// apps/kv3-admin/src/modules/_example/customColumns/_module/02ElAttrs/ElAttrsColumns.vue
<template>
  <div class="page-el-attrs-columns">
    <TableWrap
      enable-do-header
      :disabled-column-config="false"
    >
      <el-table
        :key="tableRenderKey"
        v-loading="tableLoading"
        class="do-inner-scroller page-table hide-table-border"
        :max-height="maxHeight"
        :data="tableData"
        border
        stripe
      >
        <el-table-column
          label="ID"
          prop="id"
          width="60"
          fixed="left"
          align="center"
        />
        <el-table-column
          label="名称"
          prop="name"
          min-width="120"
          fixed="left"
        />
        <el-table-column
          v-for="schema in visibleSchemas"
          :key="schema.prop"
          :prop="schema.prop"
          :label="schema.label"
          :min-width="schema.minWidth || undefined"
          :align="schema.align || 'left'"
          v-bind="schema.elAttrs || {}"
        >
          <template #default="{ row, column }">
            {{ formatSchemaCell(row[column.property], schema) }}
          </template>
        </el-table-column>
      </el-table>
    </TableWrap>
  </div>
</template>

<script setup lang="ts">
import { useSchemaColumnConfig, type ColumnSchema } from '@ku-utils/custom-columns';

import { useAdminTableMaxHeight } from '@/composables/useAdminTableMaxHeight';
import { DEMO_CUSTOM_COLUMN_MESSAGES } from '@/modules/_example/customColumns/_utils/demoSchemas';
import { useCustomColumnsDemoData } from '@/modules/_example/customColumns/_utils/useCustomColumnsDemoData';

const { tableLoading, tableData } = useCustomColumnsDemoData();

const columnSchemas: ColumnSchema[] = [
  {
    prop: 'amount',
    label: '数量',
    minWidth: 100,
    align: 'right',
    renderType: 'integer',
    isDefault: true,
    elAttrs: { 'show-overflow-tooltip': true },
  },
  {
    prop: 'cost',
    label: '成本（超长提示）',
    minWidth: 140,
    align: 'right',
    renderType: 'float',
    isDefault: true,
    elAttrs: { 'show-overflow-tooltip': true },
  },
  {
    prop: 'roi',
    label: 'ROI',
    minWidth: 100,
    align: 'right',
    renderType: 'float',
    isDefault: true,
  },
];

const maxHeight = useAdminTableMaxHeight('.page-el-attrs-columns', 400);

const { visibleSchemas, tableRenderKey, formatSchemaCell } = useSchemaColumnConfig({
  columnSchemas,
  storageKey: 'kv3-example-el-attrs',
  schemaVersion: 1,
  messages: DEMO_CUSTOM_COLUMN_MESSAGES,
});
</script>

// apps/kr-admin/src/modules/_example/customColumns/_module/02ElAttrs/ElAttrsColumns.tsx
import {
  useSchemaColumnConfig,
  DoConfigColumnDialog,
  schemasToColumns,
  SchemaColumnConfigContext,
  type ColumnSchema,
} from '@ku-utils/r-custom-columns';
import { Table } from 'antd';
import type { ColumnsType } from 'antd/es/table';

import TableWrap from '@/components/TableWrap';
import { useAdminTableMaxHeight } from '@/composables/useAdminTableMaxHeight';
import { DEMO_CUSTOM_COLUMN_MESSAGES } from '@/modules/_example/customColumns/_utils/demoSchemas';
import {
  useCustomColumnsDemoData,
  type DemoRow,
} from '@/modules/_example/customColumns/_utils/useCustomColumnsDemoData';

const columnSchemas: ColumnSchema[] = [
  {
    prop: 'amount',
    label: '数量',
    minWidth: 100,
    align: 'right',
    renderType: 'integer',
    isDefault: true,
    showOverflowTooltip: true,
    antdAttrs: { ellipsis: { showTitle: true } },
  },
  {
    prop: 'cost',
    label: '成本（超长提示）',
    minWidth: 140,
    align: 'right',
    renderType: 'float',
    isDefault: true,
    showOverflowTooltip: true,
    antdAttrs: { ellipsis: { showTitle: true } },
  },
  {
    prop: 'roi',
    label: 'ROI',
    minWidth: 100,
    align: 'right',
    renderType: 'float',
    isDefault: true,
  },
];

export default function ElAttrsColumns() {
  const maxHeight = useAdminTableMaxHeight('.page-el-attrs-columns', 400);
  const { tableLoading, tableData } = useCustomColumnsDemoData();

  const config = useSchemaColumnConfig({
    columnSchemas,
    storageKey: 'kr-example-el-attrs',
    schemaVersion: 1,
    messages: DEMO_CUSTOM_COLUMN_MESSAGES,
  });

  const columns: ColumnsType<DemoRow> = [
    {
      title: 'ID',
      dataIndex: 'id',
      width: 60,
      fixed: 'left',
      align: 'center',
    },
    {
      title: '名称',
      dataIndex: 'name',
      minWidth: 120,
      fixed: 'left',
    },
    ...schemasToColumns<DemoRow>(config.visibleSchemas, {
      formatCell: config.formatSchemaCell,
    }),
  ];

  return (
    <SchemaColumnConfigContext.Provider value={config}>
      <div className="page-el-attrs-columns">
        <TableWrap
          enableDoHeader
          disabledColumnConfig={false}
        >
          <Table
            key={config.tableRenderKey}
            className="do-inner-scroller page-table hide-table-border"
            size="middle"
            rowKey="id"
            loading={tableLoading}
            columns={columns}
            dataSource={tableData}
            pagination={false}
            bordered
            scroll={{ x: true, y: maxHeight }}
          />
        </TableWrap>
        <DoConfigColumnDialog />
      </div>
    </SchemaColumnConfigContext.Provider>
  );
}
