// apps/playground-vue2/src/demos/CustomColumnsDemo.vue
<template>
  <section
    id="custom-columns"
    class="pg-section"
  >
    <h3>@ku-utils/v2-custom-columns</h3>
    <p class="pg-hint">
      Element UI 表格 + mixin
      <code class="pg-code">useSchemaColumnConfig</code>
      +
      <code class="pg-code">DoTableHeader</code>
      。点「自定义列」可改可见列。
    </p>

    <do-table-header :disabled-column-config="false" />
    <el-table
      :key="tableRenderKey"
      :data="tableData"
      border
      stripe
      style="width: 100%"
    >
      <el-table-column
        prop="id"
        label="ID"
        width="70"
      />
      <el-table-column
        prop="name"
        label="名称"
        min-width="140"
      />
      <el-table-column
        v-for="schema in visibleSchemas"
        :key="schema.prop"
        :prop="schema.prop"
        :label="schema.label"
        :min-width="schema.minWidth"
        :align="schema.align || 'left'"
      >
        <template #default="{ row }">
          {{ formatSchemaCell(row[schema.prop], schema) }}
        </template>
      </el-table-column>
    </el-table>
  </section>
</template>

<script>
import { DoTableHeader, useSchemaColumnConfig } from '@ku-utils/v2-custom-columns';

export default {
  name: 'CustomColumnsDemo',
  components: { DoTableHeader },
  mixins: [useSchemaColumnConfig],
  data() {
    return {
      schemaStorageKey: 'pg-vue2-basic-cols',
      schemaVersion: 1,
      alwaysVisibleColumns: [
        { prop: 'id', label: 'ID' },
        { prop: 'name', label: '名称' },
      ],
      columnSchemas: [
        {
          prop: 'amount',
          label: '数量',
          minWidth: 100,
          align: 'right',
          renderType: 'integer',
          group: '数值',
          isDefault: true,
        },
        {
          prop: 'cost',
          label: '成本',
          minWidth: 110,
          align: 'right',
          renderType: 'float',
          renderArgs: [2, true],
          group: '金额',
          isDefault: true,
        },
        {
          prop: 'rate',
          label: '转化率',
          minWidth: 100,
          align: 'right',
          renderType: 'percent',
          renderArgs: [1, true],
          group: '金额',
          isDefault: true,
        },
      ],
      tableData: [
        { id: 1, name: 'Campaign A', amount: 1280, cost: 320.5, rate: 0.126 },
        { id: 2, name: 'Campaign B', amount: 860, cost: 118, rate: 0.084 },
        { id: 3, name: 'Campaign C', amount: 0, cost: 56.2, rate: 0.031 },
      ],
    };
  },
};
</script>

// apps/kr-admin/src/modules/_example/customColumns/_module/CustomColumnsDemo.tsx
import {
  useSchemaColumnConfig,
  DoTableHeader,
  DoConfigColumnDialog,
  schemasToColumns,
  SchemaColumnConfigContext,
  type ColumnSchema,
} from '@ku-utils/r-custom-columns';
import { Table } from 'antd';

const BASE_SCHEMAS: ColumnSchema[] = [
  { prop: 'id', label: 'ID', width: 80, fixed: 'left', isDefault: true },
  { prop: 'name', label: '名称', isDefault: true, showOverflowTooltip: true },
  { prop: 'groupA', label: '分组A', group: '指标', isDefault: true },
  { prop: 'groupB', label: '分组B', group: '指标' },
  { prop: 'amount', label: '金额', align: 'right', isDefault: true },
  { prop: 'rate', label: '比率', align: 'right' },
  { prop: 'status', label: '状态', isDefault: true },
  { prop: 'remark', label: '备注' },
];

const NESTED: ColumnSchema[] = [
  { prop: 'id', label: 'ID', width: 80, isDefault: true },
  {
    label: '嵌套表头',
    children: [
      { prop: 'name', label: '名称', isDefault: true },
      { prop: 'amount', label: '金额', isDefault: true },
    ],
  },
];

const DATA = Array.from({ length: 8 }, (_, i) => ({
  id: i + 1,
  name: `示例 ${i + 1}`,
  groupA: 10 + i,
  groupB: 20 + i,
  amount: 1000 * (i + 1),
  rate: `${(i + 1) * 3}%`,
  status: i % 2 ? '启用' : '停用',
  remark: '备注',
}));

export default function CustomColumnsDemo({
  title,
  mode = 'basic',
}: {
  title: string;
  mode?: 'basic' | 'nested' | 'fixed' | 'version' | 'slots';
}) {
  const schemas =
    mode === 'nested'
      ? NESTED
      : mode === 'fixed'
        ? BASE_SCHEMAS.map((s) => (s.prop === 'name' ? { ...s, fixed: 'left' as const } : s))
        : BASE_SCHEMAS;

  const config = useSchemaColumnConfig({
    columnSchemas: schemas,
    storageKey: `kr_cc_${mode}`,
    schemaVersion: mode === 'version' ? 2 : 1,
  });

  const columns = schemasToColumns(config.visibleSchemas);

  return (
    <SchemaColumnConfigContext.Provider value={config}>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
        <DoTableHeader />
        <div style={{ opacity: 0.65, fontSize: 12 }}>{title} · 自定义列</div>
        <Table
          key={config.tableRenderKey}
          size="middle"
          rowKey="id"
          columns={columns}
          dataSource={DATA}
          pagination={false}
          scroll={{ x: true }}
        />
        <DoConfigColumnDialog />
      </div>
    </SchemaColumnConfigContext.Provider>
  );
}
