// apps/kv2-admin/src/views/AccountException.vue
<template>
  <AuthStatusShell
    title-id="account-exception-title"
    icon-tone="warning"
    role="alert"
  >
    <template #icon>
      <Lock />
    </template>
    <template #title>账号异常或无权限</template>
    <template #desc>
      登录已成功，但当前账号异常、尚未开通或缺少模块权限。可重试刷新状态，或切换其他账号。
    </template>
    <template
      v-if="codeLabel || detailLabel"
      #meta
    >
      <p class="page-account-exception-meta">
        <span
          v-if="codeLabel"
          class="page-account-exception-chip"
        >
          异常码 {{ codeLabel }}
        </span>
        <span
          v-if="detailLabel"
          class="page-account-exception-chip-detail"
        >
          {{ detailLabel }}
        </span>
      </p>
    </template>
    <template #actions>
      <el-button
        type="primary"
        :loading="retryLoading"
        :disabled="switchLoading"
        @click="handleRetry"
      >
        重试
      </el-button>
      <el-button
        :loading="switchLoading"
        :disabled="retryLoading"
        @click="handleSwitchAccount"
      >
        切换账号
      </el-button>
    </template>
  </AuthStatusShell>
</template>

<script setup lang="ts">
import { Message as ElMessage } from 'element-ui';
import { computed, ref } from 'vue';
import { useRouter } from 'vue-router/composables';

import AuthStatusShell from './AuthStatusShell.vue';

import { Lock } from '@/components/icons/elIcons';
import { MODULE_PERMISSION_KEYS } from '@/maps/common/dspPermission';
import { useUserStore } from '@/stores/user';
import {
  isUserInfoMissingLocalUserCode,
  redirectToLogin,
  submitLogout,
} from '@/utils/authRedirect';

const userStore = useUserStore();
const router = useRouter();
const retryLoading = ref(false);
const switchLoading = ref(false);

const codeLabel = computed(() => {
  const code = userStore.accessDenied?.code;
  if (code === undefined || code === null || code === '') return '';
  return String(code);
});

const detailLabel = computed(() => {
  const detail = userStore.accessDenied?.detail?.trim();
  if (!detail) return '';
  return detail.length > 80 ? `${detail.slice(0, 80)}…` : detail;
});

function isUnauthorizedRetryError(error: unknown): boolean {
  if (!error || typeof error !== 'object') return false;
  const anyErr = error as {
    message?: string;
    response?: { status?: number };
    code?: number | string;
  };
  if (anyErr.message === 'unauthorized') return true;
  if (anyErr.response?.status === 401 && !isUserInfoMissingLocalUserCode(anyErr.code)) return true;
  return false;
}

function isUserNotProvisionedRetryError(error: unknown): boolean {
  if (!error || typeof error !== 'object') return false;
  const anyErr = error as { message?: string; code?: number | string };
  if (anyErr.message === 'user-not-provisioned') return true;
  return isUserInfoMissingLocalUserCode(anyErr.code);
}

async function handleRetry() {
  if (retryLoading.value || switchLoading.value) return;
  retryLoading.value = true;
  try {
    await userStore.fetchUserInfo();
    if (!MODULE_PERMISSION_KEYS.some((key) => userStore.hasPermission(key))) {
      userStore.markNoPermissionDenied();
      return;
    }
    await router.replace('/');
  } catch (error: unknown) {
    if (isUnauthorizedRetryError(error)) {
      redirectToLogin();
      return;
    }
    if (isUserNotProvisionedRetryError(error)) {
      userStore.markAccessDeniedFromError(error);
      return;
    }
    ElMessage.error({
      message: '暂时无法刷新账号状态，请稍后重试',
      showClose: true,
    });
  } finally {
    retryLoading.value = false;
  }
}

function handleSwitchAccount() {
  if (retryLoading.value || switchLoading.value) return;
  switchLoading.value = true;
  userStore.clearSession();
  submitLogout('login');
}
</script>

<style lang="scss" scoped>
.page-account-exception-meta {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: center;
  gap: 8px;
  margin: 0 0 24px;
}

.page-account-exception-chip {
  display: inline-flex;
  align-items: center;
  min-height: 28px;
  padding: 0 10px;
  border-radius: 999px;
  background: var(--el-fill-color-light);
  color: var(--el-text-color-secondary);
  font-size: 12px;
  line-height: 1;
  font-variant-numeric: tabular-nums;
}

.page-account-exception-chip-detail {
  color: var(--el-text-color-placeholder);
  font-size: 12px;
  line-height: 1.4;
}
</style>

// apps/kr-admin/src/views/AccountException.tsx
import { LockOutlined } from '@ant-design/icons';
import { Button, message } from 'antd';
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';

import { MODULE_PERMISSION_KEYS } from '@/maps/common/dspPermission';
import { submitLogout } from '@/plugins/axios';
import { resolveBusinessHomePath } from '@/router/paths';
import { useUserStore } from '@/stores/user';
import AuthStatusShell from '@/views/AuthStatusShell';

export default function AccountException() {
  const navigate = useNavigate();
  const accessDenied = useUserStore((s) => s.accessDenied);
  const fetchUserInfo = useUserStore((s) => s.fetchUserInfo);
  const hasPermission = useUserStore((s) => s.hasPermission);
  const markNoPermissionDenied = useUserStore((s) => s.markNoPermissionDenied);
  const clearSession = useUserStore((s) => s.clearSession);
  const [retryLoading, setRetryLoading] = useState(false);
  const [switchLoading, setSwitchLoading] = useState(false);

  const codeLabel =
    accessDenied?.code === undefined || accessDenied?.code === null || accessDenied?.code === ''
      ? ''
      : String(accessDenied.code);
  const detailLabel = accessDenied?.detail || '';

  async function handleRetry() {
    setRetryLoading(true);
    try {
      await fetchUserInfo();
      const ok = MODULE_PERMISSION_KEYS.some((key) => hasPermission(key));
      if (!ok) {
        markNoPermissionDenied();
        message.warning('当前账号仍无功能权限');
        return;
      }
      void navigate(resolveBusinessHomePath(), { replace: true });
    } catch {
      message.error('刷新账号状态失败');
    } finally {
      setRetryLoading(false);
    }
  }

  function handleSwitchAccount() {
    setSwitchLoading(true);
    clearSession();
    submitLogout('login');
  }

  return (
    <AuthStatusShell
      titleId="account-exception-title"
      iconTone="warning"
      role="alert"
      icon={<LockOutlined style={{ fontSize: 32 }} />}
      title="账号异常或无权限"
      desc="登录已成功，但当前账号异常、尚未开通或缺少投放权限。可重试刷新状态，或切换其他账号。"
      meta={
        codeLabel || detailLabel ? (
          <p className="page-account-exception-meta">
            {codeLabel ? (
              <span className="page-account-exception-chip">异常码 {codeLabel}</span>
            ) : null}
            {detailLabel ? (
              <span className="page-account-exception-chip-detail">{detailLabel}</span>
            ) : null}
          </p>
        ) : null
      }
      actions={
        <>
          <Button
            type="primary"
            loading={retryLoading}
            disabled={switchLoading}
            onClick={handleRetry}
          >
            重试
          </Button>
          <Button
            loading={switchLoading}
            disabled={retryLoading}
            onClick={handleSwitchAccount}
          >
            切换账号
          </Button>
        </>
      }
    />
  );
}
