// apps/kr-admin/src/App.tsx
import { useVersionUpdate } from '@ku-utils/hooks-react';
import { App as AntdApp, ConfigProvider, Spin } from 'antd';
import zhCN from 'antd/locale/zh_CN';
import { Suspense, useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react';
import { Outlet, useLocation } from 'react-router-dom';

import DialogPreviewVideo, { type DialogPreviewVideoRef } from '@/components/DialogPreviewVideo';
import { useSplashReadiness } from '@/composables/useSplashReadiness';
import BaseHeader from '@/layouts/BaseHeader';
import { AntdAppBridge } from '@/plugins/antdApp';
import { createAntdTheme } from '@/plugins/antdTheme';
import { useAppStore } from '@/stores/app';
import { registerPreviewVideoHost } from '@/utils/previewMedia';
import { fetchStaticVersion } from '@/utils/version';

export default function App() {
  const location = useLocation();
  const previewVideoRef = useRef<DialogPreviewVideoRef>(null);
  const [routerReady, setRouterReady] = useState(false);
  const themeMode = useAppStore((s) => s.theme);
  const isDark =
    themeMode === 'dark' ||
    (themeMode === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches);

  const antdTheme = useMemo(() => createAntdTheme(isDark), [isDark]);

  useEffect(() => {
    setRouterReady(true);
  }, [location.pathname]);

  useSplashReadiness(routerReady);

  useLayoutEffect(() => {
    const host = previewVideoRef.current;
    registerPreviewVideoHost(host ? { play: (url, raw) => host.play(url, raw) } : null);
    return () => registerPreviewVideoHost(null);
  }, []);

  const { hasUpdate, refreshForUpdate } = useVersionUpdate({
    fetchVersion: fetchStaticVersion,
    getVersionId: (v) => `${v.version}:${v.versionTimeISO}`,
    getVersionTime: (v) => `${v.version}:${v.versionTime}`,
  });

  const hideHeader =
    location.pathname === '/account-exception' || location.pathname === '/logged-out';

  return (
    <ConfigProvider
      locale={zhCN}
      button={{ autoInsertSpace: false }}
      theme={antdTheme}
    >
      <AntdApp component={false}>
        <AntdAppBridge />
        <div
          className="app-entry"
          style={{
            display: 'flex',
            flexDirection: 'column',
            height: '100%',
            overflow: 'hidden',
            background: 'var(--ku-bg-page-gradient, var(--ku-bg-page))',
          }}
        >
          {!hideHeader ? (
            <BaseHeader
              hasUpdate={hasUpdate}
              onRefresh={refreshForUpdate}
            />
          ) : null}
          <div
            className="app-shell-main"
            style={{ flex: 1, minHeight: 0, overflow: 'hidden' }}
          >
            <Suspense
              fallback={
                <div style={{ padding: 48, textAlign: 'center' }}>
                  <Spin />
                </div>
              }
            >
              <Outlet />
            </Suspense>
          </div>
          <DialogPreviewVideo ref={previewVideoRef} />
        </div>
      </AntdApp>
    </ConfigProvider>
  );
}

// apps/kv3-admin/src/App.vue
<template>
  <el-config-provider :locale="zhCn">
    <div
      class="app-entry"
      :class="{
        'hide-header': route.meta.hideHeader,
      }"
    >
      <BaseHeader
        v-if="!route.meta.hideHeader"
        :has-update="hasUpdate"
        @refresh="refreshForUpdate"
      />
      <div class="app-shell-main">
        <RouterView />
      </div>
      <DialogPreviewVideo ref="previewVideoRef" />
    </div>
  </el-config-provider>
</template>

<script setup lang="ts">
import { useVersionUpdate } from '@ku-utils/hooks';
import zhCn from 'element-plus/es/locale/lang/zh-cn';
import { onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { useRoute } from 'vue-router';

import DialogPreviewVideo from '@/components/DialogPreviewVideo.vue';
import { useSplashReadiness } from '@/composables/useSplashReadiness';
import BaseHeader from '@/layouts/BaseHeader.vue';
import router from '@/router';
import { registerPreviewVideoHost } from '@/utils/previewMedia';
import { fetchStaticVersion } from '@/utils/version';

const route = useRoute();
const previewVideoRef = ref<InstanceType<typeof DialogPreviewVideo> | null>(null);

const { waitForRouterReady } = useSplashReadiness(() => router.isReady());

const { hasUpdate, refreshForUpdate } = useVersionUpdate({
  fetchVersion: fetchStaticVersion,
  getVersionId: (version) => `${version.version}:${version.versionTimeISO}`,
  getVersionTime: (version) => `${version.version}:${version.versionTime}`,
});

watch(
  previewVideoRef,
  (host) => {
    registerPreviewVideoHost(host ? { play: (url, raw) => host.play(url, raw) } : null);
  },
  { immediate: true },
);

onMounted(waitForRouterReady);

onBeforeUnmount(() => {
  registerPreviewVideoHost(null);
});
</script>

<style lang="scss">
.app-entry {
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  align-items: stretch;
  height: 100%;
  overflow: hidden;
  background: var(--ku-bg-page-gradient, var(--ku-bg-page));
}

.app-shell-main {
  flex: 1;
  min-height: 0;
  overflow: hidden;
}

.hide-header .base-header {
  display: none;
}
</style>
