// apps/kv2-admin/src/layouts/DomainModuleShell.vue
<template>
  <main class="domain-module-shell">
    <aside class="domain-module-aside">
      <div class="domain-module-aside-body">
        <SideMenu :data="menus" />
      </div>
    </aside>
    <div
      class="domain-module-main"
      :class="{ 'use-full-view': route.meta.useFullView }"
    >
      <router-view />
    </div>
  </main>
</template>

<script setup lang="ts">
import { onMounted, watch } from 'vue';

import SideMenu from '@/layouts/sideMenu/index.vue';
import type { SideMenuNode } from '@/layouts/sideMenu/SideMenuItem.vue';
import { useRoute, useRouter } from '@/shims/vue-router-composables';

const props = defineProps<{
  menus: SideMenuNode[];
  /** 顶栏 Tab 根 path，如 /asset；用于进入域根时跳到首个叶子 */
  moduleRootPath: string;
}>();

const route = useRoute();
const router = useRouter();

/** menus 为扁平叶子列表（顶栏已展示域名，侧栏不再套一级分组） */
function firstLeafPath(node: string | SideMenuNode | undefined): string | undefined {
  if (!node) return undefined;
  if (typeof node === 'string') return node;
  if (node.children?.length) return firstLeafPath(node.children[0]);
  return node.path;
}

function triggerMenu() {
  if (!route.meta.isHeaderTab) return;
  const leaf = firstLeafPath(props.menus[0]);
  if (leaf && route.path === props.moduleRootPath) {
    router.replace(leaf).catch(console.error);
  }
}

watch(
  () => route.fullPath,
  () => triggerMenu(),
);

onMounted(() => triggerMenu());
</script>

<style lang="scss" scoped>
.domain-module-shell {
  display: flex;
  height: 100%;
  overflow: hidden;
  background: var(--ku-bg-sidebar);
}

.domain-module-aside {
  width: var(--ku-layout-aside-width, 220px);
  flex-shrink: 0;
  height: 100%;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  background: var(--ku-bg-sidebar);
  border-right: 1px solid var(--ku-border-light);
}

.domain-module-aside-body {
  flex: 1;
  min-height: 0;
  overflow-x: hidden;
  overflow-y: auto;
  padding: 12px 0;
}

.domain-module-main {
  flex: 1;
  min-width: 0;
  min-height: 0;
  overflow: auto;
  padding: 0 20px 20px;
  background: var(--ku-bg-page-gradient);
  background-attachment: local;
}

.domain-module-main.use-full-view {
  display: flex;
  flex-direction: column;
  padding: 0;
  overflow: hidden;
}
</style>

// apps/kr-admin/src/layouts/DomainModuleShell.tsx
import { useEffect } from 'react';
import { Outlet, useLocation, useNavigate } from 'react-router-dom';

import SideMenu, { type SideMenuNode } from '@/layouts/sideMenu';

function firstLeafPath(node: string | SideMenuNode | undefined): string | undefined {
  if (!node) return undefined;
  if (typeof node === 'string') return node;
  if (node.children?.length) return firstLeafPath(node.children[0]);
  return node.path;
}

export type DomainModuleShellProps = {
  menus: SideMenuNode[];
  moduleRootPath: string;
};

export function DomainModuleShell({ menus, moduleRootPath }: DomainModuleShellProps) {
  const location = useLocation();
  const navigate = useNavigate();

  useEffect(() => {
    const leaf = firstLeafPath(menus[0]);
    if (leaf && location.pathname === moduleRootPath) {
      void navigate(leaf, { replace: true });
    }
  }, [location.pathname, menus, moduleRootPath, navigate]);

  return (
    <main
      className="domain-module-shell"
      style={{
        display: 'flex',
        height: '100%',
        minHeight: 0,
        overflow: 'hidden',
        background: 'transparent',
      }}
    >
      <aside
        className="domain-module-aside sidebar-nav"
        style={{
          width: 220,
          flexShrink: 0,
          borderRight: '1px solid var(--ku-border-color-sidebar, transparent)',
          background: 'var(--ku-bg-sidebar, #2f2a26)',
          overflow: 'auto',
        }}
      >
        <div className="domain-module-aside-body">
          <SideMenu
            menus={menus}
            moduleRootPath={moduleRootPath}
          />
        </div>
      </aside>
      <div
        className="domain-module-main"
        style={{
          flex: 1,
          minWidth: 0,
          minHeight: 0,
          padding: 20,
          overflow: 'auto',
          display: 'flex',
          flexDirection: 'column',
          gap: 12,
        }}
      >
        <Outlet />
      </div>
    </main>
  );
}

export default DomainModuleShell;
