// packages/r-custom-columns/src/components/DoConfigColumnDialog.tsx
import { CloseOutlined, LockOutlined, SearchOutlined } from '@ant-design/icons';
import { App, Button, Checkbox, Drawer, Input, Popover, message as staticMessage } from 'antd';
import type { InputRef } from 'antd';
import { forwardRef, useEffect, useImperativeHandle, useMemo, useRef, useState } from 'react';
import Sortable from 'sortablejs';

import { useOptionalSchemaColumnConfigContext } from '../context';
import type { ColumnConfig, TableColumnMeta } from '../types';
import { DEFAULT_CUSTOM_COLUMN_MESSAGES } from '../useSchemaColumnConfig';

import { DoReadColumnConfig } from './DoReadColumnConfig';

export interface DoConfigColumnDialogProps {
  /** 点击「完成」，携带当前配置 */
  onConfirm?: (config: ColumnConfig) => void;
}

export interface DoConfigColumnDialogRef {
  /** 打开抽屉；不传则用默认配置 */
  showConfigColumnDialog: (currentConfig?: ColumnConfig) => void;
}

/**
 * 自定义列配置抽屉：左侧分组导航、中间分组勾选、右侧已选列（固定区 + 拖拽排序），
 * 底部存到本地 / 读取本地 / 取消 / 完成。需在 SchemaColumnConfigContext 内使用。
 */
export const DoConfigColumnDialog = forwardRef<DoConfigColumnDialogRef, DoConfigColumnDialogProps>(
  function DoConfigColumnDialog({ onConfirm }, ref) {
    const ctx = useOptionalSchemaColumnConfigContext();
    const messages = ctx?.messages ?? DEFAULT_CUSTOM_COLUMN_MESSAGES;
    const noNameLabel = ctx?.noNameLabel || messages.noNameLabel;
    const maxCount = ctx?.maxSelectCount || 50;
    const { message: appMessage } = App.useApp();
    const message = typeof appMessage.warning === 'function' ? appMessage : staticMessage;

    const [visible, setVisible] = useState(false);
    const [popperSaveToLocal, setPopperSaveToLocal] = useState(false);
    const [popperReadFromLocal, setPopperReadFromLocal] = useState(false);
    const [columnList, setColumnList] = useState<TableColumnMeta[]>([]);
    const [emitColumnConfig, setEmitColumnConfig] = useState<TableColumnMeta[]>([]);
    const [newConfigName, setNewConfigName] = useState(noNameLabel);
    const [searchKeyword, setSearchKeyword] = useState('');
    const [activeNavGroup, setActiveNavGroup] = useState('');

    const midPanelRef = useRef<HTMLDivElement>(null);
    const groupRefs = useRef(new Map<string, HTMLElement>());
    const inputConfigNameRef = useRef<InputRef>(null);
    const [dragZoneEl, setDragZoneEl] = useState<HTMLDivElement | null>(null);

    const unableToControl = (col: TableColumnMeta): boolean =>
      col.type === 'selection' ||
      col.fixed ||
      col.label === messages.operationColumnLabel ||
      col.label === '操作';

    const groupOf = (col: TableColumnMeta) => col.group || messages.groupFallback;

    const uniqueGroups = useMemo(() => {
      const seen = new Set<string>();
      columnList.forEach((item) => seen.add(item.group || messages.groupFallback));
      return [...seen];
    }, [columnList, messages.groupFallback]);

    const filteredGroups = useMemo(() => {
      const keyword = searchKeyword.trim().toLowerCase();
      const groupMap = new Map<string, TableColumnMeta[]>();
      columnList.forEach((item) => {
        if (keyword && !item.label.toLowerCase().includes(keyword)) return;
        const g = item.group || messages.groupFallback;
        if (!groupMap.has(g)) groupMap.set(g, []);
        groupMap.get(g)!.push(item);
      });
      return uniqueGroups
        .filter((g) => groupMap.has(g))
        .map((g) => ({ label: g, children: groupMap.get(g)! }));
    }, [columnList, searchKeyword, uniqueGroups, messages.groupFallback]);

    const alwaysCols = useMemo<TableColumnMeta[]>(
      () =>
        (ctx?.alwaysVisibleColumns || []).map((col) => ({
          property: col.prop,
          label: col.label,
          fixed: true,
          group: messages.groupFallback,
          isLeaf: true,
          visible: true,
          _alwaysVisible: true,
        })),
      [ctx?.alwaysVisibleColumns, messages.groupFallback],
    );

    const fixedSelectedCols = [...alwaysCols, ...emitColumnConfig.filter(unableToControl)];
    const draggableList = emitColumnConfig.filter((col) => !unableToControl(col));

    /** 与本地缓存逐一比对，命中则沿用其名称，否则视为未命名 */
    const matchConfigName = (cols: TableColumnMeta[]): string | null => {
      const cache = ctx?.readCacheConfig();
      if (!cache) return null;
      const temp = JSON.stringify(cols.map((item) => item.property));
      const hit = cache.columnConfig.filter((config) => JSON.stringify(config.columns) === temp);
      return hit.length ? hit[hit.length - 1].label : noNameLabel;
    };

    const commitEmit = (cols: TableColumnMeta[]) => {
      setEmitColumnConfig(cols);
      const name = matchConfigName(cols);
      if (name !== null) setNewConfigName(name);
    };

    const syncEmitWithVisible = (list: TableColumnMeta[]) => {
      const visibleProps = list.filter((col) => col.visible).map((col) => col.property);
      const next = emitColumnConfig.filter((col) => visibleProps.includes(col.property));
      visibleProps.forEach((property) => {
        if (next.some((col) => col.property === property)) return;
        const col = list.find((c) => c.property === property);
        if (col) next.push(col);
      });
      setColumnList(list);
      commitEmit(next);
    };

    const applyConfig = (columnConfig: ColumnConfig) => {
      if (!ctx) return;
      setNewConfigName(columnConfig.label);
      const allColumns = ctx.tableColumns.map((item) => ({
        ...item,
        visible: columnConfig.columns.includes(item.property as string),
      }));
      setColumnList(allColumns);
      setEmitColumnConfig(
        columnConfig.columns
          .map((property) => allColumns.find((col) => col.property === property))
          .filter((col): col is TableColumnMeta => !!col),
      );
    };

    useImperativeHandle(ref, () => ({
      showConfigColumnDialog(currentConfig?: ColumnConfig) {
        if (!ctx) return;
        const columnConfig = currentConfig || ctx.getDefaultConfig();
        if (!columnConfig) return;
        applyConfig(columnConfig);
        const first = ctx.tableColumns[0];
        setActiveNavGroup(first ? first.group || messages.groupFallback : '');
        setSearchKeyword('');
        setVisible(true);
      },
    }));

    const closePoppers = () => {
      setPopperSaveToLocal(false);
      setPopperReadFromLocal(false);
    };

    const cancelColumnConfig = () => {
      closePoppers();
      setVisible(false);
      ctx?.onDialogClose?.();
    };

    const confirmColumnConfig = () => {
      closePoppers();
      setVisible(false);
      onConfirm?.({
        label: newConfigName || noNameLabel,
        columns: emitColumnConfig
          .filter((config) => !config._alwaysVisible)
          .map((config) => config.property as string),
      });
    };

    const resetConfig = () => {
      const defaultConfig = ctx?.getDefaultConfig();
      if (!defaultConfig) return;
      applyConfig(defaultConfig);
      const allColumns = ctx!.tableColumns;
      const name = matchConfigName(
        defaultConfig.columns
          .map((property) => allColumns.find((col) => col.property === property))
          .filter((col): col is TableColumnMeta => !!col),
      );
      if (name !== null) setNewConfigName(name);
    };

    const toggleColumnCheck = (checked: boolean, col: TableColumnMeta) => {
      if (checked && !unableToControl(col)) {
        const willCount = draggableList.length + 1;
        if (willCount > maxCount) {
          message.warning(messages.maxSelectedWarning(maxCount));
          return;
        }
      }
      syncEmitWithVisible(
        columnList.map((item) =>
          item.property === col.property ? { ...item, visible: checked } : item,
        ),
      );
    };

    const groupSelect = (group: string, pick: (item: TableColumnMeta) => boolean) => {
      syncEmitWithVisible(
        columnList.map((item) =>
          !unableToControl(item) && groupOf(item) === group
            ? { ...item, visible: pick(item) }
            : item,
        ),
      );
    };

    const removeSelectedItem = (property?: string) => {
      setColumnList(
        columnList.map((item) => (item.property === property ? { ...item, visible: false } : item)),
      );
      commitEmit(emitColumnConfig.filter((c) => c.property !== property));
    };

    const emitRef = useRef(emitColumnConfig);
    emitRef.current = emitColumnConfig;
    const reorderRef = useRef<(oldIndex: number, newIndex: number) => void>(() => {});
    reorderRef.current = (oldIndex, newIndex) => {
      const current = emitRef.current;
      const reordered = current.filter((col) => !unableToControl(col));
      const [moved] = reordered.splice(oldIndex, 1);
      reordered.splice(newIndex, 0, moved);
      const schemaFixed = current.filter((col) => unableToControl(col) && !col._alwaysVisible);
      commitEmit([...schemaFixed, ...reordered]);
    };

    useEffect(() => {
      if (!dragZoneEl) return;
      const sortable = Sortable.create(dragZoneEl, {
        animation: 200,
        handle: '.sel-drag-handle',
        onUpdate(evt) {
          const { item, from, oldIndex, newIndex } = evt;
          if (oldIndex === undefined || newIndex === undefined) return;
          // 还原 Sortable 的 DOM 移动，交由 React 按新顺序渲染
          from.removeChild(item);
          from.insertBefore(item, from.children[oldIndex] ?? null);
          reorderRef.current(oldIndex, newIndex);
        },
      });
      return () => sortable.destroy();
    }, [dragZoneEl]);

    const scrollToGroup = (group: string) => {
      setActiveNavGroup(group);
      const domEl = groupRefs.current.get(group);
      const panel = midPanelRef.current;
      if (domEl && panel) {
        panel.scrollTo({ top: domEl.offsetTop - panel.offsetTop, behavior: 'smooth' });
      }
    };

    const onMidScroll = () => {
      const panel = midPanelRef.current;
      if (!panel) return;
      const { scrollTop } = panel;
      for (let i = uniqueGroups.length - 1; i >= 0; i--) {
        const domEl = groupRefs.current.get(uniqueGroups[i]);
        if (!domEl) continue;
        if (domEl.offsetTop - panel.offsetTop <= scrollTop + 8) {
          setActiveNavGroup(uniqueGroups[i]);
          break;
        }
      }
    };

    const applyReadConfig = (config: ColumnConfig) => {
      if (!ctx || !config || !config.label || !columnList.length) return;
      const columns =
        !config.columns || !config.columns.length || config.columns.includes('ALL')
          ? ctx.tableColumns.map((each) => each.property as string)
          : config.columns;
      setPopperReadFromLocal(false);
      setNewConfigName(config.label);
      const list = columnList.map((item) => ({
        ...item,
        visible: columns.includes(item.property as string),
      }));
      setColumnList(list);
      setEmitColumnConfig(
        columns
          .map((property) => list.find((col) => col.property === property))
          .filter((col): col is TableColumnMeta => !!col),
      );
    };

    const toSaveToLocal = () => {
      setNewConfigName('');
      setPopperSaveToLocal(true);
      setPopperReadFromLocal(false);
    };

    useEffect(() => {
      if (!popperSaveToLocal) return;
      const id = requestAnimationFrame(() => inputConfigNameRef.current?.focus());
      return () => cancelAnimationFrame(id);
    }, [popperSaveToLocal]);

    const doSaveToLocal = () => {
      if (!ctx || !newConfigName || !newConfigName.trim()) {
        message.warning(messages.configNameRequired);
        return;
      }
      const configName = newConfigName.trim();
      if (ctx.readCacheConfig()?.columnConfig?.some((c) => c.label === configName)) {
        message.warning(messages.configNameExists);
        return;
      }
      ctx.saveConfigToLocal(
        configName,
        emitColumnConfig.map((config) => config.property as string),
      );
      setPopperSaveToLocal(false);
      message.success(messages.configSaved);
    };

    const cancelSaveToLocal = () => {
      const name = matchConfigName(emitColumnConfig);
      if (name !== null) setNewConfigName(name);
      setPopperSaveToLocal(false);
    };

    return (
      <Drawer
        open={visible}
        onClose={cancelColumnConfig}
        className="do-config-column-dialog"
        width={1000}
        placement="right"
        closable={false}
        title={
          <span className="drawer-title">
            {messages.customColumns}{' '}
            <span
              className={[
                'tips',
                newConfigName === noNameLabel ? 'status-warning' : 'status-success',
              ].join(' ')}
            >
              ({newConfigName})
            </span>
          </span>
        }
        extra={
          <button
            type="button"
            className="drawer-close"
            aria-label="Close"
            onClick={cancelColumnConfig}
          >
            <CloseOutlined />
          </button>
        }
      >
        <div className="drawer-wrap">
          <div className="col-dialog-body">
            <div className="cfg-search">
              <Input
                value={searchKeyword}
                onChange={(e) => setSearchKeyword(e.target.value)}
                placeholder={messages.searchPlaceholder}
                allowClear
                size="small"
                prefix={<SearchOutlined />}
              />
            </div>

            <div className="cfg-panels">
              <div className="cfg-left">
                {uniqueGroups.map((group) => (
                  <div
                    key={group}
                    className={['nav-link', activeNavGroup === group ? 'active' : '']
                      .filter(Boolean)
                      .join(' ')}
                    onClick={() => scrollToGroup(group)}
                  >
                    {group}
                  </div>
                ))}
              </div>

              <div
                ref={midPanelRef}
                className="cfg-mid"
                onScroll={onMidScroll}
              >
                {filteredGroups.map((group) => (
                  <div
                    key={group.label}
                    ref={(el) => {
                      if (el) groupRefs.current.set(group.label, el);
                      else groupRefs.current.delete(group.label);
                    }}
                    className="grp-section"
                  >
                    <div className="grp-head">
                      <span className="grp-label">{group.label}</span>
                      <span className="grp-actions">
                        <a onClick={() => groupSelect(group.label, () => true)}>
                          {messages.selectAll}
                        </a>
                        <a onClick={() => groupSelect(group.label, (item) => !item.visible)}>
                          {messages.invertSelection}
                        </a>
                      </span>
                    </div>
                    <div className="grp-grid">
                      {group.children.map((col) => (
                        <div
                          key={col.property}
                          className="grp-item"
                        >
                          <Checkbox
                            checked={col.visible}
                            disabled={unableToControl(col)}
                            onChange={(e) => toggleColumnCheck(e.target.checked, col)}
                          >
                            {col.label}
                          </Checkbox>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
                {filteredGroups.length === 0 ? (
                  <div className="grp-empty">{messages.emptySearch}</div>
                ) : null}
              </div>

              <div className="cfg-right">
                <div className="sel-header">
                  <span className="sel-count">
                    {messages.selectedCount(emitColumnConfig.length, maxCount)}
                  </span>
                  <a
                    className="sel-reset"
                    onClick={resetConfig}
                  >
                    {messages.reset}
                  </a>
                </div>

                <div className="sel-body">
                  {fixedSelectedCols.length ? (
                    <>
                      <div className="sel-fix-zone">
                        {fixedSelectedCols.map((col) => (
                          <div
                            key={col.property}
                            className="sel-fix-row"
                          >
                            <LockOutlined className="sel-lock" />
                            <span className="sel-fix-name">{col.label}</span>
                          </div>
                        ))}
                      </div>
                      <div className="sel-sepline">
                        <span className="sel-septip">{messages.fixedColumnsTip}</span>
                      </div>
                    </>
                  ) : null}

                  <div className="sel-drag-zone">
                    <div ref={setDragZoneEl}>
                      {draggableList.map((col) => (
                        <div
                          key={col.property}
                          className="sel-drag-row"
                        >
                          <span className="sel-drag-handle">
                            <span className="sel-drag-dots" />
                          </span>
                          <span
                            className="sel-drag-name"
                            title={col.label}
                          >
                            {col.label}
                          </span>
                          <CloseOutlined
                            className="sel-remove"
                            onClick={() => removeSelectedItem(col.property)}
                          />
                        </div>
                      ))}
                    </div>
                    {draggableList.length === 0 ? (
                      <div className="sel-empty">{messages.emptySelected}</div>
                    ) : null}
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="drawer-foot">
            <div className="left-btn-group">
              <Popover
                open={popperSaveToLocal}
                placement="top"
                trigger={[]}
                rootClassName="save-to-local-popper"
                content={
                  <div className="save-to-local-form">
                    <Input
                      ref={inputConfigNameRef}
                      className="storage-key-will-save"
                      value={newConfigName}
                      onChange={(e) => setNewConfigName(e.target.value)}
                      placeholder={messages.configNamePlaceholder}
                    />
                    <Button
                      size="small"
                      onClick={cancelSaveToLocal}
                    >
                      {messages.cancel}
                    </Button>
                    <Button
                      size="small"
                      onClick={doSaveToLocal}
                    >
                      {messages.save}
                    </Button>
                  </div>
                }
              >
                <Button onClick={toSaveToLocal}>{messages.saveToLocal}</Button>
              </Popover>

              <Popover
                open={popperReadFromLocal}
                onOpenChange={(open) => {
                  setPopperReadFromLocal(open);
                  if (open) setPopperSaveToLocal(false);
                }}
                placement="top"
                trigger="click"
                rootClassName="read-from-local-popper"
                content={
                  <DoReadColumnConfig
                    onConfirm={applyReadConfig}
                    onRemove={(label) => ctx?.removeConfigFromLocal(label)}
                    onClosed={() => setPopperReadFromLocal(false)}
                  />
                }
              >
                <Button>{messages.readFromLocal}</Button>
              </Popover>
            </div>

            <div className="right-btn-group">
              <Button onClick={cancelColumnConfig}>{messages.cancel}</Button>
              <Button
                type="primary"
                onClick={confirmColumnConfig}
              >
                {messages.complete}
              </Button>
            </div>
          </div>
        </div>
      </Drawer>
    );
  },
);

// packages/v2-custom-columns/src/components/DoConfigColumnDialog.vue
<!--
@file: DoConfigColumnDialog.vue
@description: 自定义列弹框 — 三栏式布局（左导航 / 中指标勾选 / 右已选列）
 -->
<template>
  <el-drawer
    custom-class="do-config-column-dialog"
    :visible.sync="dialogConfigColumnVisible"
    :append-to-body="true"
    size="1000px"
    direction="rtl"
    :before-close="handleBeforeClose"
  >
    <template #title>
      <span class="drawer-title">
        自定义列
        <span
          class="tips"
          :class="[`${newConfigName === labelNoName ? 'status-warning' : 'status-success'}`]"
        >
          ({{ newConfigName }})
        </span>
      </span>
    </template>

    <div class="drawer-wrap">
      <div class="col-dialog-body">
        <!-- 搜索栏 -->
        <div class="cfg-search">
          <el-input
            v-model="searchKeyword"
            placeholder="请搜索指标"
            prefix-icon="el-icon-search"
            clearable
            size="small"
          ></el-input>
        </div>

        <!-- 三栏面板 -->
        <div class="cfg-panels">
          <!-- 左侧分类导航 -->
          <div class="cfg-left">
            <div
              v-for="group in uniqueGroups"
              :key="group"
              class="nav-link"
              :class="{ 'is-active': activeNavGroup === group }"
              @click="scrollToGroup(group)"
            >
              {{ group }}
            </div>
          </div>

          <!-- 中间指标勾选区 -->
          <div
            ref="cfgMid"
            class="cfg-mid"
            @scroll="onMidScroll"
          >
            <div
              v-for="group in filteredGroups"
              :key="group.label"
              :ref="'grp_' + group.label"
              class="grp-section"
            >
              <div class="grp-head">
                <span class="grp-label">{{ group.label }}</span>
                <span class="grp-actions">
                  <a
                    href="javascript:"
                    @click="groupColumnAllSelect(group.label)"
                  >
                    全选
                  </a>
                  <a
                    href="javascript:"
                    @click="groupColumnReverseSelect(group.label)"
                  >
                    反选
                  </a>
                </span>
              </div>
              <div class="grp-grid">
                <div
                  v-for="col in group.children"
                  :key="col.property"
                  class="grp-item"
                >
                  <el-checkbox
                    v-model="col.visible"
                    :disabled="unableToControl(col)"
                    @change="toggleColumnCheck($event, col)"
                  >
                    {{ col.label }}
                  </el-checkbox>
                </div>
              </div>
            </div>
            <div
              v-if="filteredGroups.length === 0"
              class="grp-empty"
            >
              未找到相关指标
            </div>
          </div>

          <!-- 右侧已选列 -->
          <div class="cfg-right">
            <div class="sel-header">
              <span class="sel-count">已添加 ({{ selectedCount }}/{{ maxCount }})</span>
              <a
                class="sel-reset"
                href="javascript:"
                @click="resetConfig"
              >
                重置
              </a>
            </div>

            <div class="sel-body">
              <!-- 固定列区域（有固定列时显示） -->
              <template v-if="fixedSelectedCols.length">
                <div class="sel-fix-zone">
                  <div
                    v-for="col in fixedSelectedCols"
                    :key="col.property"
                    class="sel-fix-row"
                  >
                    <i class="el-icon-lock sel-lock"></i>
                    <span class="sel-fix-name">{{ col.label }}</span>
                  </div>
                </div>
                <div class="sel-sepline">
                  <span class="sel-septip">以上指标横向固定</span>
                </div>
              </template>

              <!-- 可拖拽列区域 -->
              <div class="sel-drag-zone">
                <draggable
                  :value="draggableSelectedCols"
                  animation="200"
                  handle=".sel-drag-handle"
                  @input="onDragReorder"
                >
                  <div
                    v-for="col in draggableSelectedCols"
                    :key="col.property"
                    class="sel-drag-row"
                  >
                    <span class="sel-drag-handle">
                      <span class="sel-drag-dots"></span>
                    </span>
                    <span
                      class="sel-drag-name"
                      :title="col.label"
                    >
                      {{ col.label }}
                    </span>
                    <i
                      class="el-icon-close sel-remove"
                      @click="removeSelectedItem(col.property)"
                    ></i>
                  </div>
                </draggable>
                <div
                  v-if="draggableSelectedCols.length === 0"
                  class="sel-empty"
                >
                  暂无已选列
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- 抽屉底部操作栏（el-drawer 无 footer slot，写在 body 内） -->
      <div class="drawer-foot">
        <div class="left-btn-group">
          <el-popover
            v-model="popperSaveToLocal"
            placement="top"
            popper-class="save-to-local-popper"
            trigger="manual"
          >
            <template #default>
              <div class="save-to-local-form">
                <el-input
                  ref="inputConfigName"
                  v-model="newConfigName"
                  class="storage-key-will-save"
                  autofocus
                  placeholder="请输入配置名称"
                ></el-input>
                <el-button
                  class="save-to-local-confirm"
                  plain
                  size="small"
                  @click="cancelSaveToLocal"
                >
                  取消
                </el-button>
                <el-button
                  class="save-to-local-confirm"
                  plain
                  size="small"
                  @click="doSaveToLocal"
                >
                  保存
                </el-button>
              </div>
            </template>

            <template #reference>
              <el-button
                class="save-to-local-btn"
                @click="toSaveToLocal"
              >
                存到本地
              </el-button>
            </template>
          </el-popover>

          <el-popover
            v-model="popperReadFromLocal"
            placement="top"
            popper-class="read-from-local-popper"
            trigger="click"
          >
            <template #default>
              <do-read-column-config
                ref="doReadColumnConfig"
                @confirm="useReadConfig"
                @remove="removeChooseConfig"
                @closed="cancelChooseConfig"
              ></do-read-column-config>
            </template>

            <template #reference>
              <el-button @click="toReadFromLocal">读取本地</el-button>
            </template>
          </el-popover>
        </div>

        <div class="right-btn-group">
          <el-button @click="cancelColumnConfig">取 消</el-button>
          <el-button
            type="primary"
            @click="confirmColumnConfig"
          >
            完 成
          </el-button>
        </div>
      </div>
    </div>
  </el-drawer>
</template>

<script>
import Draggable from 'vuedraggable';

import DoReadColumnConfig from './DoReadColumnConfig.vue';

export default {
  name: 'DoConfigColumnDialog',
  components: {
    DoReadColumnConfig,
    Draggable,
  },
  inject: {
    crud: {
      from: 'crud',
      default: null,
    },
  },
  data() {
    return {
      popperSaveToLocal: false,
      popperReadFromLocal: false,
      dialogConfigColumnVisible: false,

      columnList: [],
      emitColumnConfig: [],
      newConfigName: (this.crud && this.crud.noNameLabel) || '未命名配置',

      searchKeyword: '',
      activeNavGroup: '',
      /** 弹窗打开时自动检测到的硬编码固定列，每次 showConfigColumnDialog 刷新 */
      detectedAlwaysCols: [],
      /** rename 模式下记录原配置名，用于允许同名覆盖保存 */
      renamingLabel: null,
    };
  },
  computed: {
    labelNoName() {
      if (!this.crud) {
        return '';
      }
      return this.crud.noNameLabel;
    },
    maxCount() {
      return (this.crud && this.crud.maxSelectCount) || 50;
    },
    selectedCount() {
      return this.emitColumnConfig.length;
    },
    /** 从 columnList 提取有序不重复的 group 名（用于左侧导航） */
    uniqueGroups() {
      const seen = new Set();
      const groups = [];
      this.columnList.forEach((item) => {
        const g = item.group || '未分组';
        if (!seen.has(g)) {
          seen.add(g);
          groups.push(g);
        }
      });
      return groups;
    },
    /**
     * 按搜索关键字过滤后的分组列表（用于中间指标区渲染）
     * 结构：[{ label: 'groupName', children: [...colItems] }]
     */
    filteredGroups() {
      const keyword = this.searchKeyword.trim().toLowerCase();
      const groupMap = new Map();

      this.columnList.forEach((item) => {
        const g = item.group || '未分组';
        if (keyword && !item.label.toLowerCase().includes(keyword)) {
          return;
        }
        if (!groupMap.has(g)) {
          groupMap.set(g, { label: g, children: [] });
        }
        groupMap.get(g).children.push(item);
      });

      return this.uniqueGroups.filter((g) => groupMap.has(g)).map((g) => groupMap.get(g));
    },
    /**
     * 硬编码固定列列表
     */
    alwaysCols() {
      const detected = this.detectedAlwaysCols || [];
      const manual = (this.crud && this.crud.alwaysVisibleColumns) || [];
      const seenProps = new Set(detected.map((c) => c.prop));
      const merged = [...detected, ...manual.filter((c) => !seenProps.has(c.prop))];
      return merged.map((col) => ({ ...col, fixed: true, _alwaysVisible: true }));
    },
    fixedSelectedCols() {
      const schemaFixed = this.emitColumnConfig.filter((col) => this.unableToControl(col));
      return [...this.alwaysCols, ...schemaFixed];
    },
    draggableSelectedCols() {
      return this.emitColumnConfig.filter((col) => !this.unableToControl(col));
    },
  },
  methods: {
    /**
     * el-drawer 的 before-close 钩子
     * 关闭后调用 crud.onDialogClose（若消费方提供）
     */
    handleBeforeClose(done) {
      this.popperSaveToLocal = false;
      this.popperReadFromLocal = false;
      done();
      this.$nextTick(() => {
        if (this.crud && typeof this.crud.onDialogClose === 'function') {
          this.crud.onDialogClose();
        }
      });
    },
    cancelColumnConfig() {
      this.popperSaveToLocal = false;
      this.popperReadFromLocal = false;
      this.dialogConfigColumnVisible = false;
      this.$nextTick(() => {
        if (this.crud && typeof this.crud.onDialogClose === 'function') {
          this.crud.onDialogClose();
        }
      });
    },
    confirmColumnConfig() {
      this.popperSaveToLocal = false;
      this.popperReadFromLocal = false;
      this.dialogConfigColumnVisible = false;
      this.$emit('confirm', {
        label: this.newConfigName || this.labelNoName,
        columns: this.emitColumnConfig
          .filter((config) => !config._alwaysVisible)
          .map((config) => config.property),
      });
    },
    showConfigColumnDialog(currentConfig) {
      if (!this.crud) {
        return;
      }
      const columnConfig = currentConfig || this.crud.getDefaultConfig();
      if (!columnConfig) {
        return;
      }

      this.detectedAlwaysCols =
        typeof this.crud._detectHardcodedCols === 'function'
          ? this.crud._detectHardcodedCols()
          : [];

      this._applyConfig(columnConfig);
      this.searchKeyword = '';
      this.dialogConfigColumnVisible = true;

      this.$nextTick(() => {
        this._syncActiveNavGroup();
      });
    },
    showConfigColumnDialogWithRename(config) {
      this.showConfigColumnDialog(config);
      this.renamingLabel = config.label;
      this.$nextTick(() => {
        this.newConfigName = config.label;
        this.popperSaveToLocal = true;
        this.popperReadFromLocal = false;
        this.$nextTick(() => {
          const { inputConfigName } = this.$refs;
          if (inputConfigName && inputConfigName.focus) {
            inputConfigName.focus();
          }
        });
      });
    },
    _applyConfig(columnConfig) {
      this.newConfigName = columnConfig.label;

      const allColumns = this.crud.tableColumns.reduce((newArr, item) => {
        const isVisible = columnConfig.columns.includes(item.property);
        return [...newArr, { ...item, visible: isVisible }];
      }, []);

      this.columnList = allColumns;

      this.emitColumnConfig = columnConfig.columns
        .map((property) => allColumns.find((col) => col.property === property))
        .filter((col) => col);
    },
    resetConfig() {
      if (!this.crud) {
        return;
      }
      const defaultConfig = this.crud.getDefaultConfig();
      if (!defaultConfig) {
        return;
      }
      this._applyConfig(defaultConfig);
      this.updateNewConfigName();
    },
    unableToControl(col) {
      return col.type === 'selection' || col.fixed || col.label === '操作';
    },
    onDragReorder(newDraggableOrder) {
      const schemaFixed = this.fixedSelectedCols.filter((col) => !col._alwaysVisible);
      this.emitColumnConfig = [...schemaFixed, ...newDraggableOrder];
      this.updateNewConfigName();
    },
    updateEmitColumnConfig() {
      const currentProperties = this.emitColumnConfig.map((col) => col.property);
      const newVisibleProperties = this.columnList
        .filter((col) => col.visible)
        .map((col) => col.property);

      this.emitColumnConfig = this.emitColumnConfig.filter((col) =>
        newVisibleProperties.includes(col.property),
      );

      newVisibleProperties.forEach((property) => {
        if (!currentProperties.includes(property)) {
          const col = this.columnList.find((c) => c.property === property);
          if (col) {
            this.emitColumnConfig.push(col);
          }
        }
      });

      this.updateNewConfigName();
    },
    updateNewConfigName() {
      if (!this.crud) {
        return;
      }
      const cacheColumnConfig = this.crud.readCacheConfig();
      if (!cacheColumnConfig) {
        return;
      }
      const tempConfig = this.emitColumnConfig.map((item) => item.property);
      let found = false;
      cacheColumnConfig.columnConfig.forEach((config) => {
        if (JSON.stringify(config.columns) === JSON.stringify(tempConfig)) {
          found = true;
          this.newConfigName = config.label;
        }
      });
      if (!found) {
        this.newConfigName = this.crud.noNameLabel;
      }
    },
    toggleColumnCheck(checked, col) {
      if (checked && !this.unableToControl(col)) {
        const willCount = this.emitColumnConfig.filter((c) => !this.unableToControl(c)).length + 1;
        if (willCount > this.maxCount) {
          this.$message.warning(`已选列数量已达上限 ${this.maxCount} 个`);
          this.$nextTick(() => {
            col.visible = false;
          });
          return;
        }
      }
      this.updateEmitColumnConfig();
    },
    groupColumnAllSelect(group) {
      this.columnList.forEach((item) => {
        if (!this.unableToControl(item)) {
          const itemGroup = item.group || '未分组';
          if (itemGroup === group) {
            item.visible = true;
          }
        }
      });
      this.updateEmitColumnConfig();
    },
    groupColumnReverseSelect(group) {
      this.columnList.forEach((item) => {
        if (!this.unableToControl(item)) {
          const itemGroup = item.group || '未分组';
          if (itemGroup === group) {
            item.visible = !item.visible;
          }
        }
      });
      this.updateEmitColumnConfig();
    },
    removeSelectedItem(property) {
      const col = this.columnList.find((c) => c.property === property);
      if (col) {
        col.visible = false;
      }
      this.emitColumnConfig = this.emitColumnConfig.filter((c) => c.property !== property);
      this.updateNewConfigName();
    },
    scrollToGroup(group) {
      this.activeNavGroup = group;
      const refKey = `grp_${group}`;
      const refEl = this.$refs[refKey];
      const el = Array.isArray(refEl) ? refEl[0] : refEl;
      if (el) {
        const domEl = el.$el || el;
        const midPanel = this.$refs.cfgMid;
        if (midPanel && domEl) {
          midPanel.scrollTo({ top: domEl.offsetTop - midPanel.offsetTop, behavior: 'smooth' });
        }
      }
    },
    onMidScroll() {
      const midPanel = this.$refs.cfgMid;
      if (!midPanel) return;
      const scrollTop = midPanel.scrollTop;

      for (let i = this.uniqueGroups.length - 1; i >= 0; i--) {
        const group = this.uniqueGroups[i];
        const refKey = `grp_${group}`;
        const refEl = this.$refs[refKey];
        const el = Array.isArray(refEl) ? refEl[0] : refEl;
        if (!el) continue;
        const domEl = el.$el || el;
        if (domEl.offsetTop - midPanel.offsetTop <= scrollTop + 8) {
          this.activeNavGroup = group;
          break;
        }
      }
    },
    _syncActiveNavGroup() {
      if (this.uniqueGroups.length > 0) {
        this.activeNavGroup = this.uniqueGroups[0];
      }
    },
    toReadFromLocal() {
      this.popperSaveToLocal = false;
      if (this.$refs.doReadColumnConfig) {
        this.$refs.doReadColumnConfig.getColumnConfigFromLocal();
      }
    },
    cancelChooseConfig() {
      this.popperReadFromLocal = false;
    },
    removeChooseConfig(label) {
      this.crud && this.crud.removeConfigFromLocal(label);
    },
    useReadConfig(config) {
      if (!this.crud || !config || !config.label || !this.columnList.length) {
        return;
      }
      if (!config.columns || !config.columns.length || config.columns.includes('ALL')) {
        return this.useReadConfig({
          label: config.label,
          columns: this.crud.tableColumns.map((each) => each.property),
        });
      }
      this.popperReadFromLocal = false;
      this.newConfigName = config.label;

      this.columnList.forEach((item) => {
        item.visible = config.columns.includes(item.property);
      });

      this.emitColumnConfig = config.columns
        .map((property) => this.columnList.find((col) => col.property === property))
        .filter((col) => col);
    },
    toSaveToLocal() {
      this.newConfigName = '';
      this.popperSaveToLocal = true;
      this.popperReadFromLocal = false;
      this.$nextTick(() => {
        const { inputConfigName } = this.$refs;
        if (inputConfigName && inputConfigName.focus) {
          inputConfigName.focus();
        }
      });
    },
    doSaveToLocal() {
      if (!this.crud || !this.newConfigName || !this.newConfigName.trim()) {
        this.$message.warning('请输入配置名称');
        return;
      }

      const configName = this.newConfigName.trim();
      const currentColumns = this.emitColumnConfig.map((config) => config.property);

      // rename 模式下，若名称未变，直接覆盖更新已有配置
      if (this.renamingLabel && configName === this.renamingLabel) {
        this.crud.updateConfigInLocal(this.renamingLabel, configName, currentColumns);
        this.popperSaveToLocal = false;
        this.renamingLabel = null;
        this.$message.success('配置已保存');
        return;
      }

      const existingConfig = this.crud.readCacheConfig();
      if (existingConfig && existingConfig.columnConfig) {
        const isDuplicate = existingConfig.columnConfig.some((c) => c.label === configName);
        if (isDuplicate) {
          this.$message.warning('配置名称已存在，请使用其他名称');
          return;
        }
      }

      this.crud.saveConfigToLocal(configName, currentColumns);
      this.popperSaveToLocal = false;
      this.renamingLabel = null;
      this.$message.success('配置已保存');
    },
    cancelSaveToLocal() {
      this.updateNewConfigName();
      this.popperSaveToLocal = false;
      this.renamingLabel = null;
    },
  },
};
</script>

<style lang="less" scoped>
.do-config-column-dialog {
  .drawer-wrap {
    display: flex;
    flex-direction: column;
    height: 100%;
  }

  .col-dialog-body {
    flex: 1;
    overflow: hidden;
    display: flex;
    flex-direction: column;
    gap: 12px;
    padding: 10px 0 12px;

    .cfg-search {
      padding: 0 20px;
      flex-shrink: 0;
    }

    .cfg-panels {
      display: flex;
      flex: 1;
      border: 1px solid #f1f1f1;
      border-radius: 2px;
      overflow: hidden;

      .cfg-left {
        width: 240px;
        flex-shrink: 0;
        overflow-y: auto;
        border-right: 1px solid #f1f1f1;
        background: #fafafa;
        padding: 8px 0;

        .nav-link {
          padding: 8px 16px;
          font-size: 13px;
          color: #606266;
          cursor: pointer;
          line-height: 1.4;
          transition:
            background 0.15s,
            color 0.15s;

          &:hover {
            background: #f0f2f5;
            color: #303133;
          }

          &.is-active {
            color: #409eff;
            background: #ecf5ff;
            font-weight: 500;
          }
        }
      }

      .cfg-mid {
        flex: 1;
        overflow-y: auto;
        padding: 0;

        .grp-section {
          .grp-head {
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 12px 10px 8px;
            position: sticky;
            top: 0;
            background: #fff;
            z-index: 9;

            .grp-label {
              font-size: 13px;
              font-weight: 600;
              color: #303133;
            }

            .grp-actions {
              display: flex;
              gap: 8px;

              a {
                font-size: 12px;
                color: #409eff;
                text-decoration: none;

                &:hover {
                  text-decoration: underline;
                }
              }
            }
          }

          .grp-grid {
            padding: 0 30px;
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 4px 8px;

            .grp-item {
              padding: 4px 0;

              :deep(.el-checkbox) {
                display: flex;
                align-items: center;
                width: 100%;
                margin-right: 0;

                .el-checkbox__label {
                  font-size: 13px;
                  color: #606266;
                  white-space: nowrap;
                  overflow: hidden;
                  text-overflow: ellipsis;
                }
              }
            }
          }
        }

        .grp-empty {
          padding: 48px 16px;
          text-align: center;
          color: #909399;
          font-size: 13px;
        }
      }

      .cfg-right {
        width: 280px;
        flex-shrink: 0;
        border-left: 1px solid #f1f1f1;
        display: flex;
        flex-direction: column;
        background: #fff;

        .sel-header {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 10px 12px;
          border-bottom: 1px solid #f1f1f1;
          background: #f5f7fa;
          flex-shrink: 0;

          .sel-count {
            font-size: 13px;
            color: #606266;
            font-weight: 500;
          }

          .sel-reset {
            font-size: 12px;
            color: #409eff;
            text-decoration: none;

            &:hover {
              text-decoration: underline;
            }
          }
        }

        .sel-body {
          flex: 1;
          overflow-y: auto;
          display: flex;
          flex-direction: column;

          .sel-fix-zone {
            flex-shrink: 0;

            .sel-fix-row {
              display: flex;
              align-items: center;
              padding: 0 12px;
              height: 36px;
              background: #f5f7fa;
              border-bottom: 1px solid #f0f2f5;

              .sel-lock {
                font-size: 12px;
                color: #c0c4cc;
                margin-right: 8px;
                flex-shrink: 0;
              }

              .sel-fix-name {
                font-size: 13px;
                color: #606266;
                overflow: hidden;
                text-overflow: ellipsis;
                white-space: nowrap;
              }
            }
          }

          .sel-sepline {
            display: flex;
            align-items: center;
            padding: 6px 12px;
            flex-shrink: 0;
            background: #fff;

            &::before,
            &::after {
              content: '';
              flex: 1;
              border-top: 1px dashed #dcdfe6;
            }

            .sel-septip {
              padding: 0 8px;
              font-size: 11px;
              color: #c0c4cc;
              white-space: nowrap;
            }
          }

          .sel-drag-zone {
            flex: 1;

            .sel-drag-row {
              display: flex;
              align-items: center;
              height: 36px;
              padding: 0 4px 0 8px;
              border-bottom: 1px solid #f5f7fa;
              transition: background 0.12s;

              &:hover {
                background: #f5f7fa;
              }

              .sel-drag-handle {
                display: flex;
                align-items: center;
                justify-content: center;
                width: 20px;
                height: 100%;
                cursor: grab;
                flex-shrink: 0;
                color: #c0c4cc;

                &:active {
                  cursor: grabbing;
                }

                .sel-drag-dots {
                  display: inline-block;
                  width: 6px;
                  height: 14px;
                  background-image: radial-gradient(circle, currentColor 1.2px, transparent 1.2px);
                  background-size: 3px 4px;
                  background-repeat: repeat;
                }
              }

              .sel-drag-name {
                flex: 1;
                font-size: 13px;
                color: #303133;
                overflow: hidden;
                text-overflow: ellipsis;
                white-space: nowrap;
                margin: 0 4px;
              }

              .sel-remove {
                flex-shrink: 0;
                width: 20px;
                height: 20px;
                display: flex;
                align-items: center;
                justify-content: center;
                font-size: 12px;
                color: #c0c4cc;
                cursor: pointer;
                border-radius: 3px;
                transition:
                  color 0.15s,
                  background 0.15s;

                &:hover {
                  color: #f56c6c;
                  background: #fef0f0;
                }
              }
            }

            .sel-empty {
              padding: 24px 12px;
              text-align: center;
              font-size: 13px;
              color: #c0c4cc;
            }
          }
        }
      }
    }
  }

  .drawer-foot {
    flex-shrink: 0;
    box-sizing: border-box;
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 10px 20px;
    border-top: 1px solid #f1f1f1;

    .left-btn-group {
      > span {
        margin-right: 10px;
      }

      > button {
        margin-left: 0;
        margin-right: 10px;

        &:last-child {
          margin-right: 0;
        }
      }
    }
  }

  .cfg-left,
  .cfg-mid,
  .sel-body {
    &::-webkit-scrollbar {
      width: 4px;
      height: 4px;
    }

    &::-webkit-scrollbar-thumb {
      border-radius: 5px;
      -webkit-box-shadow: inset 0 0 5px rgba(0, 0, 0, 0.2);
      background: #c1c1c1;
    }

    &::-webkit-scrollbar-track {
      -webkit-box-shadow: inset 0 0 5px rgba(0, 0, 0, 0.2);
      border-radius: 0;
      background: #f1f1f1;
    }
  }
}
</style>

<style lang="less">
.do-config-column-dialog {
  .el-drawer__body {
    padding: 0;
    overflow: hidden;
    display: flex;
    flex-direction: column;
  }
}
.save-to-local-popper {
  .save-to-local-form {
    box-sizing: border-box;
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: flex-start;

    .storage-key-will-save {
      box-sizing: border-box;
      width: 400px;
    }

    .save-to-local-confirm {
      margin-left: 10px;
      box-sizing: border-box;
    }
  }
}
</style>
