// apps/kr-admin/src/modules/_example/customColumns/_module/07HeaderSlots/HeaderSlots.tsx
import {
  useSchemaColumnConfig,
  DoConfigColumnDialog,
  schemasToColumns,
  SchemaColumnConfigContext,
  type ColumnSchema,
} from '@ku-utils/r-custom-columns';
import { Table } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { useMemo } from 'react';

import BadgeHeader from './headers/BadgeHeader';
import TrendHeader from './headers/TrendHeader';

import TableWrap from '@/components/TableWrap';
import { useAdminTableMaxHeight } from '@/composables/useAdminTableMaxHeight';
import { DEMO_CUSTOM_COLUMN_MESSAGES } from '@/modules/_example/customColumns/_utils/demoSchemas';
import {
  useCustomColumnsDemoData,
  type DemoRow,
} from '@/modules/_example/customColumns/_utils/useCustomColumnsDemoData';

export default function HeaderSlots() {
  const maxHeight = useAdminTableMaxHeight('.page-header-slots', 400);
  const { tableLoading, tableData } = useCustomColumnsDemoData();

  const columnSchemas = useMemo<ColumnSchema[]>(
    () => [
      {
        prop: 'amount',
        label: '数量',
        minWidth: 110,
        align: 'right',
        renderType: 'integer',
        headerTooltip: '投放量（headerTooltip）',
        isDefault: true,
      },
      {
        prop: 'score',
        label: '评分',
        minWidth: 120,
        align: 'right',
        renderType: 'integer',
        renderHeader: () => <TrendHeader label="评分" />,
        isDefault: true,
      },
      {
        prop: 'cost',
        label: '成本',
        minWidth: 110,
        align: 'right',
        renderType: 'float',
        isDefault: true,
      },
      {
        prop: 'roi',
        label: 'ROI',
        minWidth: 100,
        align: 'right',
        renderType: 'float',
        isDefault: true,
      },
    ],
    [],
  );

  const config = useSchemaColumnConfig({
    columnSchemas,
    storageKey: 'kr-example-header-slots',
    schemaVersion: 2,
    messages: DEMO_CUSTOM_COLUMN_MESSAGES,
  });

  const visibleWithHeaders = useMemo<ColumnSchema[]>(
    () =>
      config.visibleSchemas.map((schema) => {
        if (schema.prop === 'score') {
          return {
            ...schema,
            renderHeader: () => <TrendHeader label="评分" />,
          };
        }
        if (schema.prop === 'cost') {
          return {
            ...schema,
            renderHeader: (s) => <BadgeHeader label={s.label} />,
          };
        }
        if (schema.prop === 'roi') {
          return {
            ...schema,
            renderHeader: (s) => <TrendHeader label={s.label} />,
          };
        }
        return schema;
      }),
    [config.visibleSchemas],
  );

  const columns: ColumnsType<DemoRow> = [
    {
      title: 'ID',
      dataIndex: 'id',
      width: 60,
      fixed: 'left',
      align: 'center',
    },
    {
      title: '名称',
      dataIndex: 'name',
      minWidth: 120,
      fixed: 'left',
    },
    ...schemasToColumns<DemoRow>(visibleWithHeaders, {
      formatCell: config.formatSchemaCell,
    }),
  ];

  return (
    <SchemaColumnConfigContext.Provider value={config}>
      <div className="page-header-slots">
        <TableWrap
          enableDoHeader
          disabledColumnConfig={false}
        >
          <Table
            key={config.tableRenderKey}
            className="do-inner-scroller page-table hide-table-border"
            size="middle"
            rowKey="id"
            loading={tableLoading}
            columns={columns}
            dataSource={tableData}
            pagination={false}
            bordered
            scroll={{ x: true, y: maxHeight }}
          />
        </TableWrap>
        <DoConfigColumnDialog />
      </div>
    </SchemaColumnConfigContext.Provider>
  );
}

// apps/kv2-admin/src/modules/_example/customColumns/_module/07HeaderSlots/HeaderSlots.vue
<template>
  <div class="page-header-slots">
    <TableWrap
      enable-do-header
      :disabled-column-config="false"
    >
      <el-table
        :key="tableRenderKey"
        v-loading="tableLoading"
        class="do-inner-scroller page-table hide-table-border"
        :max-height="maxHeight"
        :data="tableData"
        border
        stripe
      >
        <el-table-column
          label="ID"
          prop="id"
          width="60"
          fixed="left"
          align="center"
        />
        <el-table-column
          label="名称"
          prop="name"
          min-width="120"
          fixed="left"
        />
        <SchemaColumn
          v-for="schema in schemaColumnList"
          :key="schema.prop"
          :schema="schema"
          :format-cell="formatSchemaCell"
        />
        <el-table-column
          v-for="schema in templateHeaderSchemas"
          :key="schema.prop"
          :prop="schema.prop"
          :label="schema.label"
          :min-width="schema.minWidth || undefined"
          :align="schema.align || 'left'"
        >
          <template #header>
            <BadgeHeader
              v-if="schema.prop === 'cost'"
              :label="schema.label"
            />
            <TrendHeader
              v-else-if="schema.prop === 'roi'"
              :label="schema.label"
            />
            <span v-else>{{ schema.label }}</span>
          </template>
          <template #default="{ row, column }">
            {{ formatSchemaCell(row[column.property], schema) }}
          </template>
        </el-table-column>
      </el-table>
    </TableWrap>
  </div>
</template>

<script>
import { SchemaColumn, useSchemaColumnConfig } from '@ku-utils/v2-custom-columns';

import BadgeHeader from './headers/BadgeHeader.vue';
import TrendHeader from './headers/TrendHeader.vue';

import { useAdminTableMaxHeight } from '@/composables/useAdminTableMaxHeight';
import { useCustomColumnsDemoData } from '@/modules/_example/customColumns/_utils/useCustomColumnsDemoData';

export default {
  name: 'HeaderSlots',
  components: { BadgeHeader, SchemaColumn, TrendHeader },
  mixins: [useSchemaColumnConfig],
  setup() {
    const { tableLoading, tableData } = useCustomColumnsDemoData();
    const maxHeight = useAdminTableMaxHeight('.page-header-slots', 400);
    return { tableLoading, tableData, maxHeight };
  },
  data() {
    return {
      schemaStorageKey: 'kv2-example-header-slots',
      schemaVersion: 2,
      columnSchemas: [
        {
          prop: 'amount',
          label: '数量',
          minWidth: 110,
          align: 'right',
          renderType: 'integer',
          headerTooltip: '投放量（headerTooltip）',
          isDefault: true,
        },
        {
          prop: 'score',
          label: '评分',
          minWidth: 120,
          align: 'right',
          renderType: 'integer',
          renderHeader: (h) => h(TrendHeader, { props: { label: '评分' } }),
          isDefault: true,
        },
        {
          prop: 'cost',
          label: '成本',
          minWidth: 110,
          align: 'right',
          renderType: 'float',
          isDefault: true,
        },
        {
          prop: 'roi',
          label: 'ROI',
          minWidth: 100,
          align: 'right',
          renderType: 'float',
          isDefault: true,
        },
      ],
      alwaysVisibleColumns: [
        { prop: 'id', label: 'ID' },
        { prop: 'name', label: '名称' },
      ],
    };
  },
  computed: {
    schemaColumnList() {
      return this.visibleSchemas.filter((s) => s.prop === 'amount' || s.prop === 'score');
    },
    templateHeaderSchemas() {
      return this.visibleSchemas.filter((s) => s.prop === 'cost' || s.prop === 'roi');
    },
  },
};
</script>
