// apps/kr-admin/src/modules/_example/clazzManage/_module/DialogEditClazzManage.tsx
import { Form, Input, Modal, Radio } from 'antd';
import { useEffect, useState } from 'react';

import maps from '@/maps';
import { requestEditClazzManage, type ClazzManageRow } from '@/modules/_example/clazzManage/_api';
import SchoolSelector from '@/modules/_example/schoolResource/_module/SchoolSelector';
import {
  toSchoolPickFromRef,
  type SchoolSelectorValue,
} from '@/modules/_example/schoolResource/_module/types';
import { message } from '@/plugins/antdApp';

type FormValues = {
  clazzName: string;
  status: number;
  schoolPick: SchoolSelectorValue | null;
};

export default function DialogEditClazzManage({
  open,
  row,
  onClose,
  onSuccess,
}: {
  open: boolean;
  row?: ClazzManageRow | null;
  onClose: () => void;
  onSuccess: () => void;
}) {
  const [form] = Form.useForm();
  const [loading, setLoading] = useState(false);
  const status = maps.example.clazzManage.clazzStatus;
  const isEdit = !!row?.id;

  useEffect(() => {
    if (!open) return;
    form.setFieldsValue({
      clazzName: row?.clazzName || '',
      status: row?.status ?? status.CLAZZ_STATUS_ENABLED,
      schoolPick:
        row?.schoolId != null
          ? toSchoolPickFromRef({ id: row.schoolId, schoolName: row.schoolName })
          : null,
    });
  }, [open, row, form, status.CLAZZ_STATUS_ENABLED]);

  async function handleOk() {
    const values = (await form.validateFields().catch(() => null)) as FormValues | null;
    if (!values) return;
    setLoading(true);
    try {
      await requestEditClazzManage({
        id: row?.id || undefined,
        clazzName: values.clazzName.trim(),
        status: values.status,
        schoolId: values.schoolPick?.id ?? null,
        schoolName: values.schoolPick?.item.schoolName || values.schoolPick?.label || '',
      });
      message.success(isEdit ? '修改成功' : '创建成功');
      onClose();
      onSuccess();
    } finally {
      setLoading(false);
    }
  }

  return (
    <Modal
      open={open}
      title={
        <span>
          {isEdit ? '修改' : '添加'}班级
          {isEdit ? <span className="dialog-tips">(ID: {row?.id})</span> : null}
        </span>
      }
      onCancel={onClose}
      onOk={handleOk}
      okText="确 定"
      cancelText="取 消"
      confirmLoading={loading}
      destroyOnHidden
      width={560}
    >
      <Form
        form={form}
        layout="horizontal"
        labelCol={{ flex: '100px' }}
        className="do-dialog-content-box"
      >
        <Form.Item
          name="clazzName"
          label="班级名称"
          rules={[{ required: true, whitespace: true, message: '请输入班级名称' }]}
        >
          <Input
            allowClear
            placeholder="请输入班级名称"
          />
        </Form.Item>
        <Form.Item
          name="status"
          label="状态"
        >
          <Radio.Group options={status.options} />
        </Form.Item>
        <Form.Item
          name="schoolPick"
          label="所属学校"
          rules={[{ required: true, message: '请选择所属学校' }]}
        >
          <SchoolSelector />
        </Form.Item>
      </Form>
    </Modal>
  );
}

// apps/kv2-admin/src/modules/_example/clazzManage/_module/DialogEditClazzManage.vue
<template>
  <div class="dialog-edit-clazz-manage-host">
    <el-dialog
      :visible.sync="dialogVisible"
      class="dialog-edit-clazz-manage"
      width="560px"
      append-to-body
      destroy-on-close
      @closed="resetEditClazzManage"
    >
      <template #title>
        <span class="el-dialog__title">
          {{ isEdit ? '修改' : '添加' }}班级
          <span
            v-if="isEdit"
            class="tips"
          >
            (ID: {{ clazzForm.id }})
          </span>
        </span>
      </template>

      <div
        v-loading="pageLoading"
        class="do-dialog-content-box"
      >
        <el-form
          ref="clazzFormRef"
          label-width="100px"
          :model="clazzForm"
          :rules="clazzRules"
        >
          <el-form-item
            label="班级名称"
            prop="clazzName"
          >
            <el-input
              v-model.trim="clazzForm.clazzName"
              clearable
              placeholder="请输入班级名称"
            />
          </el-form-item>
          <el-form-item
            label="状态"
            prop="status"
          >
            <el-radio-group v-model="clazzForm.status">
              <el-radio
                v-for="opt in $MAPS.example.clazzManage.clazzStatus.options"
                :key="opt.value"
                :label="opt.value"
              >
                {{ opt.label }}
              </el-radio>
            </el-radio-group>
          </el-form-item>
          <el-form-item
            label="所属学校"
            prop="schoolPick"
          >
            <SchoolSelector v-model="clazzForm.schoolPick" />
          </el-form-item>
        </el-form>
      </div>

      <template #footer>
        <el-button @click="dialogVisible = false">取 消</el-button>
        <el-button
          type="primary"
          :loading="submitLoading"
          @click="confirmEditClazzManage"
        >
          确 定
        </el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { Message as ElMessage } from 'element-ui';
import { computed, reactive, ref } from 'vue';

import { requestEditClazzManage } from '@/modules/_example/clazzManage/_api';
import { CLAZZ_STATUS_ENABLED } from '@/modules/_example/clazzManage/_map/clazzStatus';
import SchoolSelector from '@/modules/_example/schoolResource/_module/SchoolSelector.vue';
import type { SchoolSelectorValue } from '@/modules/_example/schoolResource/_module/types';
import type { FormInstance, FormRules } from '@/types/element-ui-form';

const emit = defineEmits<{
  success: [];
}>();

const dialogVisible = ref(false);
const pageLoading = ref(false);
const submitLoading = ref(false);
const clazzFormRef = ref<FormInstance>();

const clazzForm = reactive({
  id: '' as string | number,
  clazzName: '',
  status: CLAZZ_STATUS_ENABLED,
  schoolPick: null as SchoolSelectorValue | null,
});

const clazzRules: FormRules = {
  clazzName: [{ required: true, message: '请输入班级名称', trigger: 'blur' }],
  schoolPick: [
    {
      validator: (_rule, value, callback) => {
        if (!value) callback(new Error('请选择所属学校'));
        else callback();
      },
      trigger: 'change',
    },
  ],
};

const isEdit = computed(() => !!clazzForm.id);

function resetEditClazzManage() {
  clazzForm.id = '';
  clazzForm.clazzName = '';
  clazzForm.status = CLAZZ_STATUS_ENABLED;
  clazzForm.schoolPick = null;
  clazzFormRef.value?.clearValidate();
}

function open(row?: {
  id: number;
  clazzName: string;
  status: number;
  schoolId: string | number | null;
  schoolName: string;
}) {
  resetEditClazzManage();
  if (row) {
    clazzForm.id = row.id;
    clazzForm.clazzName = row.clazzName;
    clazzForm.status = row.status;
    if (row.schoolId != null) {
      clazzForm.schoolPick = {
        id: String(row.schoolId),
        label: row.schoolName ? `${row.schoolName}（${row.schoolId}）` : String(row.schoolId),
        item: {
          id: String(row.schoolId),
          schoolName: row.schoolName || '',
          status: 1,
          remark: '',
          createTime: '',
        },
      };
    }
  }
  dialogVisible.value = true;
  pageLoading.value = true;
  window.setTimeout(() => {
    pageLoading.value = false;
  }, 120);
}

async function confirmEditClazzManage() {
  await clazzFormRef.value?.validate();
  submitLoading.value = true;
  try {
    await requestEditClazzManage({
      id: clazzForm.id || undefined,
      clazzName: clazzForm.clazzName,
      status: clazzForm.status,
      schoolId: clazzForm.schoolPick?.id ?? null,
      schoolName: clazzForm.schoolPick?.item.schoolName || clazzForm.schoolPick?.label || '',
    });
    ElMessage.success(isEdit.value ? '修改成功' : '创建成功');
    dialogVisible.value = false;
    emit('success');
  } finally {
    submitLoading.value = false;
  }
}

defineExpose({ open });
</script>

<style lang="scss" scoped>
.dialog-edit-clazz-manage-host {
  display: contents;
}

.tips {
  margin-left: 8px;
  color: var(--ku-text-secondary, #909399);
  font-size: 13px;
  font-weight: 400;
}
</style>
