// packages/r-custom-columns/src/components/DoReadColumnConfig.tsx
import { CloseOutlined } from '@ant-design/icons';
import { Button } from 'antd';

import { useOptionalSchemaColumnConfigContext } from '../context';
import type { ColumnConfig } from '../types';
import { DEFAULT_CUSTOM_COLUMN_MESSAGES } from '../useSchemaColumnConfig';

export interface DoReadColumnConfigProps {
  /** 隐藏用户配置的删除按钮 */
  disabledDelete?: boolean;
  /** 隐藏「取消」按钮，默认 true */
  disabledCancelButton?: boolean;
  /** 显示「自定义配置」按钮 */
  showCustomConfigButton?: boolean;
  onConfirm?: (config: ColumnConfig) => void;
  onRemove?: (label: string) => void;
  /** 点击「自定义配置」，携带当前激活配置 */
  onCustom?: (config: ColumnConfig | undefined) => void;
  onClosed?: () => void;
}

/**
 * 本地配置列表：激活项高亮，其余半透明；悬停非系统配置时显示删除。
 */
export function DoReadColumnConfig(props: DoReadColumnConfigProps) {
  const {
    disabledDelete = false,
    disabledCancelButton = true,
    showCustomConfigButton = false,
    onConfirm,
    onRemove,
    onCustom,
    onClosed,
  } = props;
  const ctx = useOptionalSchemaColumnConfigContext();
  const messages = ctx?.messages ?? DEFAULT_CUSTOM_COLUMN_MESSAGES;
  const cache = ctx?.readCacheConfig();
  const configList = cache?.columnConfig ?? [];
  const currentConfigLabel = cache?.activeColumnConfigLabel ?? '';

  const chooseColumnConfig = (config: ColumnConfig) => {
    onConfirm?.(config);
    onClosed?.();
  };

  const removeConfig = (label: string) => {
    onRemove?.(label);
    onClosed?.();
  };

  return (
    <div className="do-read-column-config">
      {configList.map((item) => (
        <div
          key={item.label}
          className="read-from-local-line"
        >
          <Button
            className={['read-from-local-config', item.label === currentConfigLabel ? 'active' : '']
              .filter(Boolean)
              .join(' ')}
            size="small"
            onClick={() => chooseColumnConfig(item)}
          >
            {item.label}
          </Button>
          {!disabledDelete && ctx && !ctx.existAlreadyWithSystem(item.label) ? (
            <CloseOutlined
              className="read-from-local-delete"
              onClick={() => removeConfig(item.label)}
            />
          ) : null}
        </div>
      ))}

      {!disabledCancelButton ? (
        <div className="read-from-local-line">
          <Button
            className="read-from-local-config active"
            size="small"
            onClick={() => onClosed?.()}
          >
            {messages.cancel}
          </Button>
        </div>
      ) : null}

      {showCustomConfigButton ? (
        <div className="read-from-local-line">
          <Button
            className="read-from-local-config custom"
            size="small"
            onClick={() =>
              onCustom?.(configList.find((config) => config.label === currentConfigLabel))
            }
          >
            {messages.customConfig}
          </Button>
        </div>
      ) : null}
    </div>
  );
}

// packages/custom-columns/src/components/DoReadColumnConfig.vue
<template>
  <div class="do-read-column-config">
    <div
      v-for="(item, key) in configList"
      :key="key"
      class="read-from-local-line"
    >
      <el-button
        class="read-from-local-config"
        :class="{ active: item.label === currentConfigLabel }"
        plain
        size="small"
        @click="chooseColumnConfig(item)"
      >
        {{ item.label }}
      </el-button>
      <el-icon
        v-if="!disabledDelete && crud && !crud.existAlreadyWithSystem(item.label)"
        class="read-from-local-delete"
        @click="removeConfig(item.label)"
      >
        <Close />
      </el-icon>
    </div>

    <div
      v-if="!disabledCancelButton"
      class="read-from-local-line"
    >
      <el-button
        class="read-from-local-config active"
        plain
        size="small"
        @click="cancelChoose"
      >
        {{ messages.cancel }}
      </el-button>
    </div>
    <div
      v-if="showCustomConfigButton"
      class="read-from-local-line"
    >
      <el-button
        class="read-from-local-config custom"
        plain
        size="small"
        @click="clickCustom"
      >
        {{ messages.customConfig }}
      </el-button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { Close } from '@element-plus/icons-vue';
import { computed, inject, ref } from 'vue';

import {
  CRUD_INJECTION_KEY,
  DEFAULT_CUSTOM_COLUMN_MESSAGES,
} from '../composables/useSchemaColumnConfig';
import type { ColumnConfig, CrudContext } from '../types';

defineOptions({ name: 'DoReadColumnConfig' });

withDefaults(
  defineProps<{
    disabledDelete?: boolean;
    disabledCancelButton?: boolean;
    showCustomConfigButton?: boolean;
  }>(),
  {
    disabledDelete: false,
    disabledCancelButton: true,
    showCustomConfigButton: false,
  },
);

const emit = defineEmits<{
  confirm: [config: ColumnConfig];
  remove: [label: string];
  custom: [config: ColumnConfig | undefined];
  closed: [];
}>();

const crud = inject<CrudContext | null>(CRUD_INJECTION_KEY, null);
const messages = computed(() => crud?.messages || DEFAULT_CUSTOM_COLUMN_MESSAGES);

const currentConfigLabel = ref('');
const configList = ref<ColumnConfig[]>([]);

function getColumnConfigFromLocal(): void {
  if (!crud) return;
  const cache = crud.readCacheConfig();
  if (!cache) return;
  currentConfigLabel.value = cache.activeColumnConfigLabel || '';
  configList.value = cache.columnConfig || [];
}

function removeConfig(label: string): void {
  const idx = configList.value.findIndex((item) => item.label === label);
  if (idx < 0) return;
  configList.value.splice(idx, 1);
  emit('remove', label);
  emit('closed');
}

function chooseColumnConfig(config: ColumnConfig): void {
  currentConfigLabel.value = config.label;
  emit('confirm', config);
  emit('closed');
}

function cancelChoose(): void {
  emit('closed');
}

function clickCustom(): void {
  emit(
    'custom',
    configList.value.find((config) => config.label === currentConfigLabel.value),
  );
}

defineExpose({ getColumnConfigFromLocal });
</script>

<style scoped>
.do-read-column-config {
  box-sizing: border-box;
  width: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}

.read-from-local-line {
  margin: 10px 0 0;
  box-sizing: border-box;
  width: 100%;
  position: relative;
}

.read-from-local-delete {
  position: absolute;
  top: 50%;
  right: 10px;
  transform: translateY(-50%);
  cursor: pointer;
  display: none;
}

.read-from-local-delete:hover {
  color: #f56c6c;
}

.read-from-local-line:hover .read-from-local-delete {
  display: block;
}

.read-from-local-config {
  box-sizing: border-box;
  width: 100%;
  opacity: 0.5;
}

.read-from-local-config.active,
.read-from-local-config:hover {
  background-color: #fff;
  border-color: #409eff;
  color: #409eff;
}

.read-from-local-config.active {
  opacity: 1;
}
</style>
