// packages/r-custom-columns/src/components/SchemaColumn.tsx
import { Tooltip } from 'antd';
import type { ColumnsType, ColumnType } from 'antd/es/table';
import type { ReactNode } from 'react';

import type { ColumnSchema } from '../types';

export interface SchemaToColumnOptions {
  formatCell?: (val: unknown, schema: ColumnSchema) => string;
}

function resolveCellValue(
  value: unknown,
  schema: ColumnSchema,
  formatCell?: (val: unknown, schema: ColumnSchema) => string,
): string {
  if (formatCell) return formatCell(value, schema);
  if (value === null || value === undefined || value === '') return '-';
  return String(value);
}

/**
 * 将单个 ColumnSchema 转为 Ant Design Table ColumnType。
 * 支持嵌套 children。
 */
export function schemaToColumn<T extends Record<string, unknown> = Record<string, unknown>>(
  schema: ColumnSchema,
  options: SchemaToColumnOptions = {},
): ColumnType<T> {
  const { formatCell } = options;

  if (schema.children && schema.children.length) {
    return {
      title: schema.label,
      align: schema.align || 'center',
      children: schema.children.map((child) => schemaToColumn<T>(child, options)),
      ...schema.antdAttrs,
    } as ColumnType<T>;
  }

  const titleNode: ReactNode = schema.renderHeader ? (
    schema.renderHeader(schema)
  ) : schema.headerTooltip ? (
    <Tooltip title={schema.headerTooltip}>
      <span className="schema-col-header-tip">{schema.label}</span>
    </Tooltip>
  ) : (
    schema.label
  );

  return {
    key: schema.prop || schema.label,
    dataIndex: schema.prop,
    title: titleNode,
    width: schema.width,
    minWidth: schema.minWidth,
    align: schema.align || 'left',
    sorter: schema.sortable ? true : undefined,
    ellipsis: schema.showOverflowTooltip ? { showTitle: true } : undefined,
    render: (value: unknown, record: T, index: number) => {
      if (schema.cellRender) {
        return schema.cellRender({
          value,
          record: record as Record<string, unknown>,
          index,
          schema,
        });
      }
      return resolveCellValue(value, schema, formatCell);
    },
    ...schema.antdAttrs,
  };
}

/**
 * 将 schema 数组批量转为 Ant Design Table columns。
 */
export function schemasToColumns<T extends Record<string, unknown> = Record<string, unknown>>(
  schemas: ColumnSchema[],
  options: SchemaToColumnOptions = {},
): ColumnsType<T> {
  return (schemas || []).map((schema) => schemaToColumn<T>(schema, options));
}

// packages/custom-columns/src/components/SchemaColumn.vue
<template>
  <el-table-column
    v-if="schema.children && schema.children.length"
    :label="schema.label"
    :align="schema.align || 'center'"
  >
    <SchemaColumn
      v-for="child in schema.children"
      :key="child.prop || child.label"
      :schema="child"
      :format-cell="formatCell"
    />
  </el-table-column>

  <el-table-column
    v-else
    :prop="schema.prop"
    :label="schema.label"
    :width="schema.width || undefined"
    :min-width="schema.minWidth || undefined"
    :align="schema.align || 'left'"
    :sortable="schema.sortable || false"
    :show-overflow-tooltip="schema.showOverflowTooltip"
    :render-header="schema.renderHeader || undefined"
    v-bind="schema.elAttrs || {}"
  >
    <template
      v-if="schema.headerTooltip"
      #header
    >
      <el-tooltip
        :content="schema.headerTooltip"
        placement="top"
      >
        <span class="schema-col-header-tip">{{ schema.label }}</span>
      </el-tooltip>
    </template>
    <template #default="{ row, column, $index }">
      <component
        :is="schema.cellComponent"
        v-if="schema.cellComponent"
        :row="row"
        :column="column"
        :index="$index"
        :schema="schema"
      />
      <span v-else>{{ resolveCell(row, column) }}</span>
    </template>
  </el-table-column>
</template>

<script setup lang="ts">
import type { ColumnSchema } from '../types';

defineOptions({ name: 'SchemaColumn' });

const props = defineProps<{
  schema: ColumnSchema;
  formatCell?: (val: unknown, schema: ColumnSchema) => string;
}>();

function resolveCell(row: Record<string, unknown>, column: { property?: string }): string {
  const val = column.property ? row[column.property] : undefined;
  if (props.formatCell) return props.formatCell(val, props.schema);
  return val === null || val === undefined || val === '' ? '-' : String(val);
}
</script>

<style scoped>
.schema-col-header-tip {
  border-bottom: 1px dashed currentColor;
  cursor: help;
}
</style>
