// apps/kv2-admin/src/modules/_example/customColumns/_module/08FixedCols/FixedCols.vue
<template>
  <div class="page-fixed-cols">
    <TableWrap
      enable-do-header
      :disabled-column-config="false"
    >
      <el-table
        :key="tableRenderKey"
        v-loading="tableLoading"
        class="do-inner-scroller page-table hide-table-border"
        :max-height="maxHeight"
        :data="tableData"
        border
        stripe
      >
        <el-table-column
          label="ID"
          prop="id"
          width="70"
          fixed="left"
          align="center"
        />
        <el-table-column
          label="名称"
          prop="name"
          min-width="140"
          fixed="left"
        />
        <el-table-column
          v-for="schema in visibleSchemas"
          :key="schema.prop"
          :prop="schema.prop"
          :label="schema.label"
          :min-width="schema.minWidth || undefined"
          :align="schema.align || 'left'"
        >
          <template #default="{ row, column }">
            {{ formatSchemaCell(row[column.property], schema) }}
          </template>
        </el-table-column>
        <el-table-column
          label="操作"
          width="100"
          fixed="right"
          class-name="ops-column"
        >
          <template #default>
            <el-button
              plain
              size="small"
              type="primary"
            >
              详情
            </el-button>
          </template>
        </el-table-column>
      </el-table>
    </TableWrap>
  </div>
</template>

<script>
import { useSchemaColumnConfig } from '@ku-utils/v2-custom-columns';

import { useAdminTableMaxHeight } from '@/composables/useAdminTableMaxHeight';
import { SCHEMA_FIXED_COLUMN_SCHEMAS } from '@/modules/_example/customColumns/_utils/demoSchemas';
import { useCustomColumnsDemoData } from '@/modules/_example/customColumns/_utils/useCustomColumnsDemoData';

export default {
  name: 'FixedCols',
  mixins: [useSchemaColumnConfig],
  setup() {
    const { tableLoading, tableData } = useCustomColumnsDemoData();
    const maxHeight = useAdminTableMaxHeight('.page-fixed-cols', 400);
    return { tableLoading, tableData, maxHeight };
  },
  data() {
    return {
      schemaStorageKey: 'kv2-example-fixed-cols',
      schemaVersion: 2,
      columnSchemas: SCHEMA_FIXED_COLUMN_SCHEMAS,
      alwaysVisibleColumns: [
        { prop: 'id', label: 'ID' },
        { prop: 'name', label: '名称' },
      ],
    };
  },
};
</script>

// apps/kr-admin/src/modules/_example/customColumns/_module/08FixedCols/FixedCols.tsx
import {
  SchemaColumnConfigContext,
  schemasToColumns,
  useSchemaColumnConfig,
} from '@ku-utils/r-custom-columns';
import { Button, Table } from 'antd';
import type { ColumnsType } from 'antd/es/table';

import TableWrap from '@/components/TableWrap';
import { useAdminTableMaxHeight } from '@/composables/useAdminTableMaxHeight';
import { useFlexColumns } from '@/composables/useFlexColumns';
import {
  DEMO_CUSTOM_COLUMN_MESSAGES,
  SCHEMA_FIXED_COLUMN_SCHEMAS,
} from '@/modules/_example/customColumns/_utils/demoSchemas';
import {
  useCustomColumnsDemoData,
  type DemoRow,
} from '@/modules/_example/customColumns/_utils/useCustomColumnsDemoData';

export default function FixedCols() {
  const { tableLoading, tableData } = useCustomColumnsDemoData();
  const maxHeight = useAdminTableMaxHeight('.page-fixed-cols', 400);

  const config = useSchemaColumnConfig({
    columnSchemas: SCHEMA_FIXED_COLUMN_SCHEMAS,
    storageKey: 'kr-example-fixed-cols',
    schemaVersion: 2,
    messages: DEMO_CUSTOM_COLUMN_MESSAGES,
    alwaysVisibleColumns: [
      { prop: 'id', label: 'ID' },
      { prop: 'name', label: '名称' },
    ],
  });

  const columns: ColumnsType<DemoRow> = [
    { title: 'ID', dataIndex: 'id', width: 70, fixed: 'left', align: 'center' },
    { title: '名称', dataIndex: 'name', minWidth: 140, fixed: 'left' },
    ...schemasToColumns<DemoRow>(config.visibleSchemas, { formatCell: config.formatSchemaCell }),
    {
      title: '操作',
      key: 'ops',
      width: 100,
      fixed: 'right',
      className: 'ops-column',
      render: () => (
        <Button
          size="small"
          color="primary"
          variant="outlined"
        >
          详情
        </Button>
      ),
    },
  ];
  const flexColumns = useFlexColumns(columns, '.page-fixed-cols');

  return (
    <SchemaColumnConfigContext.Provider value={config}>
      <div className="page-fixed-cols">
        <TableWrap
          enableDoHeader
          disabledColumnConfig={false}
        >
          <Table
            key={config.tableRenderKey}
            className="do-inner-scroller page-table"
            size="middle"
            rowKey="id"
            loading={tableLoading}
            columns={flexColumns}
            dataSource={tableData}
            pagination={false}
            scroll={{ x: true, y: maxHeight }}
          />
        </TableWrap>
      </div>
    </SchemaColumnConfigContext.Provider>
  );
}
