// apps/kr-admin/src/modules/_example/clazzManage/_module/ClazzManageList.tsx
import { DeleteOutlined, EditOutlined } from '@ant-design/icons';
import { Button, Input, Radio, Table, message, Modal } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { useState } from 'react';

import DialogEditClazzManage from './DialogEditClazzManage';

import CellNameId from '@/components/CellNameId';
import CellState from '@/components/CellState';
import DoFilterPanel from '@/components/DoFilterPanel';
import ListPaginationBar from '@/components/ListPaginationBar';
import TableWrap from '@/components/TableWrap';
import { useAdminTableMaxHeight } from '@/composables/useAdminTableMaxHeight';
import { useTableQuery } from '@/composables/useTableQuery';
import maps from '@/maps';
import {
  requestDeleteClazzManage,
  requestClazzManageList,
  type ClazzManageRow,
} from '@/modules/_example/clazzManage/_api';
import {
  CLAZZ_STATUS_DISABLED,
  CLAZZ_STATUS_ENABLED,
} from '@/modules/_example/clazzManage/_map/clazzStatus';

export default function ClazzManageList() {
  const status = maps.example.clazzManage.clazzStatus;
  const [editOpen, setEditOpen] = useState(false);
  const [editRow, setEditRow] = useState<ClazzManageRow | null>(null);
  const {
    listFilters,
    setListFilters,
    tableData,
    tableTotal,
    tableLoading,
    search,
    reset,
    handlePageChange,
    handleSizeChange,
  } = useTableQuery<ClazzManageRow, { clazzName: string; status: number | '' }>({
    defaultFilters: { clazzName: '', status: '' },
    defaultPageSize: 10,
    fetcher: async (query, signal) =>
      requestClazzManageList(query, signal) as Promise<{
        data: { lists: ClazzManageRow[]; total: number };
      }>,
  });
  const maxHeight = useAdminTableMaxHeight('.page-clazz-manage', 400);

  const columns: ColumnsType<ClazzManageRow> = [
    {
      title: '班级名称',
      dataIndex: 'clazzName',
      minWidth: 160,
      className: 'name-slot-cell',
      render: (_, row) => (
        <CellNameId
          id={row.id}
          name={row.clazzName}
        />
      ),
    },
    {
      title: '所属学校',
      dataIndex: 'schoolName',
      minWidth: 160,
      ellipsis: true,
      render: (v) => v || '—',
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 100,
      align: 'center',
      render: (v) => (
        <CellState
          modelValue={v}
          activeValue={CLAZZ_STATUS_ENABLED}
          inactiveValue={CLAZZ_STATUS_DISABLED}
          activeLabel={status.getLabel(CLAZZ_STATUS_ENABLED)}
          inactiveLabel={status.getLabel(CLAZZ_STATUS_DISABLED)}
        />
      ),
    },
    {
      title: '创建时间',
      dataIndex: 'createTime',
      minWidth: 160,
      render: (v) => v || '—',
    },
    {
      title: (
        <Button
          type="primary"
          size="small"
          onClick={() => {
            setEditRow(null);
            setEditOpen(true);
          }}
        >
          新建班级
        </Button>
      ),
      key: 'ops',
      width: 140,
      fixed: 'right',
      className: 'ops-column',
      render: (_, row) => (
        <div className="line-actions">
          <Button
            type="primary"
            ghost
            size="small"
            icon={<EditOutlined />}
            title="编辑"
            aria-label="编辑"
            onClick={() => {
              setEditRow(row);
              setEditOpen(true);
            }}
          />
          <Button
            danger
            ghost
            size="small"
            icon={<DeleteOutlined />}
            title="删除"
            aria-label="删除"
            onClick={() => {
              Modal.confirm({
                title: '提示',
                content: `确认删除「${row.clazzName}」？`,
                onOk: async () => {
                  await requestDeleteClazzManage({ id: row.id });
                  message.success('删除成功');
                  void search(false);
                },
              });
            }}
          />
        </div>
      ),
    },
  ];

  return (
    <div className="page-clazz-manage">
      <DoFilterPanel
        line={1}
        loading={tableLoading}
        onSearch={() => void search(true)}
        ctl={
          <Button
            disabled={tableLoading}
            onClick={() => void reset()}
          >
            重置
          </Button>
        }
      >
        <div className="do-filter-field">
          <span className="do-filter-field-label">班级名称</span>
          <Input
            allowClear
            placeholder="不限"
            style={{ width: 180 }}
            value={listFilters.clazzName}
            onChange={(e) => setListFilters({ clazzName: e.target.value })}
            onPressEnter={() => void search(true)}
          />
        </div>
        <div className="do-filter-field">
          <span className="do-filter-field-label do-filter-field-label-sm">状态</span>
          <Radio.Group
            optionType="button"
            buttonStyle="solid"
            size="small"
            value={listFilters.status}
            onChange={(e) => {
              setListFilters({ status: e.target.value });
              void search(true);
            }}
            options={[{ label: '不限', value: '' }, ...status.options]}
          />
        </div>
      </DoFilterPanel>
      <TableWrap
        footer={
          <ListPaginationBar
            pageNum={listFilters.pageNum || 1}
            pageSize={listFilters.pageSize || 10}
            total={tableTotal}
            loading={tableLoading}
            onPageChange={(p) => void handlePageChange(p)}
            onSizeChange={(s) => void handleSizeChange(s)}
            onRefresh={() => void search(false)}
          />
        }
      >
        <Table
          className="do-inner-scroller page-table hide-table-border"
          rowKey="id"
          loading={tableLoading}
          dataSource={tableData}
          columns={columns}
          pagination={false}
          bordered
          size="middle"
          scroll={{ y: maxHeight }}
        />
      </TableWrap>
      <DialogEditClazzManage
        open={editOpen}
        row={editRow}
        onClose={() => setEditOpen(false)}
        onSuccess={() => void search(false)}
      />
    </div>
  );
}

// apps/kv3-admin/src/modules/_example/clazzManage/_module/ClazzManageList.vue
<template>
  <div class="page-clazz-manage">
    <DoFilterPanel
      :line="1"
      :loading="tableLoading"
      @search="search(true)"
    >
      <el-form
        class="with-btn"
        inline
        label-width="80px"
        @submit.prevent
      >
        <el-form-item label="班级名称">
          <el-input
            v-model="listFilters.clazzName"
            clearable
            placeholder="不限"
            @keyup.enter="search(true)"
          />
        </el-form-item>

        <el-form-item
          label="状态"
          label-width="52px"
        >
          <el-radio-group
            v-model="listFilters.status"
            size="small"
            @change="search(true)"
          >
            <el-radio-button value="">不限</el-radio-button>
            <el-radio-button
              v-for="eachStatus in $MAPS.example.clazzManage.clazzStatus.options"
              :key="eachStatus.value"
              :value="eachStatus.value"
            >
              {{ eachStatus.label }}
            </el-radio-button>
          </el-radio-group>
        </el-form-item>
      </el-form>
      <template #ctl>
        <el-button
          :disabled="tableLoading"
          @click="handleReset"
        >
          重置
        </el-button>
      </template>
    </DoFilterPanel>

    <TableWrap>
      <el-table
        v-loading="tableLoading"
        class="do-inner-scroller page-table hide-table-border"
        :data="tableData"
        :max-height="maxHeight"
        border
        stripe
      >
        <el-table-column
          label="班级名称"
          prop="clazzName"
          min-width="160"
          class-name="name-slot-cell"
          show-overflow-tooltip
        >
          <template #default="{ row }">
            <CellNameId
              :id="row.id"
              :name="row.clazzName"
            />
          </template>
        </el-table-column>
        <el-table-column
          label="所属学校"
          prop="schoolName"
          min-width="160"
          show-overflow-tooltip
        >
          <template #default="{ row }">
            <span>{{ row.schoolName || '—' }}</span>
          </template>
        </el-table-column>
        <el-table-column
          label="状态"
          prop="status"
          width="100"
          align="center"
        >
          <template #default="{ row }">
            <CellState
              :model-value="row.status"
              :active-value="CLAZZ_STATUS_ENABLED"
              :inactive-value="CLAZZ_STATUS_DISABLED"
              :active-label="$MAPS.example.clazzManage.clazzStatus.getLabel(CLAZZ_STATUS_ENABLED)"
              :inactive-label="
                $MAPS.example.clazzManage.clazzStatus.getLabel(CLAZZ_STATUS_DISABLED)
              "
            />
          </template>
        </el-table-column>
        <el-table-column
          label="创建时间"
          prop="createTime"
          min-width="160"
        >
          <template #default="{ row }">
            <CellDateTime :value="row.createTime" />
          </template>
        </el-table-column>
        <el-table-column
          width="140"
          fixed="right"
          class-name="ops-column"
        >
          <template #header>
            <el-button
              type="primary"
              size="small"
              @click="openCreate"
            >
              新建班级
            </el-button>
          </template>
          <template #default="{ row }">
            <div class="line-actions">
              <el-button
                type="primary"
                plain
                size="small"
                :icon="EditPen"
                title="编辑"
                aria-label="编辑"
                @click="openEdit(row as ClazzManageRow)"
              />
              <el-button
                type="danger"
                plain
                size="small"
                :icon="Delete"
                title="删除"
                aria-label="删除"
                @click="removeRow(row as ClazzManageRow)"
              />
            </div>
          </template>
        </el-table-column>
      </el-table>

      <template #ft>
        <BasePagination
          enable-refresh
          :refresh-loading="tableLoading"
          :page-num="listFilters.pageNum"
          :page-size="listFilters.pageSize"
          :total="tableTotal"
          :page-sizes="[10, 20, 50]"
          @page-change="handlePageChange"
          @size-change="handleSizeChange"
          @refresh="refresh()"
        />
      </template>
    </TableWrap>

    <DialogEditClazzManage
      ref="dialogEditRef"
      @success="search(false)"
    />
  </div>
</template>

<script setup lang="ts">
import { Delete, EditPen } from '@element-plus/icons-vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { ref } from 'vue';

import DialogEditClazzManage from './DialogEditClazzManage.vue';

import { useAdminTableMaxHeight } from '@/composables/useAdminTableMaxHeight';
import { useTableQuery } from '@/composables/useTableQuery';
import {
  requestClazzManageList,
  requestDeleteClazzManage,
  type ClazzManageRow,
} from '@/modules/_example/clazzManage/_api';
import {
  CLAZZ_STATUS_DISABLED,
  CLAZZ_STATUS_ENABLED,
} from '@/modules/_example/clazzManage/_map/clazzStatus';

const maxHeight = useAdminTableMaxHeight('.page-clazz-manage', 400);
const dialogEditRef = ref<InstanceType<typeof DialogEditClazzManage>>();

const {
  listFilters,
  tableData,
  tableTotal,
  tableLoading,
  search,
  refresh,
  handlePageChange,
  handleSizeChange,
  reset,
} = useTableQuery<ClazzManageRow, { clazzName: string; status: string | number }>({
  defaultFilters: {
    clazzName: '',
    status: '',
  },
  defaultPageSize: 10,
  fetcher: async (query, signal) =>
    requestClazzManageList(query, signal) as Promise<{
      data: { lists: ClazzManageRow[]; total: number };
    }>,
});

function handleReset() {
  reset();
}

function openCreate() {
  dialogEditRef.value?.open();
}

function openEdit(row: ClazzManageRow) {
  dialogEditRef.value?.open(row);
}

async function removeRow(row: ClazzManageRow) {
  await ElMessageBox.confirm(`确认删除「${row.clazzName}」？`, '提示', { type: 'warning' });
  await requestDeleteClazzManage({ id: row.id });
  ElMessage.success('删除成功');
  search(false);
}
</script>

<style lang="scss" scoped>
.page-clazz-manage {
  box-sizing: border-box;
}
</style>
