// apps/kr-admin/src/modules/_example/uiKit/_module/UiKitWordsTagDemo.tsx
import { Card } from 'antd';
import { useState } from 'react';

import DoWordsTag from '@/components/DoWordsTag';

const recommendList = ['新品', '促销', '高转化', '品牌词'];

export default function UiKitWordsTagDemo() {
  const [asideTags, setAsideTags] = useState<string[]>(['新品']);
  const [inlineTags, setInlineTags] = useState<string[]>([]);

  return (
    <div className="page-ui-kit-words-tag">
      <Card
        size="small"
        className="ui-kit-demo-card"
      >
        <h3>侧栏推荐</h3>
        <DoWordsTag
          value={asideTags}
          max={6}
          tagLength={12}
          recommends={recommendList}
          recommendLayout="aside"
          onChange={setAsideTags}
        />
        <p className="ui-kit-demo-hint">{asideTags.join(' / ') || '—'}</p>
      </Card>

      <Card
        size="small"
        className="ui-kit-demo-card"
      >
        <h3>行内推荐</h3>
        <DoWordsTag
          value={inlineTags}
          tipsMain="可从推荐词快速添加；超出长度会截断提示。"
          max={5}
          tagLength={16}
          recommends={recommendList}
          recommendLayout="inline"
          onChange={setInlineTags}
        />
        <p className="ui-kit-demo-hint">{inlineTags.join(' / ') || '—'}</p>
      </Card>
    </div>
  );
}

// apps/kv3-admin/src/modules/_example/uiKit/_module/UiKitWordsTagDemo.vue
<template>
  <div class="page-ui-kit-words-tag">
    <el-card
      shadow="never"
      class="ui-kit-demo-card"
    >
      <h3>侧栏推荐</h3>
      <DoWordsTag
        v-model="asideTags"
        :max="6"
        :tag-length="12"
        :recommends="recommendList"
        recommend-layout="aside"
      />
      <p class="ui-kit-demo-hint">{{ asideTags.join(' / ') || '—' }}</p>
    </el-card>

    <el-card
      shadow="never"
      class="ui-kit-demo-card"
    >
      <h3>行内推荐</h3>
      <DoWordsTag
        v-model="inlineTags"
        tips-main="可从推荐词快速添加；超出长度会截断提示。"
        :max="5"
        :tag-length="16"
        :recommends="recommendList"
        recommend-layout="inline"
      />
      <p class="ui-kit-demo-hint">{{ inlineTags.join(' / ') || '—' }}</p>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const recommendList = ['新品', '促销', '高转化', '品牌词'];

const asideTags = ref<string[]>(['新品']);
const inlineTags = ref<string[]>([]);
</script>

<style lang="scss" scoped>
.page-ui-kit-words-tag {
  box-sizing: border-box;
}

.ui-kit-demo-card {
  margin-top: 12px;

  h3 {
    margin: 0 0 12px;
    font-size: 14px;
    font-weight: 600;
  }
}

.ui-kit-demo-hint {
  margin: 8px 0 0;
  color: var(--ku-text-secondary, var(--el-text-color-secondary));
  font-size: 12px;
  word-break: break-all;
}
</style>
