// apps/kr-admin/src/modules/_example/uiKit/_module/UiKitCellsDemo.tsx
import { Card, Space } from 'antd';
import { useState } from 'react';

import CellDateTime from '@/components/CellDateTime';
import CellState from '@/components/CellState';
import DateRange from '@/components/DateRange';
import DoNumberSetter from '@/components/DoNumberSetter';
import { DoSelector } from '@/components/DoSelector';
import DoTxtSetter from '@/components/DoTxtSetter';
import { message } from '@/plugins/antdApp';

const sampleTime = '2026-08-06 19:43:02';
const cityOptions = [
  { value: 'bj', label: '北京' },
  { value: 'sh', label: '上海' },
  { value: 'gz', label: '广州' },
];

export default function UiKitCellsDemo() {
  const [switchValue, setSwitchValue] = useState(1);
  const [switching, setSwitching] = useState(false);
  const [dateRange, setDateRange] = useState<[string, string] | []>([]);
  const [selectorValue, setSelectorValue] = useState<string | number | null>(null);
  const [score, setScore] = useState(88);
  const [title, setTitle] = useState('可编辑标题');

  async function onSwitch(next: string | number | boolean) {
    setSwitching(true);
    try {
      await new Promise((r) => setTimeout(r, 400));
      setSwitchValue(Number(next));
      message.success('状态已切换');
    } finally {
      setSwitching(false);
    }
  }

  return (
    <div className="page-ui-kit-cells">
      <Card
        size="small"
        title="CellState"
        className="demo-card"
      >
        <div className="demo-row">
          <CellState modelValue={1} />
          <CellState modelValue={0} />
          <CellState
            modelValue={switchValue}
            switchable
            switching={switching}
            onSwitch={(v) => void onSwitch(v)}
          />
        </div>
      </Card>

      <Card
        size="small"
        title="CellDateTime"
        className="demo-card"
      >
        <div className="demo-row demo-datetime">
          <div>
            <div className="demo-label">stacked</div>
            <CellDateTime value={sampleTime} />
          </div>
          <div>
            <div className="demo-label">compact</div>
            <CellDateTime
              layout="compact"
              value={sampleTime}
            />
          </div>
          <div>
            <div className="demo-label">with-actor</div>
            <CellDateTime
              layout="with-actor"
              value={sampleTime}
              actor="zhengwenwen"
            />
          </div>
          <div>
            <div className="demo-label">dateOnly</div>
            <CellDateTime
              dateOnly
              value={sampleTime}
            />
          </div>
          <div>
            <div className="demo-label">inline</div>
            <CellDateTime
              variant="inline"
              value={sampleTime}
            />
          </div>
        </div>
      </Card>

      <Card
        size="small"
        title="DateRange / DoSelector"
        className="demo-card"
      >
        <div className="demo-row">
          <DateRange
            value={dateRange}
            onChange={(v) => setDateRange(v)}
            style={{ width: 260 }}
          />
          <DoSelector
            value={selectorValue}
            options={cityOptions}
            style={{ width: 180 }}
            onChange={(v) => setSelectorValue(Array.isArray(v) ? (v[0] ?? null) : v)}
          />
          <span className="demo-hint">
            已选：{selectorValue || '—'} / {dateRange.length === 2 ? dateRange.join(' ~ ') : '—'}
          </span>
        </div>
      </Card>

      <Card
        size="small"
        title="DoNumberSetter / DoTxtSetter"
        className="demo-card"
      >
        <Space
          className="demo-row"
          size="large"
        >
          <DoNumberSetter
            num={score}
            newValue={score}
            onOk={(v) => {
              setScore(v);
              message.success(`评分更新为 ${v}`);
            }}
          >
            评分 {score}
          </DoNumberSetter>
          <DoTxtSetter
            inline
            initValue={title}
            onOk={(v) => {
              setTitle(v);
              message.success('标题已更新');
            }}
          >
            <span>{title}</span>
          </DoTxtSetter>
        </Space>
      </Card>
    </div>
  );
}

// apps/kv3-admin/src/modules/_example/uiKit/_module/UiKitCellsDemo.vue
<template>
  <div class="page-ui-kit-cells">
    <el-card
      shadow="never"
      class="demo-card"
    >
      <template #header>CellState</template>
      <div class="demo-row">
        <CellState :model-value="1" />
        <CellState :model-value="0" />
        <CellState
          :model-value="switchValue"
          switchable
          :switching="switching"
          @switch="onSwitch"
        />
      </div>
    </el-card>

    <el-card
      shadow="never"
      class="demo-card"
    >
      <template #header>CellDateTime</template>
      <div class="demo-row demo-datetime">
        <div>
          <div class="demo-label">stacked</div>
          <CellDateTime :value="sampleTime" />
        </div>
        <div>
          <div class="demo-label">compact</div>
          <CellDateTime
            layout="compact"
            :value="sampleTime"
          />
        </div>
        <div>
          <div class="demo-label">with-actor</div>
          <CellDateTime
            layout="with-actor"
            :value="sampleTime"
            actor="zhengwenwen"
          />
        </div>
        <div>
          <div class="demo-label">dateOnly</div>
          <CellDateTime
            date-only
            :value="sampleTime"
          />
        </div>
        <div>
          <div class="demo-label">inline</div>
          <CellDateTime
            variant="inline"
            :value="sampleTime"
          />
        </div>
      </div>
    </el-card>

    <el-card
      shadow="never"
      class="demo-card"
    >
      <template #header>DateRange / DoSelector</template>
      <div class="demo-row">
        <DateRange
          v-model="dateRange"
          style="width: 260px"
        />
        <DoSelector
          v-model="selectorValue"
          style="width: 180px"
          :options="cityOptions"
        >
          <template #option="{ option }">
            <el-option
              :label="String(option.label)"
              :value="toOptionValue(option.value)"
            />
          </template>
        </DoSelector>
        <span class="demo-hint">
          已选：{{ selectorValue || '—' }} / {{ dateRange.join(' ~ ') || '—' }}
        </span>
      </div>
    </el-card>

    <el-card
      shadow="never"
      class="demo-card"
    >
      <template #header>DoNumberSetter / DoTxtSetter</template>
      <div class="demo-row">
        <DoNumberSetter
          :num="score"
          :new-value="score"
          @ok="onScoreOk"
        >
          评分 {{ score }}
        </DoNumberSetter>
        <DoTxtSetter
          inline
          :init-value="title"
          @ok="onTitleOk"
        >
          <span>{{ title }}</span>
        </DoTxtSetter>
      </div>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ElMessage } from 'element-plus';
import { ref } from 'vue';

const sampleTime = '2026-08-06 19:43:02';
const switchValue = ref(1);
const switching = ref(false);
const dateRange = ref<string[]>([]);
const selectorValue = ref('');
const score = ref(88);
const title = ref('可编辑标题');

const cityOptions = [
  { label: '北京', value: 'bj' },
  { label: '上海', value: 'sh' },
  { label: '深圳', value: 'sz' },
];

function toOptionValue(value: unknown): string | number | boolean {
  return value as string | number | boolean;
}

function onSwitch(value: string | number | boolean) {
  switching.value = true;
  window.setTimeout(() => {
    switchValue.value = Number(value);
    switching.value = false;
    ElMessage.success('状态已切换');
  }, 400);
}

function onScoreOk(value: number | undefined) {
  if (value == null) return;
  score.value = value;
  ElMessage.success(`评分更新为 ${value}`);
}

function onTitleOk(value: string | undefined) {
  title.value = value || title.value;
  ElMessage.success('标题已更新');
}
</script>

<style lang="scss" scoped>
.demo-card {
  margin-bottom: 12px;
}

.demo-row {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 16px;
}

.demo-datetime {
  align-items: flex-start;
}

.demo-label {
  margin-bottom: 6px;
  font-size: 12px;
  color: #909399;
}

.demo-hint {
  font-size: 13px;
  color: #606266;
}
</style>
