// apps/kv3-admin/src/modules/_example/uiKit/_module/UiKitNamePatternDemo.vue
<template>
  <div class="page-ui-kit-name-pattern">
    <el-card
      shadow="never"
      class="ui-kit-demo-card"
    >
      <h3>底栏芯片（默认）</h3>
      <DoNamePattern
        v-model="patternBottom"
        :pattern-list="patternList"
      />
      <p class="ui-kit-demo-hint">{{ patternBottom || '—' }}</p>
    </el-card>

    <el-card
      shadow="never"
      class="ui-kit-demo-card"
    >
      <h3>浮层插入</h3>
      <DoNamePattern
        v-model="patternPopover"
        use-popover
        :pattern-list="patternList"
        style="max-width: 420px"
      />
      <p class="ui-kit-demo-hint">{{ patternPopover || '—' }}</p>
    </el-card>

    <el-card
      shadow="never"
      class="ui-kit-demo-card"
    >
      <h3>textarea + useOnly</h3>
      <DoNamePattern
        v-model="patternTextarea"
        textarea
        use-only
        :pattern-list="patternList"
      />
      <p class="ui-kit-demo-hint">{{ patternTextarea || '—' }}</p>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const patternList = ['{应用名}', '{日期}', '{时分秒}', '{动态标号}'];
const patternBottom = ref('{应用名}-{日期}-{动态标号}');
const patternPopover = ref('');
const patternTextarea = ref('{应用名}-{日期}');
</script>

<style lang="scss" scoped>
.page-ui-kit-name-pattern {
  box-sizing: border-box;
}

.ui-kit-demo-card {
  margin-top: 12px;

  h3 {
    margin: 0 0 12px;
    font-size: 14px;
    font-weight: 600;
  }
}

.ui-kit-demo-hint {
  margin: 8px 0 0;
  color: var(--ku-text-secondary, var(--el-text-color-secondary));
  font-size: 12px;
  word-break: break-all;
}
</style>

// apps/kr-admin/src/modules/_example/uiKit/_module/UiKitNamePatternDemo.tsx
import { Card } from 'antd';
import { useState } from 'react';

import DoNamePattern from '@/components/DoNamePattern';

const patternList = ['{应用名}', '{日期}', '{时分秒}', '{动态标号}'];

export default function UiKitNamePatternDemo() {
  const [patternBottom, setPatternBottom] = useState('{应用名}-{日期}-{动态标号}');
  const [patternPopover, setPatternPopover] = useState('');
  const [patternTextarea, setPatternTextarea] = useState('{应用名}-{日期}');

  return (
    <div className="page-ui-kit-name-pattern">
      <Card
        size="small"
        className="ui-kit-demo-card"
      >
        <h3>底栏芯片（默认）</h3>
        <DoNamePattern
          value={patternBottom}
          patternList={patternList}
          onChange={setPatternBottom}
        />
        <p className="ui-kit-demo-hint">{patternBottom || '—'}</p>
      </Card>

      <Card
        size="small"
        className="ui-kit-demo-card"
      >
        <h3>浮层插入</h3>
        <DoNamePattern
          value={patternPopover}
          usePopover
          patternList={patternList}
          style={{ maxWidth: 420 }}
          onChange={setPatternPopover}
        />
        <p className="ui-kit-demo-hint">{patternPopover || '—'}</p>
      </Card>

      <Card
        size="small"
        className="ui-kit-demo-card"
      >
        <h3>textarea + useOnly</h3>
        <DoNamePattern
          value={patternTextarea}
          textarea
          useOnly
          patternList={patternList}
          onChange={setPatternTextarea}
        />
        <p className="ui-kit-demo-hint">{patternTextarea || '—'}</p>
      </Card>
    </div>
  );
}
