// apps/kv3-admin/src/modules/_example/customColumns/_module/03Slots/SlotsColumns.vue
<template>
  <div class="page-slots-columns">
    <TableWrap
      enable-do-header
      :disabled-column-config="false"
    >
      <el-table
        :key="tableRenderKey"
        v-loading="tableLoading"
        class="do-inner-scroller page-table hide-table-border"
        :max-height="maxHeight"
        :data="tableData"
        border
        stripe
      >
        <el-table-column
          label="ID"
          prop="id"
          width="60"
          fixed="left"
          align="center"
        />
        <el-table-column
          label="名称"
          prop="name"
          min-width="120"
          fixed="left"
        />
        <el-table-column
          v-for="schema in visibleSchemas"
          :key="schema.prop"
          :prop="schema.prop"
          :label="schema.label"
          :min-width="schema.minWidth || undefined"
          :align="schema.align || 'left'"
        >
          <template #default="{ row, column }">
            <span
              v-if="schema.prop === 'roi'"
              :class="row.roi >= 1.8 ? 'roi-high' : 'roi-normal'"
            >
              {{ formatSchemaCell(row[column.property], schema) }}
            </span>
            <template v-else>
              {{ formatSchemaCell(row[column.property], schema) }}
            </template>
          </template>
        </el-table-column>
      </el-table>
    </TableWrap>
  </div>
</template>

<script setup lang="ts">
import { useSchemaColumnConfig } from '@ku-utils/custom-columns';

import { useAdminTableMaxHeight } from '@/composables/useAdminTableMaxHeight';
import {
  BASIC_COLUMN_SCHEMAS,
  DEMO_CUSTOM_COLUMN_MESSAGES,
} from '@/modules/_example/customColumns/_utils/demoSchemas';
import { useCustomColumnsDemoData } from '@/modules/_example/customColumns/_utils/useCustomColumnsDemoData';

const { tableLoading, tableData } = useCustomColumnsDemoData();

const maxHeight = useAdminTableMaxHeight('.page-slots-columns', 400);

const { visibleSchemas, tableRenderKey, formatSchemaCell } = useSchemaColumnConfig({
  columnSchemas: BASIC_COLUMN_SCHEMAS,
  storageKey: 'kv3-example-slots',
  schemaVersion: 1,
  messages: DEMO_CUSTOM_COLUMN_MESSAGES,
});
</script>

<style lang="scss" scoped>
.roi-high {
  color: #67c23a;
  font-weight: 600;
}
.roi-normal {
  color: #606266;
}
</style>

// apps/kr-admin/src/modules/_example/customColumns/_module/03Slots/SlotsColumns.tsx
import {
  useSchemaColumnConfig,
  DoConfigColumnDialog,
  schemasToColumns,
  SchemaColumnConfigContext,
  type ColumnSchema,
} from '@ku-utils/r-custom-columns';
import { Table } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { useMemo } from 'react';

import TableWrap from '@/components/TableWrap';
import { useAdminTableMaxHeight } from '@/composables/useAdminTableMaxHeight';
import {
  BASIC_COLUMN_SCHEMAS,
  DEMO_CUSTOM_COLUMN_MESSAGES,
} from '@/modules/_example/customColumns/_utils/demoSchemas';
import {
  useCustomColumnsDemoData,
  type DemoRow,
} from '@/modules/_example/customColumns/_utils/useCustomColumnsDemoData';

export default function SlotsColumns() {
  const maxHeight = useAdminTableMaxHeight('.page-slots-columns', 400);
  const { tableLoading, tableData } = useCustomColumnsDemoData();

  const config = useSchemaColumnConfig({
    columnSchemas: BASIC_COLUMN_SCHEMAS,
    storageKey: 'kr-example-slots',
    schemaVersion: 1,
    messages: DEMO_CUSTOM_COLUMN_MESSAGES,
  });

  const visibleWithSlots = useMemo<ColumnSchema[]>(
    () =>
      config.visibleSchemas.map((schema) =>
        schema.prop === 'roi'
          ? {
              ...schema,
              cellRender: ({ value, record, schema: s }) => (
                <span className={Number(record.roi) >= 1.8 ? 'roi-high' : 'roi-normal'}>
                  {config.formatSchemaCell(value, s)}
                </span>
              ),
            }
          : schema,
      ),
    [config],
  );

  const columns: ColumnsType<DemoRow> = [
    {
      title: 'ID',
      dataIndex: 'id',
      width: 60,
      fixed: 'left',
      align: 'center',
    },
    {
      title: '名称',
      dataIndex: 'name',
      minWidth: 120,
      fixed: 'left',
    },
    ...schemasToColumns<DemoRow>(visibleWithSlots, {
      formatCell: config.formatSchemaCell,
    }),
  ];

  return (
    <SchemaColumnConfigContext.Provider value={config}>
      <div className="page-slots-columns">
        <TableWrap
          enableDoHeader
          disabledColumnConfig={false}
        >
          <Table
            key={config.tableRenderKey}
            className="do-inner-scroller page-table hide-table-border"
            size="middle"
            rowKey="id"
            loading={tableLoading}
            columns={columns}
            dataSource={tableData}
            pagination={false}
            bordered
            scroll={{ x: true, y: maxHeight }}
          />
        </TableWrap>
        <DoConfigColumnDialog />
      </div>
    </SchemaColumnConfigContext.Provider>
  );
}
