// apps/kv2-admin/src/modules/_example/clubActivity/_module/ClubActivityList.vue
<template>
  <div class="page-club-activity">
    <DoFilterPanel
      :line="1"
      :loading="tableLoading"
      @search="search(true)"
    >
      <el-form
        class="with-btn"
        inline
        label-width="80px"
        @submit.prevent
      >
        <el-form-item label="社团名称">
          <el-input
            v-model="listFilters.clubName"
            clearable
            placeholder="不限"
            @keyup.enter="search(true)"
          />
        </el-form-item>

        <el-form-item
          label="状态"
          label-width="52px"
        >
          <el-radio-group
            v-model="listFilters.status"
            size="small"
            @change="search(true)"
          >
            <el-radio-button label="">不限</el-radio-button>
            <el-radio-button
              v-for="eachStatus in $MAPS.example.clubActivity.clubStatus.options"
              :key="eachStatus.value"
              :label="eachStatus.value"
            >
              {{ eachStatus.label }}
            </el-radio-button>
          </el-radio-group>
        </el-form-item>
      </el-form>
      <template #ctl>
        <el-button
          :disabled="tableLoading"
          @click="handleReset"
        >
          重置
        </el-button>
      </template>
    </DoFilterPanel>

    <TableWrap enable-do-header>
      <template #batch>
        <div class="batch-control">
          <div
            class="batch-select-control"
            :class="{ 'is-active': statusOfSelect !== 'none-selected' }"
            role="checkbox"
            :aria-checked="
              statusOfSelect === 'all-selected'
                ? 'true'
                : statusOfSelect === 'half-selected'
                  ? 'mixed'
                  : 'false'
            "
            tabindex="0"
            @click="toggleBatchSelect"
            @keydown.enter.prevent="toggleBatchSelect"
            @keydown.space.prevent="toggleBatchSelect"
          >
            <div
              class="do-select-cell batch-select-box"
              :class="[statusOfSelect, { active: statusOfSelect !== 'none-selected' }]"
            >
              <el-icon v-if="statusOfSelect === 'all-selected'"><Check /></el-icon>
              <el-icon v-if="statusOfSelect === 'half-selected'"><Minus /></el-icon>
            </div>
            <span class="batch-select-label">全选本页</span>
          </div>
          <span>批量操作：</span>
          <el-button
            type="success"
            size="small"
            plain
            :disabled="!selectRows.length"
            :loading="batchEnableLoading"
            @click="toBatchSwitch(CLUB_STATUS_ENABLED)"
          >
            批量启用
          </el-button>
          <el-button
            type="warning"
            size="small"
            plain
            :disabled="!selectRows.length"
            :loading="batchDisableLoading"
            @click="toBatchSwitch(CLUB_STATUS_DISABLED)"
          >
            批量停用
          </el-button>
        </div>
      </template>

      <el-table
        v-loading="tableLoading"
        class="do-inner-scroller page-table hide-table-border"
        :data="tableData"
        :max-height="maxHeight"
        border
        stripe
      >
        <el-table-column
          fixed="left"
          width="55"
          align="center"
        >
          <template #default="{ row }">
            <div
              class="do-select-cell"
              :class="{ active: isRowSelected(row) }"
              @click.stop="chooseRow(row)"
            >
              <el-icon><Check /></el-icon>
            </div>
          </template>
        </el-table-column>
        <el-table-column
          label="社团名称"
          prop="clubName"
          min-width="140"
          class-name="name-slot-cell"
          show-overflow-tooltip
        >
          <template #default="{ row }">
            <CellNameId
              :id="row.id"
              :name="row.clubName"
            />
          </template>
        </el-table-column>
        <el-table-column
          label="参与学校"
          min-width="220"
        >
          <template #default="{ row }">
            <template v-if="row.schools?.length">
              <el-tag
                v-for="school in row.schools"
                :key="school.id"
                class="school-chip"
                size="small"
                type="info"
              >
                {{ school.schoolName }}
              </el-tag>
            </template>
            <span v-else>—</span>
          </template>
        </el-table-column>
        <el-table-column
          label="状态"
          prop="status"
          width="100"
          align="center"
        >
          <template #default="{ row }">
            <CellState
              :value="row.status"
              :active-value="CLUB_STATUS_ENABLED"
              :inactive-value="CLUB_STATUS_DISABLED"
              :active-label="$MAPS.example.clubActivity.clubStatus.getLabel(CLUB_STATUS_ENABLED)"
              :inactive-label="$MAPS.example.clubActivity.clubStatus.getLabel(CLUB_STATUS_DISABLED)"
              switchable
              :switching="isStatusSwitching(row.id)"
              active-tips="确认启用该社团？"
              inactive-tips="确认停用该社团？"
              @switch="switchClubStatus(row, $event)"
            />
          </template>
        </el-table-column>
        <el-table-column
          label="创建时间"
          prop="createTime"
          min-width="160"
        >
          <template #default="{ row }">
            <CellDateTime :value="row.createTime" />
          </template>
        </el-table-column>
        <el-table-column
          width="140"
          fixed="right"
          class-name="ops-column"
        >
          <template #header>
            <el-button
              type="primary"
              size="small"
              @click="openCreate"
            >
              新建社团
            </el-button>
          </template>
          <template #default="{ row }">
            <div class="line-actions">
              <el-button
                type="primary"
                plain
                size="small"
                icon="el-icon-edit"
                title="编辑"
                aria-label="编辑"
                @click.stop="openEdit(row)"
              />
              <el-button
                type="danger"
                plain
                size="small"
                icon="el-icon-delete"
                title="删除"
                aria-label="删除"
                @click.stop="removeRow(row)"
              />
            </div>
          </template>
        </el-table-column>
      </el-table>

      <template #ft>
        <BasePagination
          enable-refresh
          :refresh-loading="tableLoading"
          :page-num="listFilters.pageNum"
          :page-size="listFilters.pageSize"
          :total="tableTotal"
          :page-sizes="[10, 20, 50]"
          @page-change="handlePageChange"
          @size-change="handleSizeChange"
          @refresh="refresh()"
        />
      </template>
    </TableWrap>

    <DialogEditClubActivity
      ref="dialogEditRef"
      @success="search(false)"
    />
  </div>
</template>

<script setup lang="ts">
import { Message as ElMessage, MessageBox as ElMessageBox } from 'element-ui';
import { ref } from 'vue';

import DialogEditClubActivity from './DialogEditClubActivity.vue';

import { Check, Minus } from '@/components/icons/elIcons';
import { useAdminTableMaxHeight } from '@/composables/useAdminTableMaxHeight';
import { useRowSelector } from '@/composables/useRowSelector';
import { useTableQuery } from '@/composables/useTableQuery';
import {
  requestBatchSwitchClubActivity,
  requestClubActivityList,
  requestDeleteClubActivity,
  type ClubActivityRow,
} from '@/modules/_example/clubActivity/_api';
import {
  CLUB_STATUS_DISABLED,
  CLUB_STATUS_ENABLED,
} from '@/modules/_example/clubActivity/_map/clubStatus';

const maxHeight = useAdminTableMaxHeight('.page-club-activity', 400);
const dialogEditRef = ref<InstanceType<typeof DialogEditClubActivity>>();
const batchEnableLoading = ref(false);
const batchDisableLoading = ref(false);
const statusSwitchingIds = ref<Record<string, boolean>>({});

const selectionApi = {
  clearSelection: () => {},
};

const {
  listFilters,
  tableData,
  tableTotal,
  tableLoading,
  search,
  refresh,
  handlePageChange,
  handleSizeChange,
  reset,
} = useTableQuery<ClubActivityRow, { clubName: string; status: string | number }>({
  defaultFilters: {
    clubName: '',
    status: '',
  },
  defaultPageSize: 10,
  fetcher: async (query, signal) =>
    requestClubActivityList(query, signal) as Promise<{
      data: { lists: ClubActivityRow[]; total: number };
    }>,
  onLoaded() {
    selectionApi.clearSelection();
  },
});

const { selectRows, statusOfSelect, isRowSelected, chooseRow, toggleBatchSelect, clearSelection } =
  useRowSelector<ClubActivityRow>({
    tableData,
    lineKey: 'id',
    isMultiple: true,
    enableCache: false,
    enableSelector: false,
  });

selectionApi.clearSelection = clearSelection;

function handleReset() {
  reset();
}

function openCreate() {
  dialogEditRef.value?.open();
}

function openEdit(row: ClubActivityRow) {
  dialogEditRef.value?.open(row);
}

async function removeRow(row: ClubActivityRow) {
  await ElMessageBox.confirm(`确认删除「${row.clubName}」？`, '提示', { type: 'warning' });
  await requestDeleteClubActivity({ id: row.id });
  ElMessage.success('删除成功');
  search(false);
}

async function toBatchSwitch(status: number) {
  const ids = selectRows.value.map((row) => row.id);
  if (!ids.length) return;
  const actionLabel = status === CLUB_STATUS_ENABLED ? '启用' : '停用';
  await ElMessageBox.confirm(`确定${actionLabel}所选的 ${ids.length} 个社团？`, '提示', {
    type: 'warning',
  });
  const loadingRef = status === CLUB_STATUS_ENABLED ? batchEnableLoading : batchDisableLoading;
  loadingRef.value = true;
  try {
    await requestBatchSwitchClubActivity(ids, status);
    ElMessage.success(`${actionLabel}成功`);
    clearSelection();
    search(false);
  } finally {
    loadingRef.value = false;
  }
}

function isStatusSwitching(id: string | number) {
  return !!statusSwitchingIds.value[String(id)];
}

async function switchClubStatus(row: ClubActivityRow, nextStatus: string | number | boolean) {
  const key = String(row.id);
  statusSwitchingIds.value = { ...statusSwitchingIds.value, [key]: true };
  try {
    await requestBatchSwitchClubActivity([row.id], Number(nextStatus));
    row.status = Number(nextStatus);
    ElMessage.success(nextStatus === CLUB_STATUS_ENABLED ? '已启用' : '已停用');
  } finally {
    const nextMap = { ...statusSwitchingIds.value };
    delete nextMap[key];
    statusSwitchingIds.value = nextMap;
  }
}
</script>

<style lang="scss" scoped>
.page-club-activity {
  box-sizing: border-box;
}

.batch-control {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 13px;
  color: var(--ku-text-secondary, #909399);
}

.school-chip {
  margin: 0 4px 4px 0;
}
</style>

// apps/kr-admin/src/modules/_example/clubActivity/_module/ClubActivityList.tsx
import { DeleteOutlined, EditOutlined } from '@ant-design/icons';
import { Button, Input, Radio, Table, Tag } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { useRef, useState } from 'react';

import DialogEditClubActivity from './DialogEditClubActivity';

import CellDateTime from '@/components/CellDateTime';
import CellNameId from '@/components/CellNameId';
import CellState from '@/components/CellState';
import DoFilterPanel from '@/components/DoFilterPanel';
import { DoSelectBatchBox, createSelectColumn } from '@/components/DoSelectCell';
import ListPaginationBar from '@/components/ListPaginationBar';
import TableWrap from '@/components/TableWrap';
import { useAdminTableMaxHeight } from '@/composables/useAdminTableMaxHeight';
import { useRowSelector } from '@/composables/useRowSelector';
import { useTableQuery } from '@/composables/useTableQuery';
import maps from '@/maps';
import {
  requestBatchSwitchClubActivity,
  requestDeleteClubActivity,
  requestClubActivityList,
  type ClubActivityRow,
} from '@/modules/_example/clubActivity/_api';
import {
  CLUB_STATUS_DISABLED,
  CLUB_STATUS_ENABLED,
} from '@/modules/_example/clubActivity/_map/clubStatus';
import { message, modal } from '@/plugins/antdApp';

export default function ClubActivityList() {
  const status = maps.example.clubActivity.clubStatus;
  const [editOpen, setEditOpen] = useState(false);
  const [editRow, setEditRow] = useState<ClubActivityRow | null>(null);
  const [batchEnableLoading, setBatchEnableLoading] = useState(false);
  const [batchDisableLoading, setBatchDisableLoading] = useState(false);
  const [statusSwitchingIds, setStatusSwitchingIds] = useState<Record<string, boolean>>({});
  const clearSelectionRef = useRef<() => void>(() => {});

  const {
    listFilters,
    setListFilters,
    tableData,
    tableTotal,
    tableLoading,
    search,
    reset,
    patchRow,
    handlePageChange,
    handleSizeChange,
  } = useTableQuery<ClubActivityRow, { clubName: string; status: number | '' }>({
    defaultFilters: { clubName: '', status: '' },
    defaultPageSize: 10,
    fetcher: async (query, signal) =>
      requestClubActivityList(query, signal) as Promise<{
        data: { lists: ClubActivityRow[]; total: number };
      }>,
    onLoaded: () => clearSelectionRef.current(),
  });
  const selector = useRowSelector<ClubActivityRow>({ tableData, lineKey: 'id', isMultiple: true });
  const { selectRows, statusOfSelect, toggleBatchSelect, clearSelection } = selector;
  clearSelectionRef.current = clearSelection;
  const maxHeight = useAdminTableMaxHeight('.page-club-activity', 400);

  async function toBatchSwitch(nextStatus: number) {
    const ids = selectRows.map((row) => row.id);
    if (!ids.length) return;
    const actionLabel = nextStatus === CLUB_STATUS_ENABLED ? '启用' : '停用';
    modal.confirm({
      title: '提示',
      content: `确定${actionLabel}所选的 ${ids.length} 个社团？`,
      onOk: async () => {
        const setLoading =
          nextStatus === CLUB_STATUS_ENABLED ? setBatchEnableLoading : setBatchDisableLoading;
        setLoading(true);
        try {
          await requestBatchSwitchClubActivity(ids, nextStatus);
          message.success(`${actionLabel}成功`);
          clearSelection();
          void search(false);
        } finally {
          setLoading(false);
        }
      },
    });
  }

  async function switchClubStatus(row: ClubActivityRow, nextStatus: string | number | boolean) {
    const key = String(row.id);
    setStatusSwitchingIds((prev) => ({ ...prev, [key]: true }));
    try {
      await requestBatchSwitchClubActivity([row.id], Number(nextStatus));
      patchRow((item) => item.id === row.id, { status: Number(nextStatus) });
      message.success(Number(nextStatus) === CLUB_STATUS_ENABLED ? '已启用' : '已停用');
    } finally {
      setStatusSwitchingIds((prev) => {
        const next = { ...prev };
        delete next[key];
        return next;
      });
    }
  }

  const columns: ColumnsType<ClubActivityRow> = [
    createSelectColumn(selector, { batchHeader: false }),
    {
      title: '社团名称',
      dataIndex: 'clubName',
      minWidth: 140,
      className: 'name-slot-cell',
      render: (_, row) => (
        <CellNameId
          id={row.id}
          name={row.clubName}
        />
      ),
    },
    {
      title: '参与学校',
      dataIndex: 'schools',
      minWidth: 220,
      render: (schools: ClubActivityRow['schools']) =>
        schools?.length
          ? schools.map((s) => (
              <Tag
                key={s.id}
                className="school-chip"
              >
                {s.schoolName}
              </Tag>
            ))
          : '—',
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 100,
      align: 'center',
      render: (_, row) => (
        <CellState
          modelValue={row.status}
          activeValue={CLUB_STATUS_ENABLED}
          inactiveValue={CLUB_STATUS_DISABLED}
          activeLabel={status.getLabel(CLUB_STATUS_ENABLED)}
          inactiveLabel={status.getLabel(CLUB_STATUS_DISABLED)}
          switchable
          switching={!!statusSwitchingIds[String(row.id)]}
          activeTips="确认启用该社团？"
          inactiveTips="确认停用该社团？"
          onSwitch={(next) => void switchClubStatus(row, next)}
        />
      ),
    },
    {
      title: '创建时间',
      dataIndex: 'createTime',
      minWidth: 160,
      render: (v) => <CellDateTime value={v} />,
    },
    {
      title: (
        <Button
          type="primary"
          size="small"
          onClick={() => {
            setEditRow(null);
            setEditOpen(true);
          }}
        >
          新建社团
        </Button>
      ),
      key: 'ops',
      width: 140,
      fixed: 'right',
      className: 'ops-column',
      render: (_, row) => (
        <div className="line-actions">
          <Button
            type="primary"
            ghost
            size="small"
            icon={<EditOutlined />}
            title="编辑"
            aria-label="编辑"
            onClick={(e) => {
              e.stopPropagation();
              setEditRow(row);
              setEditOpen(true);
            }}
          />
          <Button
            danger
            ghost
            size="small"
            icon={<DeleteOutlined />}
            title="删除"
            aria-label="删除"
            onClick={(e) => {
              e.stopPropagation();
              modal.confirm({
                title: '提示',
                content: `确认删除「${row.clubName}」？`,
                onOk: async () => {
                  await requestDeleteClubActivity({ id: row.id });
                  message.success('删除成功');
                  void search(false);
                },
              });
            }}
          />
        </div>
      ),
    },
  ];

  return (
    <div className="page-club-activity">
      <DoFilterPanel
        line={1}
        loading={tableLoading}
        onSearch={() => void search(true)}
        ctl={
          <Button
            disabled={tableLoading}
            onClick={() => void reset()}
          >
            重置
          </Button>
        }
      >
        <div className="do-filter-field">
          <span className="do-filter-field-label">社团名称</span>
          <Input
            allowClear
            placeholder="不限"
            style={{ width: 180 }}
            value={listFilters.clubName}
            onChange={(e) => setListFilters({ clubName: e.target.value })}
            onPressEnter={() => void search(true)}
          />
        </div>
        <div className="do-filter-field">
          <span className="do-filter-field-label do-filter-field-label-sm">状态</span>
          <Radio.Group
            optionType="button"
            buttonStyle="solid"
            size="small"
            value={listFilters.status}
            onChange={(e) => {
              setListFilters({ status: e.target.value });
              void search(true);
            }}
            options={[{ label: '不限', value: '' }, ...status.options]}
          />
        </div>
      </DoFilterPanel>
      <TableWrap
        enableDoHeader
        batch={
          <div className="batch-control">
            <div
              className={[
                'batch-select-control',
                statusOfSelect !== 'none-selected' ? 'is-active' : '',
              ]
                .filter(Boolean)
                .join(' ')}
              role="checkbox"
              aria-checked={
                statusOfSelect === 'all-selected'
                  ? 'true'
                  : statusOfSelect === 'half-selected'
                    ? 'mixed'
                    : 'false'
              }
              tabIndex={0}
              onClick={toggleBatchSelect}
              onKeyDown={(e) => {
                if (e.key === 'Enter' || e.key === ' ') {
                  e.preventDefault();
                  toggleBatchSelect();
                }
              }}
            >
              <DoSelectBatchBox status={statusOfSelect} />
              <span className="batch-select-label">全选本页</span>
            </div>
            <span>批量操作：</span>
            <Button
              className="ml-5"
              color="green"
              variant="outlined"
              size="small"
              disabled={!selectRows.length}
              loading={batchEnableLoading}
              onClick={() => void toBatchSwitch(CLUB_STATUS_ENABLED)}
            >
              批量启用
            </Button>
            <Button
              className="ml-5"
              color="orange"
              variant="outlined"
              size="small"
              disabled={!selectRows.length}
              loading={batchDisableLoading}
              onClick={() => void toBatchSwitch(CLUB_STATUS_DISABLED)}
            >
              批量停用
            </Button>
          </div>
        }
        footer={
          <ListPaginationBar
            pageNum={listFilters.pageNum || 1}
            pageSize={listFilters.pageSize || 10}
            total={tableTotal}
            loading={tableLoading}
            onPageChange={(p) => void handlePageChange(p)}
            onSizeChange={(s) => void handleSizeChange(s)}
            onRefresh={() => void search(false)}
          />
        }
      >
        <Table
          className="do-inner-scroller page-table hide-table-border"
          rowKey="id"
          loading={tableLoading}
          dataSource={tableData}
          columns={columns}
          pagination={false}
          bordered
          size="middle"
          scroll={{ y: maxHeight }}
        />
      </TableWrap>
      <DialogEditClubActivity
        open={editOpen}
        row={editRow}
        onClose={() => setEditOpen(false)}
        onSuccess={() => void search(false)}
      />
    </div>
  );
}
