// packages/custom-columns/src/components/DoConfigColumnDialog.vue
<template>
  <el-drawer
    v-model="visible"
    class="do-config-column-dialog"
    :append-to-body="true"
    size="1000px"
    direction="rtl"
    :before-close="handleBeforeClose"
  >
    <template #header>
      <span class="drawer-title">
        {{ messages.customColumns }}
        <span
          class="tips"
          :class="newConfigName === noNameLabel ? 'status-warning' : 'status-success'"
        >
          ({{ newConfigName }})
        </span>
      </span>
    </template>

    <div class="drawer-wrap">
      <div class="col-dialog-body">
        <div class="cfg-search">
          <el-input
            v-model="searchKeyword"
            :placeholder="messages.searchPlaceholder"
            clearable
            size="small"
            :prefix-icon="Search"
          />
        </div>

        <div class="cfg-panels">
          <div class="cfg-left">
            <div
              v-for="group in uniqueGroups"
              :key="group"
              class="nav-link"
              :class="{ active: activeNavGroup === group }"
              @click="scrollToGroup(group)"
            >
              {{ group }}
            </div>
          </div>

          <div
            ref="midPanel"
            class="cfg-mid"
            @scroll="onMidScroll"
          >
            <div
              v-for="group in filteredGroups"
              :key="group.label"
              :ref="(el) => setGroupRef(group.label, el)"
              class="grp-section"
            >
              <div class="grp-head">
                <span class="grp-label">{{ group.label }}</span>
                <span class="grp-actions">
                  <a
                    href="javascript:"
                    @click="groupAllSelect(group.label)"
                  >
                    {{ messages.selectAll }}
                  </a>
                  <a
                    href="javascript:"
                    @click="groupReverseSelect(group.label)"
                  >
                    {{ messages.invertSelection }}
                  </a>
                </span>
              </div>
              <div class="grp-grid">
                <div
                  v-for="col in group.children"
                  :key="col.property"
                  class="grp-item"
                >
                  <el-checkbox
                    v-model="col.visible"
                    :disabled="unableToControl(col)"
                    @change="(checked: boolean) => toggleColumnCheck(checked, col)"
                  >
                    {{ col.label }}
                  </el-checkbox>
                </div>
              </div>
            </div>
            <div
              v-if="filteredGroups.length === 0"
              class="grp-empty"
            >
              {{ messages.emptySearch }}
            </div>
          </div>

          <div class="cfg-right">
            <div class="sel-header">
              <span class="sel-count">{{ messages.selectedCount(selectedCount, maxCount) }}</span>
              <a
                class="sel-reset"
                href="javascript:"
                @click="resetConfig"
              >
                {{ messages.reset }}
              </a>
            </div>

            <div class="sel-body">
              <template v-if="fixedSelectedCols.length">
                <div class="sel-fix-zone">
                  <div
                    v-for="col in fixedSelectedCols"
                    :key="col.property"
                    class="sel-fix-row"
                  >
                    <el-icon class="sel-lock"><Lock /></el-icon>
                    <span class="sel-fix-name">{{ col.label }}</span>
                  </div>
                </div>
                <div class="sel-sepline">
                  <span class="sel-septip">{{ messages.fixedColumnsTip }}</span>
                </div>
              </template>

              <div class="sel-drag-zone">
                <VueDraggable
                  v-model="draggableModel"
                  :animation="200"
                  handle=".sel-drag-handle"
                  @update="onDragReorder"
                >
                  <div
                    v-for="col in draggableModel"
                    :key="col.property"
                    class="sel-drag-row"
                  >
                    <span class="sel-drag-handle">
                      <span class="sel-drag-dots" />
                    </span>
                    <span
                      class="sel-drag-name"
                      :title="col.label"
                    >
                      {{ col.label }}
                    </span>
                    <el-icon
                      class="sel-remove"
                      @click="removeSelectedItem(col.property)"
                    >
                      <Close />
                    </el-icon>
                  </div>
                </VueDraggable>
                <div
                  v-if="draggableModel.length === 0"
                  class="sel-empty"
                >
                  {{ messages.emptySelected }}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="drawer-foot">
        <div class="left-btn-group">
          <el-popover
            v-model:visible="popperSaveToLocal"
            placement="top"
            popper-class="save-to-local-popper"
            trigger="manual"
            :width="520"
          >
            <template #default>
              <div class="save-to-local-form">
                <el-input
                  ref="inputConfigName"
                  v-model="newConfigName"
                  class="storage-key-will-save"
                  :placeholder="messages.configNamePlaceholder"
                />
                <el-button
                  plain
                  size="small"
                  @click="cancelSaveToLocal"
                >
                  {{ messages.cancel }}
                </el-button>
                <el-button
                  plain
                  size="small"
                  @click="doSaveToLocal"
                >
                  {{ messages.save }}
                </el-button>
              </div>
            </template>
            <template #reference>
              <el-button @click="toSaveToLocal">{{ messages.saveToLocal }}</el-button>
            </template>
          </el-popover>

          <el-popover
            v-model:visible="popperReadFromLocal"
            placement="top"
            popper-class="read-from-local-popper"
            trigger="click"
            :width="240"
          >
            <template #default>
              <DoReadColumnConfig
                ref="readConfigRef"
                @confirm="useReadConfig"
                @remove="removeChooseConfig"
                @closed="popperReadFromLocal = false"
              />
            </template>
            <template #reference>
              <el-button @click="toReadFromLocal">{{ messages.readFromLocal }}</el-button>
            </template>
          </el-popover>
        </div>

        <div class="right-btn-group">
          <el-button @click="cancelColumnConfig">{{ messages.cancel }}</el-button>
          <el-button
            type="primary"
            @click="confirmColumnConfig"
          >
            {{ messages.complete }}
          </el-button>
        </div>
      </div>
    </div>
  </el-drawer>
</template>

<script setup lang="ts">
import { Close, Lock, Search } from '@element-plus/icons-vue';
import { ElMessage } from 'element-plus';
import { computed, inject, nextTick, ref } from 'vue';
import { VueDraggable } from 'vue-draggable-plus';

import {
  CRUD_INJECTION_KEY,
  DEFAULT_CUSTOM_COLUMN_MESSAGES,
} from '../composables/useSchemaColumnConfig';
import type { ColumnConfig, CrudContext, TableColumnMeta } from '../types';

import DoReadColumnConfig from './DoReadColumnConfig.vue';

defineOptions({ name: 'DoConfigColumnDialog' });

const emit = defineEmits<{ confirm: [config: ColumnConfig] }>();

const crud = inject<CrudContext | null>(CRUD_INJECTION_KEY, null);

const visible = ref(false);
const popperSaveToLocal = ref(false);
const popperReadFromLocal = ref(false);
const columnList = ref<TableColumnMeta[]>([]);
const emitColumnConfig = ref<TableColumnMeta[]>([]);
const messages = computed(() => crud?.messages || DEFAULT_CUSTOM_COLUMN_MESSAGES);
const newConfigName = ref(crud?.noNameLabel || messages.value?.noNameLabel || '');
const searchKeyword = ref('');
const activeNavGroup = ref('');

const midPanel = ref<HTMLElement | null>(null);
const readConfigRef = ref<InstanceType<typeof DoReadColumnConfig> | null>(null);
const inputConfigName = ref<{ focus: () => void } | null>(null);
const groupRefs = new Map<string, HTMLElement>();

function setGroupRef(label: string, el: unknown): void {
  if (el) groupRefs.set(label, (el as { $el?: HTMLElement }).$el || (el as HTMLElement));
  else groupRefs.delete(label);
}

const noNameLabel = computed(() => crud?.noNameLabel || messages.value?.noNameLabel || '');
const maxCount = computed(() => crud?.maxSelectCount || 50);
const selectedCount = computed(() => emitColumnConfig.value.length);

const uniqueGroups = computed(() => {
  const seen = new Set<string>();
  const groups: string[] = [];
  columnList.value.forEach((item) => {
    const g = item.group || messages.value.groupFallback;
    if (!seen.has(g)) {
      seen.add(g);
      groups.push(g);
    }
  });
  return groups;
});

const filteredGroups = computed(() => {
  const keyword = searchKeyword.value.trim().toLowerCase();
  const groupMap = new Map<string, { label: string; children: TableColumnMeta[] }>();
  columnList.value.forEach((item) => {
    const g = item.group || messages.value.groupFallback;
    if (keyword && !item.label.toLowerCase().includes(keyword)) return;
    if (!groupMap.has(g)) groupMap.set(g, { label: g, children: [] });
    groupMap.get(g)!.children.push(item);
  });
  return uniqueGroups.value.filter((g) => groupMap.has(g)).map((g) => groupMap.get(g)!);
});

const alwaysCols = computed<TableColumnMeta[]>(() => {
  const manual = crud?.alwaysVisibleColumns || [];
  return manual.map((col) => ({
    property: col.prop,
    label: col.label,
    fixed: true,
    group: messages.value.groupFallback,
    isLeaf: true,
    visible: true,
    _alwaysVisible: true,
  }));
});

const fixedSelectedCols = computed(() => {
  const schemaFixed = emitColumnConfig.value.filter((col) => unableToControl(col));
  return [...alwaysCols.value, ...schemaFixed];
});

const draggableModel = computed<TableColumnMeta[]>({
  get: () => emitColumnConfig.value.filter((col) => !unableToControl(col)),
  set: () => {
    /* 实际重排由 onDragReorder 处理 */
  },
});

function unableToControl(col: TableColumnMeta): boolean {
  return (
    col.type === 'selection' ||
    col.fixed ||
    col.label === messages.value.operationColumnLabel ||
    col.label === '操作'
  );
}

function applyConfig(columnConfig: ColumnConfig): void {
  if (!crud) return;
  newConfigName.value = columnConfig.label;
  const allColumns = crud.tableColumns.map((item) => ({
    ...item,
    visible: columnConfig.columns.includes(item.property as string),
  }));
  columnList.value = allColumns;
  emitColumnConfig.value = columnConfig.columns
    .map((property) => allColumns.find((col) => col.property === property))
    .filter((col): col is TableColumnMeta => !!col);
}

function showConfigColumnDialog(currentConfig?: ColumnConfig): void {
  if (!crud) return;
  const columnConfig = currentConfig || crud.getDefaultConfig();
  if (!columnConfig) return;
  applyConfig(columnConfig);
  searchKeyword.value = '';
  visible.value = true;
  nextTick(() => {
    if (uniqueGroups.value.length > 0) activeNavGroup.value = uniqueGroups.value[0];
  });
}

function handleBeforeClose(done: () => void): void {
  popperSaveToLocal.value = false;
  popperReadFromLocal.value = false;
  done();
  nextTick(() => crud?.onDialogClose?.());
}

function cancelColumnConfig(): void {
  popperSaveToLocal.value = false;
  popperReadFromLocal.value = false;
  visible.value = false;
  nextTick(() => crud?.onDialogClose?.());
}

function confirmColumnConfig(): void {
  popperSaveToLocal.value = false;
  popperReadFromLocal.value = false;
  visible.value = false;
  emit('confirm', {
    label: newConfigName.value || noNameLabel.value,
    columns: emitColumnConfig.value
      .filter((config) => !config._alwaysVisible)
      .map((config) => config.property as string),
  });
}

function resetConfig(): void {
  if (!crud) return;
  const defaultConfig = crud.getDefaultConfig();
  if (!defaultConfig) return;
  applyConfig(defaultConfig);
  updateNewConfigName();
}

function updateEmitColumnConfig(): void {
  const currentProps = emitColumnConfig.value.map((col) => col.property);
  const newVisibleProps = columnList.value.filter((col) => col.visible).map((col) => col.property);
  emitColumnConfig.value = emitColumnConfig.value.filter((col) =>
    newVisibleProps.includes(col.property),
  );
  newVisibleProps.forEach((property) => {
    if (!currentProps.includes(property)) {
      const col = columnList.value.find((c) => c.property === property);
      if (col) emitColumnConfig.value.push(col);
    }
  });
  updateNewConfigName();
}

function updateNewConfigName(): void {
  if (!crud) return;
  const cache = crud.readCacheConfig();
  if (!cache) return;
  const tempConfig = emitColumnConfig.value.map((item) => item.property);
  let found = false;
  cache.columnConfig.forEach((config) => {
    if (JSON.stringify(config.columns) === JSON.stringify(tempConfig)) {
      found = true;
      newConfigName.value = config.label;
    }
  });
  if (!found) newConfigName.value = noNameLabel.value;
}

function toggleColumnCheck(checked: boolean, col: TableColumnMeta): void {
  if (checked && !unableToControl(col)) {
    const willCount = emitColumnConfig.value.filter((c) => !unableToControl(c)).length + 1;
    if (willCount > maxCount.value) {
      ElMessage.warning(messages.value.maxSelectedWarning(maxCount.value));
      nextTick(() => {
        col.visible = false;
      });
      return;
    }
  }
  updateEmitColumnConfig();
}

function groupAllSelect(group: string): void {
  columnList.value.forEach((item) => {
    if (!unableToControl(item) && (item.group || messages.value.groupFallback) === group) {
      item.visible = true;
    }
  });
  updateEmitColumnConfig();
}

function groupReverseSelect(group: string): void {
  columnList.value.forEach((item) => {
    if (!unableToControl(item) && (item.group || messages.value.groupFallback) === group) {
      item.visible = !item.visible;
    }
  });
  updateEmitColumnConfig();
}

function removeSelectedItem(property?: string): void {
  const col = columnList.value.find((c) => c.property === property);
  if (col) col.visible = false;
  emitColumnConfig.value = emitColumnConfig.value.filter((c) => c.property !== property);
  updateNewConfigName();
}

function onDragReorder(): void {
  const reordered = draggableModel.value;
  const schemaFixed = emitColumnConfig.value.filter(
    (col) => unableToControl(col) && !col._alwaysVisible,
  );
  emitColumnConfig.value = [...schemaFixed, ...reordered];
  updateNewConfigName();
}

function scrollToGroup(group: string): void {
  activeNavGroup.value = group;
  const domEl = groupRefs.get(group);
  const panel = midPanel.value;
  if (domEl && panel) {
    panel.scrollTo({ top: domEl.offsetTop - panel.offsetTop, behavior: 'smooth' });
  }
}

function onMidScroll(): void {
  const panel = midPanel.value;
  if (!panel) return;
  const scrollTop = panel.scrollTop;
  for (let i = uniqueGroups.value.length - 1; i >= 0; i--) {
    const domEl = groupRefs.get(uniqueGroups.value[i]);
    if (!domEl) continue;
    if (domEl.offsetTop - panel.offsetTop <= scrollTop + 8) {
      activeNavGroup.value = uniqueGroups.value[i];
      break;
    }
  }
}

function toReadFromLocal(): void {
  popperSaveToLocal.value = false;
  nextTick(() => readConfigRef.value?.getColumnConfigFromLocal());
}

function removeChooseConfig(label: string): void {
  crud?.removeConfigFromLocal(label);
}

function useReadConfig(config: ColumnConfig): void {
  if (!crud || !config || !config.label || !columnList.value.length) return;
  if (!config.columns || !config.columns.length || config.columns.includes('ALL')) {
    useReadConfig({
      label: config.label,
      columns: crud.tableColumns.map((each) => each.property as string),
    });
    return;
  }
  popperReadFromLocal.value = false;
  newConfigName.value = config.label;
  columnList.value.forEach((item) => {
    item.visible = config.columns.includes(item.property as string);
  });
  emitColumnConfig.value = config.columns
    .map((property) => columnList.value.find((col) => col.property === property))
    .filter((col): col is TableColumnMeta => !!col);
}

function toSaveToLocal(): void {
  newConfigName.value = '';
  popperSaveToLocal.value = true;
  popperReadFromLocal.value = false;
  nextTick(() => inputConfigName.value?.focus?.());
}

function doSaveToLocal(): void {
  if (!crud || !newConfigName.value || !newConfigName.value.trim()) {
    ElMessage.warning(messages.value.configNameRequired);
    return;
  }
  const configName = newConfigName.value.trim();
  const existingConfig = crud.readCacheConfig();
  if (existingConfig?.columnConfig?.some((c) => c.label === configName)) {
    ElMessage.warning(messages.value.configNameExists);
    return;
  }
  crud.saveConfigToLocal(
    configName,
    emitColumnConfig.value.map((config) => config.property as string),
  );
  popperSaveToLocal.value = false;
  ElMessage.success(messages.value.configSaved);
}

function cancelSaveToLocal(): void {
  updateNewConfigName();
  popperSaveToLocal.value = false;
}

defineExpose({ showConfigColumnDialog });
</script>

<style scoped>
.drawer-wrap {
  display: flex;
  flex-direction: column;
  height: 100%;
}

.col-dialog-body {
  flex: 1;
  overflow: hidden;
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 10px 0 12px;
}

.cfg-search {
  padding: 0 20px;
  flex-shrink: 0;
}

.cfg-panels {
  display: flex;
  flex: 1;
  border: 1px solid #f1f1f1;
  border-radius: 2px;
  overflow: hidden;
}

.cfg-left {
  width: 240px;
  flex-shrink: 0;
  overflow-y: auto;
  border-right: 1px solid #f1f1f1;
  background: #fafafa;
  padding: 8px 0;
}

.nav-link {
  padding: 8px 16px;
  font-size: 13px;
  color: #606266;
  cursor: pointer;
  line-height: 1.4;
  transition:
    background 0.15s,
    color 0.15s;
}

.nav-link:hover {
  background: #f0f2f5;
  color: #303133;
}

.nav-link.active {
  color: #409eff;
  background: #ecf5ff;
  font-weight: 500;
}

.cfg-mid {
  flex: 1;
  overflow-y: auto;
}

.grp-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 10px 8px;
  position: sticky;
  top: 0;
  background: #fff;
  z-index: 9;
}

.grp-label {
  font-size: 13px;
  font-weight: 600;
  color: #303133;
}

.grp-actions {
  display: flex;
  gap: 8px;
}

.grp-actions a {
  font-size: 12px;
  color: #409eff;
  text-decoration: none;
}

.grp-actions a:hover {
  text-decoration: underline;
}

.grp-grid {
  padding: 0 30px;
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 4px 8px;
}

.grp-item {
  padding: 4px 0;
}

.grp-item :deep(.el-checkbox) {
  display: flex;
  align-items: center;
  width: 100%;
  margin-right: 0;
}

.grp-item :deep(.el-checkbox__label) {
  font-size: 13px;
  color: #606266;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.grp-empty {
  padding: 48px 16px;
  text-align: center;
  color: #909399;
  font-size: 13px;
}

.cfg-right {
  width: 280px;
  flex-shrink: 0;
  border-left: 1px solid #f1f1f1;
  display: flex;
  flex-direction: column;
  background: #fff;
}

.sel-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 10px 12px;
  border-bottom: 1px solid #f1f1f1;
  background: #f5f7fa;
  flex-shrink: 0;
}

.sel-count {
  font-size: 13px;
  color: #606266;
  font-weight: 500;
}

.sel-reset {
  font-size: 12px;
  color: #409eff;
  text-decoration: none;
}

.sel-reset:hover {
  text-decoration: underline;
}

.sel-body {
  flex: 1;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
}

.sel-fix-zone {
  flex-shrink: 0;
}

.sel-fix-row {
  display: flex;
  align-items: center;
  padding: 0 12px;
  height: 36px;
  background: #f5f7fa;
  border-bottom: 1px solid #f0f2f5;
}

.sel-lock {
  font-size: 12px;
  color: #c0c4cc;
  margin-right: 8px;
  flex-shrink: 0;
}

.sel-fix-name {
  font-size: 13px;
  color: #606266;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.sel-sepline {
  display: flex;
  align-items: center;
  padding: 6px 12px;
  flex-shrink: 0;
  background: #fff;
}

.sel-sepline::before,
.sel-sepline::after {
  content: '';
  flex: 1;
  border-top: 1px dashed #dcdfe6;
}

.sel-septip {
  padding: 0 8px;
  font-size: 11px;
  color: #c0c4cc;
  white-space: nowrap;
}

.sel-drag-zone {
  flex: 1;
}

.sel-drag-row {
  display: flex;
  align-items: center;
  height: 36px;
  padding: 0 4px 0 8px;
  border-bottom: 1px solid #f5f7fa;
  transition: background 0.12s;
}

.sel-drag-row:hover {
  background: #f5f7fa;
}

.sel-drag-handle {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 20px;
  height: 100%;
  cursor: grab;
  flex-shrink: 0;
  color: #c0c4cc;
}

.sel-drag-handle:active {
  cursor: grabbing;
}

.sel-drag-dots {
  display: inline-block;
  width: 6px;
  height: 14px;
  background-image: radial-gradient(circle, currentColor 1.2px, transparent 1.2px);
  background-size: 3px 4px;
  background-repeat: repeat;
}

.sel-drag-name {
  flex: 1;
  font-size: 13px;
  color: #303133;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  margin: 0 4px;
}

.sel-remove {
  flex-shrink: 0;
  width: 20px;
  height: 20px;
  font-size: 12px;
  color: #c0c4cc;
  cursor: pointer;
  border-radius: 3px;
  transition:
    color 0.15s,
    background 0.15s;
}

.sel-remove:hover {
  color: #f56c6c;
  background: #fef0f0;
}

.sel-empty {
  padding: 24px 12px;
  text-align: center;
  font-size: 13px;
  color: #c0c4cc;
}

.drawer-foot {
  flex-shrink: 0;
  box-sizing: border-box;
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 10px 20px;
  border-top: 1px solid #f1f1f1;
}

.left-btn-group > button {
  margin-left: 0;
  margin-right: 10px;
}

.drawer-title .tips.status-warning {
  color: #e6a23c;
}

.drawer-title .tips.status-success {
  color: #67c23a;
}

.save-to-local-form {
  display: flex;
  align-items: center;
  gap: 10px;
}
</style>

<style>
.do-config-column-dialog .el-drawer__body {
  padding: 0;
  overflow: hidden;
  display: flex;
  flex-direction: column;
}
</style>

// packages/r-custom-columns/src/components/DoConfigColumnDialog.tsx
import { CloseOutlined, LockOutlined, SearchOutlined } from '@ant-design/icons';
import { App, Button, Checkbox, Drawer, Input, Popover, message as staticMessage } from 'antd';
import type { InputRef } from 'antd';
import { forwardRef, useEffect, useImperativeHandle, useMemo, useRef, useState } from 'react';
import Sortable from 'sortablejs';

import { useOptionalSchemaColumnConfigContext } from '../context';
import type { ColumnConfig, TableColumnMeta } from '../types';
import { DEFAULT_CUSTOM_COLUMN_MESSAGES } from '../useSchemaColumnConfig';

import { DoReadColumnConfig } from './DoReadColumnConfig';

export interface DoConfigColumnDialogProps {
  /** 点击「完成」，携带当前配置 */
  onConfirm?: (config: ColumnConfig) => void;
}

export interface DoConfigColumnDialogRef {
  /** 打开抽屉；不传则用默认配置 */
  showConfigColumnDialog: (currentConfig?: ColumnConfig) => void;
}

/**
 * 自定义列配置抽屉：左侧分组导航、中间分组勾选、右侧已选列（固定区 + 拖拽排序），
 * 底部存到本地 / 读取本地 / 取消 / 完成。需在 SchemaColumnConfigContext 内使用。
 */
export const DoConfigColumnDialog = forwardRef<DoConfigColumnDialogRef, DoConfigColumnDialogProps>(
  function DoConfigColumnDialog({ onConfirm }, ref) {
    const ctx = useOptionalSchemaColumnConfigContext();
    const messages = ctx?.messages ?? DEFAULT_CUSTOM_COLUMN_MESSAGES;
    const noNameLabel = ctx?.noNameLabel || messages.noNameLabel;
    const maxCount = ctx?.maxSelectCount || 50;
    const { message: appMessage } = App.useApp();
    const message = typeof appMessage.warning === 'function' ? appMessage : staticMessage;

    const [visible, setVisible] = useState(false);
    const [popperSaveToLocal, setPopperSaveToLocal] = useState(false);
    const [popperReadFromLocal, setPopperReadFromLocal] = useState(false);
    const [columnList, setColumnList] = useState<TableColumnMeta[]>([]);
    const [emitColumnConfig, setEmitColumnConfig] = useState<TableColumnMeta[]>([]);
    const [newConfigName, setNewConfigName] = useState(noNameLabel);
    const [searchKeyword, setSearchKeyword] = useState('');
    const [activeNavGroup, setActiveNavGroup] = useState('');

    const midPanelRef = useRef<HTMLDivElement>(null);
    const groupRefs = useRef(new Map<string, HTMLElement>());
    const inputConfigNameRef = useRef<InputRef>(null);
    const [dragZoneEl, setDragZoneEl] = useState<HTMLDivElement | null>(null);

    const unableToControl = (col: TableColumnMeta): boolean =>
      col.type === 'selection' ||
      col.fixed ||
      col.label === messages.operationColumnLabel ||
      col.label === '操作';

    const groupOf = (col: TableColumnMeta) => col.group || messages.groupFallback;

    const uniqueGroups = useMemo(() => {
      const seen = new Set<string>();
      columnList.forEach((item) => seen.add(item.group || messages.groupFallback));
      return [...seen];
    }, [columnList, messages.groupFallback]);

    const filteredGroups = useMemo(() => {
      const keyword = searchKeyword.trim().toLowerCase();
      const groupMap = new Map<string, TableColumnMeta[]>();
      columnList.forEach((item) => {
        if (keyword && !item.label.toLowerCase().includes(keyword)) return;
        const g = item.group || messages.groupFallback;
        if (!groupMap.has(g)) groupMap.set(g, []);
        groupMap.get(g)!.push(item);
      });
      return uniqueGroups
        .filter((g) => groupMap.has(g))
        .map((g) => ({ label: g, children: groupMap.get(g)! }));
    }, [columnList, searchKeyword, uniqueGroups, messages.groupFallback]);

    const alwaysCols = useMemo<TableColumnMeta[]>(
      () =>
        (ctx?.alwaysVisibleColumns || []).map((col) => ({
          property: col.prop,
          label: col.label,
          fixed: true,
          group: messages.groupFallback,
          isLeaf: true,
          visible: true,
          _alwaysVisible: true,
        })),
      [ctx?.alwaysVisibleColumns, messages.groupFallback],
    );

    const fixedSelectedCols = [...alwaysCols, ...emitColumnConfig.filter(unableToControl)];
    const draggableList = emitColumnConfig.filter((col) => !unableToControl(col));

    /** 与本地缓存逐一比对，命中则沿用其名称，否则视为未命名 */
    const matchConfigName = (cols: TableColumnMeta[]): string | null => {
      const cache = ctx?.readCacheConfig();
      if (!cache) return null;
      const temp = JSON.stringify(cols.map((item) => item.property));
      const hit = cache.columnConfig.filter((config) => JSON.stringify(config.columns) === temp);
      return hit.length ? hit[hit.length - 1].label : noNameLabel;
    };

    const commitEmit = (cols: TableColumnMeta[]) => {
      setEmitColumnConfig(cols);
      const name = matchConfigName(cols);
      if (name !== null) setNewConfigName(name);
    };

    const syncEmitWithVisible = (list: TableColumnMeta[]) => {
      const visibleProps = list.filter((col) => col.visible).map((col) => col.property);
      const next = emitColumnConfig.filter((col) => visibleProps.includes(col.property));
      visibleProps.forEach((property) => {
        if (next.some((col) => col.property === property)) return;
        const col = list.find((c) => c.property === property);
        if (col) next.push(col);
      });
      setColumnList(list);
      commitEmit(next);
    };

    const applyConfig = (columnConfig: ColumnConfig) => {
      if (!ctx) return;
      setNewConfigName(columnConfig.label);
      const allColumns = ctx.tableColumns.map((item) => ({
        ...item,
        visible: columnConfig.columns.includes(item.property as string),
      }));
      setColumnList(allColumns);
      setEmitColumnConfig(
        columnConfig.columns
          .map((property) => allColumns.find((col) => col.property === property))
          .filter((col): col is TableColumnMeta => !!col),
      );
    };

    useImperativeHandle(ref, () => ({
      showConfigColumnDialog(currentConfig?: ColumnConfig) {
        if (!ctx) return;
        const columnConfig = currentConfig || ctx.getDefaultConfig();
        if (!columnConfig) return;
        applyConfig(columnConfig);
        const first = ctx.tableColumns[0];
        setActiveNavGroup(first ? first.group || messages.groupFallback : '');
        setSearchKeyword('');
        setVisible(true);
      },
    }));

    const closePoppers = () => {
      setPopperSaveToLocal(false);
      setPopperReadFromLocal(false);
    };

    const cancelColumnConfig = () => {
      closePoppers();
      setVisible(false);
      ctx?.onDialogClose?.();
    };

    const confirmColumnConfig = () => {
      closePoppers();
      setVisible(false);
      onConfirm?.({
        label: newConfigName || noNameLabel,
        columns: emitColumnConfig
          .filter((config) => !config._alwaysVisible)
          .map((config) => config.property as string),
      });
    };

    const resetConfig = () => {
      const defaultConfig = ctx?.getDefaultConfig();
      if (!defaultConfig) return;
      applyConfig(defaultConfig);
      const allColumns = ctx!.tableColumns;
      const name = matchConfigName(
        defaultConfig.columns
          .map((property) => allColumns.find((col) => col.property === property))
          .filter((col): col is TableColumnMeta => !!col),
      );
      if (name !== null) setNewConfigName(name);
    };

    const toggleColumnCheck = (checked: boolean, col: TableColumnMeta) => {
      if (checked && !unableToControl(col)) {
        const willCount = draggableList.length + 1;
        if (willCount > maxCount) {
          message.warning(messages.maxSelectedWarning(maxCount));
          return;
        }
      }
      syncEmitWithVisible(
        columnList.map((item) =>
          item.property === col.property ? { ...item, visible: checked } : item,
        ),
      );
    };

    const groupSelect = (group: string, pick: (item: TableColumnMeta) => boolean) => {
      syncEmitWithVisible(
        columnList.map((item) =>
          !unableToControl(item) && groupOf(item) === group
            ? { ...item, visible: pick(item) }
            : item,
        ),
      );
    };

    const removeSelectedItem = (property?: string) => {
      setColumnList(
        columnList.map((item) => (item.property === property ? { ...item, visible: false } : item)),
      );
      commitEmit(emitColumnConfig.filter((c) => c.property !== property));
    };

    const emitRef = useRef(emitColumnConfig);
    emitRef.current = emitColumnConfig;
    const reorderRef = useRef<(oldIndex: number, newIndex: number) => void>(() => {});
    reorderRef.current = (oldIndex, newIndex) => {
      const current = emitRef.current;
      const reordered = current.filter((col) => !unableToControl(col));
      const [moved] = reordered.splice(oldIndex, 1);
      reordered.splice(newIndex, 0, moved);
      const schemaFixed = current.filter((col) => unableToControl(col) && !col._alwaysVisible);
      commitEmit([...schemaFixed, ...reordered]);
    };

    useEffect(() => {
      if (!dragZoneEl) return;
      const sortable = Sortable.create(dragZoneEl, {
        animation: 200,
        handle: '.sel-drag-handle',
        onUpdate(evt) {
          const { item, from, oldIndex, newIndex } = evt;
          if (oldIndex === undefined || newIndex === undefined) return;
          // 还原 Sortable 的 DOM 移动，交由 React 按新顺序渲染
          from.removeChild(item);
          from.insertBefore(item, from.children[oldIndex] ?? null);
          reorderRef.current(oldIndex, newIndex);
        },
      });
      return () => sortable.destroy();
    }, [dragZoneEl]);

    const scrollToGroup = (group: string) => {
      setActiveNavGroup(group);
      const domEl = groupRefs.current.get(group);
      const panel = midPanelRef.current;
      if (domEl && panel) {
        panel.scrollTo({ top: domEl.offsetTop - panel.offsetTop, behavior: 'smooth' });
      }
    };

    const onMidScroll = () => {
      const panel = midPanelRef.current;
      if (!panel) return;
      const { scrollTop } = panel;
      for (let i = uniqueGroups.length - 1; i >= 0; i--) {
        const domEl = groupRefs.current.get(uniqueGroups[i]);
        if (!domEl) continue;
        if (domEl.offsetTop - panel.offsetTop <= scrollTop + 8) {
          setActiveNavGroup(uniqueGroups[i]);
          break;
        }
      }
    };

    const applyReadConfig = (config: ColumnConfig) => {
      if (!ctx || !config || !config.label || !columnList.length) return;
      const columns =
        !config.columns || !config.columns.length || config.columns.includes('ALL')
          ? ctx.tableColumns.map((each) => each.property as string)
          : config.columns;
      setPopperReadFromLocal(false);
      setNewConfigName(config.label);
      const list = columnList.map((item) => ({
        ...item,
        visible: columns.includes(item.property as string),
      }));
      setColumnList(list);
      setEmitColumnConfig(
        columns
          .map((property) => list.find((col) => col.property === property))
          .filter((col): col is TableColumnMeta => !!col),
      );
    };

    const toSaveToLocal = () => {
      setNewConfigName('');
      setPopperSaveToLocal(true);
      setPopperReadFromLocal(false);
    };

    useEffect(() => {
      if (!popperSaveToLocal) return;
      const id = requestAnimationFrame(() => inputConfigNameRef.current?.focus());
      return () => cancelAnimationFrame(id);
    }, [popperSaveToLocal]);

    const doSaveToLocal = () => {
      if (!ctx || !newConfigName || !newConfigName.trim()) {
        message.warning(messages.configNameRequired);
        return;
      }
      const configName = newConfigName.trim();
      if (ctx.readCacheConfig()?.columnConfig?.some((c) => c.label === configName)) {
        message.warning(messages.configNameExists);
        return;
      }
      ctx.saveConfigToLocal(
        configName,
        emitColumnConfig.map((config) => config.property as string),
      );
      setPopperSaveToLocal(false);
      message.success(messages.configSaved);
    };

    const cancelSaveToLocal = () => {
      const name = matchConfigName(emitColumnConfig);
      if (name !== null) setNewConfigName(name);
      setPopperSaveToLocal(false);
    };

    return (
      <Drawer
        open={visible}
        onClose={cancelColumnConfig}
        className="do-config-column-dialog"
        width={1000}
        placement="right"
        closable={false}
        title={
          <span className="drawer-title">
            {messages.customColumns}{' '}
            <span
              className={[
                'tips',
                newConfigName === noNameLabel ? 'status-warning' : 'status-success',
              ].join(' ')}
            >
              ({newConfigName})
            </span>
          </span>
        }
        extra={
          <button
            type="button"
            className="drawer-close"
            aria-label="Close"
            onClick={cancelColumnConfig}
          >
            <CloseOutlined />
          </button>
        }
      >
        <div className="drawer-wrap">
          <div className="col-dialog-body">
            <div className="cfg-search">
              <Input
                value={searchKeyword}
                onChange={(e) => setSearchKeyword(e.target.value)}
                placeholder={messages.searchPlaceholder}
                allowClear
                size="small"
                prefix={<SearchOutlined />}
              />
            </div>

            <div className="cfg-panels">
              <div className="cfg-left">
                {uniqueGroups.map((group) => (
                  <div
                    key={group}
                    className={['nav-link', activeNavGroup === group ? 'active' : '']
                      .filter(Boolean)
                      .join(' ')}
                    onClick={() => scrollToGroup(group)}
                  >
                    {group}
                  </div>
                ))}
              </div>

              <div
                ref={midPanelRef}
                className="cfg-mid"
                onScroll={onMidScroll}
              >
                {filteredGroups.map((group) => (
                  <div
                    key={group.label}
                    ref={(el) => {
                      if (el) groupRefs.current.set(group.label, el);
                      else groupRefs.current.delete(group.label);
                    }}
                    className="grp-section"
                  >
                    <div className="grp-head">
                      <span className="grp-label">{group.label}</span>
                      <span className="grp-actions">
                        <a onClick={() => groupSelect(group.label, () => true)}>
                          {messages.selectAll}
                        </a>
                        <a onClick={() => groupSelect(group.label, (item) => !item.visible)}>
                          {messages.invertSelection}
                        </a>
                      </span>
                    </div>
                    <div className="grp-grid">
                      {group.children.map((col) => (
                        <div
                          key={col.property}
                          className="grp-item"
                        >
                          <Checkbox
                            checked={col.visible}
                            disabled={unableToControl(col)}
                            onChange={(e) => toggleColumnCheck(e.target.checked, col)}
                          >
                            {col.label}
                          </Checkbox>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
                {filteredGroups.length === 0 ? (
                  <div className="grp-empty">{messages.emptySearch}</div>
                ) : null}
              </div>

              <div className="cfg-right">
                <div className="sel-header">
                  <span className="sel-count">
                    {messages.selectedCount(emitColumnConfig.length, maxCount)}
                  </span>
                  <a
                    className="sel-reset"
                    onClick={resetConfig}
                  >
                    {messages.reset}
                  </a>
                </div>

                <div className="sel-body">
                  {fixedSelectedCols.length ? (
                    <>
                      <div className="sel-fix-zone">
                        {fixedSelectedCols.map((col) => (
                          <div
                            key={col.property}
                            className="sel-fix-row"
                          >
                            <LockOutlined className="sel-lock" />
                            <span className="sel-fix-name">{col.label}</span>
                          </div>
                        ))}
                      </div>
                      <div className="sel-sepline">
                        <span className="sel-septip">{messages.fixedColumnsTip}</span>
                      </div>
                    </>
                  ) : null}

                  <div className="sel-drag-zone">
                    <div ref={setDragZoneEl}>
                      {draggableList.map((col) => (
                        <div
                          key={col.property}
                          className="sel-drag-row"
                        >
                          <span className="sel-drag-handle">
                            <span className="sel-drag-dots" />
                          </span>
                          <span
                            className="sel-drag-name"
                            title={col.label}
                          >
                            {col.label}
                          </span>
                          <CloseOutlined
                            className="sel-remove"
                            onClick={() => removeSelectedItem(col.property)}
                          />
                        </div>
                      ))}
                    </div>
                    {draggableList.length === 0 ? (
                      <div className="sel-empty">{messages.emptySelected}</div>
                    ) : null}
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="drawer-foot">
            <div className="left-btn-group">
              <Popover
                open={popperSaveToLocal}
                placement="top"
                trigger={[]}
                rootClassName="save-to-local-popper"
                content={
                  <div className="save-to-local-form">
                    <Input
                      ref={inputConfigNameRef}
                      className="storage-key-will-save"
                      value={newConfigName}
                      onChange={(e) => setNewConfigName(e.target.value)}
                      placeholder={messages.configNamePlaceholder}
                    />
                    <Button
                      size="small"
                      onClick={cancelSaveToLocal}
                    >
                      {messages.cancel}
                    </Button>
                    <Button
                      size="small"
                      onClick={doSaveToLocal}
                    >
                      {messages.save}
                    </Button>
                  </div>
                }
              >
                <Button onClick={toSaveToLocal}>{messages.saveToLocal}</Button>
              </Popover>

              <Popover
                open={popperReadFromLocal}
                onOpenChange={(open) => {
                  setPopperReadFromLocal(open);
                  if (open) setPopperSaveToLocal(false);
                }}
                placement="top"
                trigger="click"
                rootClassName="read-from-local-popper"
                content={
                  <DoReadColumnConfig
                    onConfirm={applyReadConfig}
                    onRemove={(label) => ctx?.removeConfigFromLocal(label)}
                    onClosed={() => setPopperReadFromLocal(false)}
                  />
                }
              >
                <Button>{messages.readFromLocal}</Button>
              </Popover>
            </div>

            <div className="right-btn-group">
              <Button onClick={cancelColumnConfig}>{messages.cancel}</Button>
              <Button
                type="primary"
                onClick={confirmColumnConfig}
              >
                {messages.complete}
              </Button>
            </div>
          </div>
        </div>
      </Drawer>
    );
  },
);
