// packages/custom-columns/src/components/DoTableHeader.vue
<template>
  <div class="do-table-header">
    <DoConfigColumnDialog
      ref="configDialogRef"
      @confirm="toApplyColumnConfig"
    />

    <div class="table-batch">
      <slot name="batch" />
    </div>

    <div class="table-control">
      <slot name="control" />

      <el-popover
        v-if="!disabledColumnConfig"
        v-model:visible="visiblePopover"
        placement="bottom"
        popper-class="do-table-config-popper"
        trigger="hover"
        :width="240"
        @show="onPopoverShow"
      >
        <template #default>
          <DoReadColumnConfig
            ref="readConfigRef"
            disabled-delete
            show-custom-config-button
            @custom="toCustomColumn"
            @remove="toRemoveConfig"
            @closed="visiblePopover = false"
            @confirm="toApplyColumnConfig"
          />
        </template>
        <template #reference>
          <el-button
            class="do-table-control-btn"
            plain
            size="small"
          >
            {{ messages.customColumns }}
          </el-button>
        </template>
      </el-popover>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, inject, nextTick, ref } from 'vue';

import {
  CRUD_INJECTION_KEY,
  DEFAULT_CUSTOM_COLUMN_MESSAGES,
} from '../composables/useSchemaColumnConfig';
import type { ColumnConfig, CrudContext } from '../types';

import DoConfigColumnDialog from './DoConfigColumnDialog.vue';
import DoReadColumnConfig from './DoReadColumnConfig.vue';

defineOptions({ name: 'DoTableHeader' });

withDefaults(defineProps<{ disabledColumnConfig?: boolean }>(), {
  disabledColumnConfig: true,
});

const crud = inject<CrudContext | null>(CRUD_INJECTION_KEY, null);
const messages = computed(() => crud?.messages || DEFAULT_CUSTOM_COLUMN_MESSAGES);

const visiblePopover = ref(false);
const configDialogRef = ref<InstanceType<typeof DoConfigColumnDialog> | null>(null);
const readConfigRef = ref<InstanceType<typeof DoReadColumnConfig> | null>(null);

function onPopoverShow(): void {
  nextTick(() => readConfigRef.value?.getColumnConfigFromLocal());
}

function toCustomColumn(currentConfig?: ColumnConfig): void {
  configDialogRef.value?.showConfigColumnDialog(currentConfig);
}

function toApplyColumnConfig(config: ColumnConfig): void {
  crud?.applyColumnConfig(config);
}

function toRemoveConfig(label: string): void {
  crud?.removeConfigFromLocal(label);
}
</script>

<style scoped>
.do-table-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  padding: 8px 0;
}

.table-batch {
  display: flex;
  align-items: center;
  gap: 8px;
  flex: 1;
}

.table-control {
  display: flex;
  align-items: center;
  gap: 8px;
}
</style>

// packages/r-custom-columns/src/components/DoTableHeader.tsx
import { Button, Popover } from 'antd';
import { useRef, useState } from 'react';
import type { CSSProperties, ReactNode } from 'react';

import { useOptionalSchemaColumnConfigContext } from '../context';
import type { ColumnConfig } from '../types';
import { DEFAULT_CUSTOM_COLUMN_MESSAGES } from '../useSchemaColumnConfig';

import { DoConfigColumnDialog } from './DoConfigColumnDialog';
import type { DoConfigColumnDialogRef } from './DoConfigColumnDialog';
import { DoReadColumnConfig } from './DoReadColumnConfig';

export interface DoTableHeaderProps {
  /** 隐藏「自定义列」入口，默认 true */
  disabledColumnConfig?: boolean;
  /** 左侧批量操作区 */
  batch?: ReactNode;
  /** 右侧额外控件（自定义列按钮左侧） */
  control?: ReactNode;
  className?: string;
  style?: CSSProperties;
}

/**
 * 表格工具栏：左侧 batch、右侧 control +「自定义列」。
 * 悬停「自定义列」列出本地配置，「自定义配置」打开配置抽屉；需在 SchemaColumnConfigContext 内使用。
 */
export function DoTableHeader(props: DoTableHeaderProps) {
  const { disabledColumnConfig = true, batch, control, className, style } = props;
  const ctx = useOptionalSchemaColumnConfigContext();
  const messages = ctx?.messages ?? DEFAULT_CUSTOM_COLUMN_MESSAGES;
  const [popoverOpen, setPopoverOpen] = useState(false);
  const dialogRef = useRef<DoConfigColumnDialogRef>(null);

  const applyColumnConfig = (config: ColumnConfig) => ctx?.applyColumnConfig(config);

  return (
    <div
      className={['do-table-header', className].filter(Boolean).join(' ')}
      style={style}
    >
      {ctx ? (
        <DoConfigColumnDialog
          ref={dialogRef}
          onConfirm={applyColumnConfig}
        />
      ) : null}

      <div className="table-batch">{batch}</div>
      <div className="table-control">
        {control}
        {!disabledColumnConfig ? (
          <Popover
            open={popoverOpen}
            onOpenChange={setPopoverOpen}
            placement="bottom"
            trigger="hover"
            mouseEnterDelay={0}
            mouseLeaveDelay={0.2}
            rootClassName="do-table-config-popper"
            content={
              <DoReadColumnConfig
                disabledDelete
                showCustomConfigButton
                onConfirm={applyColumnConfig}
                onRemove={(label) => ctx?.removeConfigFromLocal(label)}
                onCustom={(config) => {
                  setPopoverOpen(false);
                  dialogRef.current?.showConfigColumnDialog(config);
                }}
                onClosed={() => setPopoverOpen(false)}
              />
            }
          >
            <Button
              className="do-table-control-btn"
              size="small"
            >
              {messages.customColumns}
            </Button>
          </Popover>
        ) : null}
      </div>
    </div>
  );
}
