// apps/kr-admin/src/components/AppearancePicker.tsx
import { CheckOutlined } from '@ant-design/icons';

import { THEME_OPTIONS, type ThemeMode } from '@/utils/theme';

const DEFAULT_LABELS: Record<ThemeMode, string> = {
  light: '浅色',
  dark: '深色',
  system: '跟随系统',
};

export type AppearancePickerProps = {
  value: ThemeMode;
  onChange: (mode: ThemeMode) => void;
  labelOverrides?: Partial<Record<ThemeMode, string>>;
};

export default function AppearancePicker({
  value,
  onChange,
  labelOverrides,
}: AppearancePickerProps) {
  const labels = { ...DEFAULT_LABELS, ...labelOverrides };

  return (
    <div className="appearance-options">
      {THEME_OPTIONS.map((opt) => {
        const active = value === opt.value;
        return (
          <button
            key={opt.value}
            type="button"
            className={`appearance-option${active ? ' is-active' : ''}`}
            onClick={() => onChange(opt.value)}
          >
            <span>{labels[opt.value]}</span>
            {active ? <CheckOutlined /> : null}
          </button>
        );
      })}
    </div>
  );
}

// apps/kv3-admin/src/components/AppearancePicker.vue
<template>
  <div class="appearance-options">
    <button
      v-for="opt in THEME_OPTIONS"
      :key="opt.value"
      type="button"
      class="appearance-option"
      :class="{ 'is-active': modelValue === opt.value }"
      @click="$emit('update:modelValue', opt.value)"
    >
      <span>{{ resolvedLabels[opt.value] }}</span>
      <el-icon v-if="modelValue === opt.value">
        <Check />
      </el-icon>
    </button>
  </div>
</template>

<script setup lang="ts">
import { Check } from '@element-plus/icons-vue';
import { computed } from 'vue';

import { THEME_OPTIONS, type ThemeMode } from '@/utils/theme';

const props = defineProps<{
  modelValue: ThemeMode;
  labelOverrides?: Partial<Record<ThemeMode, string>>;
}>();

defineEmits<{
  'update:modelValue': [value: ThemeMode];
}>();

const defaultThemeLabels: Record<ThemeMode, string> = {
  light: '浅色',
  dark: '深色',
  system: '跟随系统',
};

const resolvedLabels = computed(() => ({
  ...defaultThemeLabels,
  ...props.labelOverrides,
}));
</script>
