// apps/kr-admin/src/components/CellState.tsx
import { LoadingOutlined } from '@ant-design/icons';
import { Popconfirm, Switch } from 'antd';

export type CellStateProps = {
  modelValue: string | number | boolean | null | undefined;
  activeValue?: string | number | boolean;
  inactiveValue?: string | number | boolean;
  activeLabel?: string;
  inactiveLabel?: string;
  activeType?: 'success' | 'warning' | 'danger' | 'info' | 'primary';
  inactiveType?: 'success' | 'warning' | 'danger' | 'info' | 'primary';
  switchable?: boolean;
  switching?: boolean;
  activeTips?: string;
  inactiveTips?: string;
  /** true 时不经确认直接切换（与 kv3 CellState.manual 对齐） */
  manual?: boolean;
  onSwitch?: (next: string | number | boolean) => void;
};

/**
 * 状态单元格：可切换时为 Switch+确认；只读时为圆点+文案指示器。
 * 行为对齐 kv3 `CellState.vue`。
 */
export function CellState({
  modelValue,
  activeValue = 1,
  inactiveValue = 0,
  activeLabel = '启用',
  inactiveLabel = '禁用',
  activeType = 'success',
  inactiveType = 'info',
  switchable = false,
  switching = false,
  activeTips = '确认启用？',
  inactiveTips = '确认禁用？',
  manual = false,
  onSwitch,
}: CellStateProps) {
  const isActive = modelValue === activeValue;
  const targetValue = isActive ? inactiveValue : activeValue;
  const confirmTitle = isActive ? inactiveTips : activeTips;

  const emitSwitch = () => {
    onSwitch?.(targetValue);
  };

  if (switchable) {
    const sw = (
      <Switch
        size="small"
        checked={isActive}
        disabled={switching}
        onChange={() => {
          if (manual) emitSwitch();
        }}
      />
    );

    return (
      <div className="cell-state">
        {manual ? (
          sw
        ) : (
          <Popconfirm
            title={confirmTitle}
            okText="确定"
            cancelText="取消"
            onConfirm={emitSwitch}
          >
            {/* antd Switch 需包一层可聚焦节点供 Popconfirm 触发 */}
            <span className="cell-state-switch-wrap">{sw}</span>
          </Popconfirm>
        )}
        {switching ? (
          <LoadingOutlined
            className="cell-state-loading"
            spin
          />
        ) : null}
      </div>
    );
  }

  return (
    <div className="cell-state">
      <span className={`cell-state-indicator is-${isActive ? activeType : inactiveType}`}>
        {isActive ? activeLabel : inactiveLabel}
      </span>
    </div>
  );
}

export default CellState;

// apps/kv3-admin/src/components/CellState.vue
<template>
  <div class="cell-state">
    <!-- Switch mode -->
    <template v-if="switchable">
      <el-popconfirm
        v-if="!manual"
        :title="isActive ? resolvedConfirmDisable : resolvedConfirmEnable"
        @confirm="emitSwitch"
      >
        <template #reference>
          <el-switch
            :model-value="isActive"
            :disabled="switching"
          />
        </template>
      </el-popconfirm>
      <el-switch
        v-else
        :model-value="isActive"
        :disabled="switching"
        @change="emitSwitch"
      />
      <el-icon
        v-if="switching"
        class="cell-state-loading"
      >
        <Loading />
      </el-icon>
    </template>
    <!-- Tag mode: 圆点 + 文字指示器，不带背景、不像按钮 -->
    <span
      v-else
      class="cell-state-indicator"
      :class="`is-${isActive ? activeType : inactiveType}`"
    >
      {{ isActive ? resolvedActiveLabel : resolvedInactiveLabel }}
    </span>
  </div>
</template>

<script setup lang="ts">
import { Loading } from '@element-plus/icons-vue';
import { computed } from 'vue';

type TagType = 'success' | 'warning' | 'danger' | 'info' | 'primary';

interface Props {
  modelValue: string | number | boolean | null | undefined;
  activeValue?: string | number | boolean;
  inactiveValue?: string | number | boolean;
  activeLabel?: string;
  inactiveLabel?: string;
  activeType?: TagType;
  inactiveType?: TagType;
  size?: 'large' | 'default' | 'small';
  switchable?: boolean;
  switching?: boolean;
  activeTips?: string;
  inactiveTips?: string;
  manual?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  activeValue: 1,
  inactiveValue: 0,
  activeLabel: undefined,
  inactiveLabel: undefined,
  activeType: 'success',
  inactiveType: 'info',
  size: 'default',
  switchable: false,
  switching: false,
  activeTips: undefined,
  inactiveTips: undefined,
  manual: false,
});

const emit = defineEmits<{
  (e: 'switch', value: string | number | boolean): void;
}>();

const resolvedActiveLabel = computed(() => props.activeLabel ?? '启用');
const resolvedInactiveLabel = computed(() => props.inactiveLabel ?? '禁用');
const resolvedConfirmEnable = computed(() => props.activeTips ?? '确认启用？');
const resolvedConfirmDisable = computed(() => props.inactiveTips ?? '确认禁用？');

const isActive = computed(() => props.modelValue === props.activeValue);
const targetValue = computed(() =>
  isActive.value ? (props.inactiveValue ?? 0) : (props.activeValue ?? 1),
);

function emitSwitch() {
  emit('switch', targetValue.value);
}
</script>

<style lang="scss" scoped>
.cell-state {
  display: inline-flex;
  align-items: center;
  gap: 6px;

  .cell-state-loading {
    font-size: 14px;
    color: var(--el-color-primary);
    animation: cell-state-spin 1s linear infinite;
  }
}

.cell-state-indicator {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  font-size: 12px;
  font-weight: 500;

  &::before {
    content: '';
    display: inline-block;
    width: 6px;
    height: 6px;
    border-radius: 50%;
    flex-shrink: 0;
  }
}

.cell-state-indicator.is-success {
  color: var(--el-color-success);

  &::before {
    background: var(--el-color-success);
  }
}

.cell-state-indicator.is-danger {
  color: var(--el-color-danger);

  &::before {
    background: var(--el-color-danger);
  }
}

.cell-state-indicator.is-warning {
  color: var(--el-color-warning);

  &::before {
    background: var(--el-color-warning);
  }
}

.cell-state-indicator.is-info {
  color: var(--el-text-color-secondary);

  &::before {
    background: var(--el-text-color-secondary);
  }
}

.cell-state-indicator.is-primary {
  color: var(--el-color-primary);

  &::before {
    background: var(--el-color-primary);
  }
}

@keyframes cell-state-spin {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
}
</style>
