// apps/kr-admin/src/modules/_example/schoolSelector/SchoolSelectorDemoLayer.tsx
import { Button } from 'antd';
import { useState } from 'react';

import DialogEditSchoolSelectorDemo, {
  type SchoolSelectorDemoForm,
} from './_module/DialogEditSchoolSelectorDemo';

import DoFilterPanel from '@/components/DoFilterPanel';
import SchoolSelector from '@/modules/_example/schoolResource/_module/SchoolSelector';
import type { SchoolSelectorValue } from '@/modules/_example/schoolResource/_module/types';

function formatMultiLabels(list: SchoolSelectorValue[]) {
  if (!list.length) return '';
  return list.map((item) => item.label).join('、');
}

export default function SchoolSelectorDemoLayer() {
  const [schoolSingle, setSchoolSingle] = useState<SchoolSelectorValue | null>(null);
  const [schoolMulti, setSchoolMulti] = useState<SchoolSelectorValue[]>([]);
  const [lastFilterSnapshot, setLastFilterSnapshot] = useState('');
  const [lastDialogSnapshot, setLastDialogSnapshot] = useState('');
  const [editOpen, setEditOpen] = useState(false);
  const [editSeed, setEditSeed] = useState<SchoolSelectorDemoForm | null>(null);

  function handleFilterSearch() {
    setLastFilterSnapshot(
      JSON.stringify({
        single: schoolSingle?.id ?? null,
        multi: schoolMulti.map((item) => item.id),
      }),
    );
  }

  function handleFilterReset() {
    setSchoolSingle(null);
    setSchoolMulti([]);
    setLastFilterSnapshot('');
  }

  function openCreateDemo() {
    setEditSeed(null);
    setEditOpen(true);
  }

  function openEditDemo() {
    setEditSeed({
      id: 'demo-1',
      demoName: '演示班级计划',
      schoolSingle,
      schoolMulti: [...schoolMulti],
    });
    setEditOpen(true);
  }

  function onDialogSuccess(payload: SchoolSelectorDemoForm) {
    setLastDialogSnapshot(
      `${payload.demoName}｜单选=${payload.schoolSingle?.label || '—'}｜多选=${
        formatMultiLabels(payload.schoolMulti) || '—'
      }`,
    );
  }

  return (
    <div className="page-example-school-selector-demo">
      <section className="page-example-school-selector-demo-card">
        <h3 className="page-example-school-selector-demo-section">筛选区（单选 / 多选）</h3>
        <DoFilterPanel
          line={1}
          onSearch={handleFilterSearch}
          ctl={<Button onClick={handleFilterReset}>重置</Button>}
        >
          <div className="do-filter-field">
            <span className="do-filter-field-label do-filter-field-label-wide">学校（单选）</span>
            <SchoolSelector
              value={schoolSingle}
              onChange={(v) => setSchoolSingle(v && !Array.isArray(v) ? v : null)}
              placeholder="请选择学校"
            />
          </div>
          <div className="do-filter-field">
            <span className="do-filter-field-label do-filter-field-label-wide">学校（多选）</span>
            <SchoolSelector
              value={schoolMulti}
              onChange={(v) => setSchoolMulti(Array.isArray(v) ? v : [])}
              multiple
              placeholder="请选择学校（可多选）"
              defaultPageSize={5}
            />
          </div>
        </DoFilterPanel>
        <p className="page-example-school-selector-demo-meta">
          当前值：单选=
          {schoolSingle?.label || '—'}
          ；多选={formatMultiLabels(schoolMulti) || '—'}
        </p>
        {lastFilterSnapshot ? (
          <p className="page-example-school-selector-demo-meta">
            上次查询快照：{lastFilterSnapshot}
          </p>
        ) : null}
      </section>

      <section className="page-example-school-selector-demo-card">
        <h3 className="page-example-school-selector-demo-section">弹层表单回填</h3>
        <div className="page-example-school-selector-demo-actions">
          <Button
            type="primary"
            onClick={openCreateDemo}
          >
            新建演示
          </Button>
          <Button onClick={openEditDemo}>编辑演示</Button>
        </div>
        {lastDialogSnapshot ? (
          <p className="page-example-school-selector-demo-meta">
            上次弹层提交：{lastDialogSnapshot}
          </p>
        ) : null}
      </section>

      <DialogEditSchoolSelectorDemo
        open={editOpen}
        seed={editSeed}
        onClose={() => setEditOpen(false)}
        onSuccess={onDialogSuccess}
      />
    </div>
  );
}

// apps/kv3-admin/src/modules/_example/schoolSelector/SchoolSelectorDemoLayer.vue
<template>
  <div class="page-example-school-selector-demo">
    <section class="page-example-school-selector-demo-card">
      <h3 class="page-example-school-selector-demo-section">筛选区（单选 / 多选）</h3>
      <DoFilterPanel
        :line="1"
        @search="handleFilterSearch"
      >
        <el-form
          class="with-btn"
          inline
          label-width="120px"
          @submit.prevent
        >
          <el-form-item label="学校（单选）">
            <SchoolSelector
              v-model="listFilters.schoolSingle"
              placeholder="请选择学校"
            />
          </el-form-item>
          <el-form-item label="学校（多选）">
            <SchoolSelector
              v-model="listFilters.schoolMulti"
              multiple
              placeholder="请选择学校（可多选）"
              :default-page-size="5"
            />
          </el-form-item>
        </el-form>
        <template #ctl>
          <el-button @click="handleFilterReset">重置</el-button>
        </template>
      </DoFilterPanel>
      <p class="page-example-school-selector-demo-meta">
        当前值：单选={{ listFilters.schoolSingle?.label || '—' }}；多选={{
          formatMultiLabels(listFilters.schoolMulti) || '—'
        }}
      </p>
      <p
        v-if="lastFilterSnapshot"
        class="page-example-school-selector-demo-meta"
      >
        上次查询快照：{{ lastFilterSnapshot }}
      </p>
    </section>

    <section class="page-example-school-selector-demo-card">
      <h3 class="page-example-school-selector-demo-section">弹层表单回填</h3>
      <div class="page-example-school-selector-demo-actions">
        <el-button
          type="primary"
          @click="openCreateDemo"
        >
          新建演示
        </el-button>
        <el-button @click="openEditDemo">编辑演示</el-button>
      </div>
      <p
        v-if="lastDialogSnapshot"
        class="page-example-school-selector-demo-meta"
      >
        上次弹层提交：{{ lastDialogSnapshot }}
      </p>
    </section>

    <DialogEditSchoolSelectorDemo
      ref="dialogEditDemoRef"
      @success="onDialogSuccess"
    />
  </div>
</template>

<script setup lang="ts">
import { reactive, ref } from 'vue';

import DialogEditSchoolSelectorDemo from './_module/DialogEditSchoolSelectorDemo.vue';

import SchoolSelector from '@/modules/_example/schoolResource/_module/SchoolSelector.vue';
import type { SchoolSelectorValue } from '@/modules/_example/schoolResource/_module/types';

const listFilters = reactive<{
  schoolSingle: SchoolSelectorValue | null;
  schoolMulti: SchoolSelectorValue[];
}>({
  schoolSingle: null,
  schoolMulti: [],
});

const lastFilterSnapshot = ref('');
const lastDialogSnapshot = ref('');
const dialogEditDemoRef = ref<InstanceType<typeof DialogEditSchoolSelectorDemo>>();

function formatMultiLabels(list: SchoolSelectorValue[]) {
  if (!list.length) return '';
  return list.map((item) => item.label).join('、');
}

function handleFilterSearch() {
  lastFilterSnapshot.value = JSON.stringify({
    single: listFilters.schoolSingle?.id ?? null,
    multi: listFilters.schoolMulti.map((item) => item.id),
  });
}

function handleFilterReset() {
  listFilters.schoolSingle = null;
  listFilters.schoolMulti = [];
  lastFilterSnapshot.value = '';
}

function openCreateDemo() {
  dialogEditDemoRef.value?.open();
}

function openEditDemo() {
  dialogEditDemoRef.value?.open({
    id: 'demo-1',
    demoName: '演示班级计划',
    schoolSingle: listFilters.schoolSingle,
    schoolMulti: [...listFilters.schoolMulti],
  });
}

function onDialogSuccess(payload: {
  id: string;
  demoName: string;
  schoolSingle: SchoolSelectorValue | null;
  schoolMulti: SchoolSelectorValue[];
}) {
  lastDialogSnapshot.value = `${payload.demoName}｜单选=${payload.schoolSingle?.label || '—'}｜多选=${
    formatMultiLabels(payload.schoolMulti) || '—'
  }`;
}
</script>

<style lang="scss" scoped>
.page-example-school-selector-demo {
  box-sizing: border-box;
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.page-example-school-selector-demo-card {
  padding: 16px;
  background: var(--ku-bg-card, #f7f3eb);
  border-radius: 8px;
}

.page-example-school-selector-demo-section {
  margin: 0 0 12px;
  font-size: 15px;
  font-weight: 600;
}

.page-example-school-selector-demo-actions {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.page-example-school-selector-demo-meta {
  margin: 8px 0 0;
  color: var(--ku-text-secondary, #909399);
  font-size: 13px;
  word-break: break-all;
}
</style>
