// apps/kv3-admin/src/modules/_example/simpleExample/_module/simpleExample/SimpleExampleBatchSelectList.vue
<template>
  <div class="page-simple-example-batch-select">
    <DoFilterPanel
      :line="1"
      :loading="tableLoading"
      @search="search(true)"
    >
      <el-form
        class="with-btn"
        inline
        label-width="80px"
        @submit.prevent
      >
        <el-form-item label="示例名称">
          <el-input
            v-model="listFilters.exampleName"
            clearable
            placeholder="不限"
            @keyup.enter="search(true)"
          />
        </el-form-item>
        <el-form-item
          label="状态"
          label-width="52px"
        >
          <el-radio-group
            v-model="listFilters.status"
            size="small"
            @change="search(true)"
          >
            <el-radio-button value="">不限</el-radio-button>
            <el-radio-button
              v-for="eachType in $MAPS.example.simpleExample.exampleStatus.options"
              :key="eachType.value"
              :value="eachType.value"
            >
              {{ eachType.label }}
            </el-radio-button>
          </el-radio-group>
        </el-form-item>
      </el-form>
      <template #ctl>
        <el-button
          :disabled="tableLoading"
          @click="handleReset"
        >
          重置
        </el-button>
      </template>
    </DoFilterPanel>

    <TableWrap enable-do-header>
      <!-- 有意放在 #batch：表外全选；用 .batch-select-control 保证热区与文案，避免孤零零 14px 方块 -->
      <template #batch>
        <div
          class="batch-select-control"
          :class="{ 'is-active': statusOfSelect !== 'none-selected' }"
          role="checkbox"
          :aria-checked="
            statusOfSelect === 'all-selected'
              ? 'true'
              : statusOfSelect === 'half-selected'
                ? 'mixed'
                : 'false'
          "
          tabindex="0"
          @click="toggleBatchSelect"
          @keydown.enter.prevent="toggleBatchSelect"
          @keydown.space.prevent="toggleBatchSelect"
        >
          <div
            class="do-select-cell batch-select-box"
            :class="[statusOfSelect, { active: statusOfSelect !== 'none-selected' }]"
          >
            <el-icon v-if="statusOfSelect === 'all-selected'"><Check /></el-icon>
            <el-icon v-if="statusOfSelect === 'half-selected'"><Minus /></el-icon>
          </div>
          <span class="batch-select-label">全选本页</span>
          <span
            v-if="selectRows.length"
            class="batch-select-count"
          >
            已选 {{ selectRows.length }}
          </span>
        </div>
      </template>

      <el-table
        v-loading="tableLoading"
        class="do-inner-scroller page-table hide-table-border"
        :data="tableData"
        :max-height="maxHeight"
        border
        stripe
        @row-click="onRowClick"
      >
        <el-table-column
          fixed="left"
          width="55"
          align="center"
        >
          <template #default="{ row }">
            <div
              class="do-select-cell"
              :class="{ active: isRowSelected(row as ExampleRow) }"
              @click.stop="chooseRow(row as ExampleRow)"
            >
              <el-icon><Check /></el-icon>
            </div>
          </template>
        </el-table-column>

        <el-table-column
          label="示例名称"
          prop="exampleName"
          min-width="160"
          class-name="name-slot-cell"
          show-overflow-tooltip
        >
          <template #default="{ row }">
            <CellNameId
              :id="row.id"
              :name="row.exampleName"
            />
          </template>
        </el-table-column>
        <el-table-column
          label="产品包名"
          prop="pkg"
          min-width="160"
        />
        <el-table-column
          label="状态"
          prop="status"
          width="100"
          align="center"
        >
          <template #default="{ row }">
            <CellState
              :model-value="(row as ExampleRow).status"
              :active-value="1"
              :inactive-value="0"
              :active-label="$MAPS.example.simpleExample.exampleStatus.getLabel(1)"
              :inactive-label="$MAPS.example.simpleExample.exampleStatus.getLabel(0)"
            />
          </template>
        </el-table-column>
        <el-table-column
          label="创建时间"
          prop="createTime"
          min-width="160"
        >
          <template #default="{ row }">
            <CellDateTime :value="(row as ExampleRow).createTime" />
          </template>
        </el-table-column>
      </el-table>

      <template #ft>
        <BasePagination
          :page-num="listFilters.pageNum"
          :page-size="listFilters.pageSize"
          :total="tableTotal"
          :page-sizes="[10, 20, 50]"
          @update:page-num="handlePageChange"
          @update:page-size="handleSizeChange"
        />
      </template>
    </TableWrap>
  </div>
</template>

<script setup lang="ts">
import { Check, Minus } from '@element-plus/icons-vue';

import { useAdminTableMaxHeight } from '@/composables/useAdminTableMaxHeight';
import { useRowSelector } from '@/composables/useRowSelector';
import { useTableQuery } from '@/composables/useTableQuery';
import { requestSimpleExampleList } from '@/modules/_example/simpleExample/_api';

defineOptions({ name: 'SimpleExampleBatchSelectList' });

type ExampleRow = {
  id: number;
  exampleName: string;
  pkg: string;
  status: number;
  taskAction: string;
  createTime: string;
  [key: string]: unknown;
};

const maxHeight = useAdminTableMaxHeight('.page-simple-example-batch-select', 400);

const {
  listFilters,
  tableData,
  tableTotal,
  tableLoading,
  search,
  handlePageChange,
  handleSizeChange,
  reset,
} = useTableQuery<ExampleRow, { exampleName: string; status: string | number }>({
  defaultFilters: {
    exampleName: '',
    status: '',
  },
  fetcher: async (query, _signal) =>
    requestSimpleExampleList(query) as Promise<{
      data: { lists: ExampleRow[]; total: number };
    }>,
});

const { selectRows, statusOfSelect, isRowSelected, chooseRow, toggleBatchSelect } =
  useRowSelector<ExampleRow>({
    tableData,
    lineKey: 'id',
    isMultiple: true,
    enableSelector: true,
  });

function handleReset() {
  reset({
    exampleName: '',
    status: '',
  });
}

function onRowClick(row: ExampleRow) {
  chooseRow(row);
}
</script>

// apps/kr-admin/src/modules/_example/simpleExample/_module/SimpleExampleBatchSelectList.tsx
import { Button, Input, Radio, Table } from 'antd';
import type { ColumnsType } from 'antd/es/table';

import CellDateTime from '@/components/CellDateTime';
import CellNameId from '@/components/CellNameId';
import CellState from '@/components/CellState';
import DoFilterPanel from '@/components/DoFilterPanel';
import { DoSelectBatchBox, createSelectColumn } from '@/components/DoSelectCell';
import ListPaginationBar from '@/components/ListPaginationBar';
import TableWrap from '@/components/TableWrap';
import { useAdminTableMaxHeight } from '@/composables/useAdminTableMaxHeight';
import { useRowSelector } from '@/composables/useRowSelector';
import { useTableQuery } from '@/composables/useTableQuery';
import maps from '@/maps';
import { requestSimpleExampleList } from '@/modules/_example/simpleExample/_api';

type ExampleRow = {
  id: number;
  exampleName: string;
  pkg: string;
  status: number;
  taskAction: string;
  createTime: string;
};

/** 表外全选（#batch 区「全选本页」）+ 行勾选，对齐 kv3 `SimpleExampleBatchSelectList.vue` */
export default function SimpleExampleBatchSelectList() {
  const statusMap = maps.example.simpleExample.exampleStatus;
  const maxHeight = useAdminTableMaxHeight('.page-simple-example-batch-select', 400);

  const {
    listFilters,
    setListFilters,
    tableData,
    tableTotal,
    tableLoading,
    search,
    reset,
    handlePageChange,
    handleSizeChange,
  } = useTableQuery<ExampleRow, { exampleName: string; status: number | '' }>({
    defaultFilters: { exampleName: '', status: '' },
    defaultPageSize: 10,
    fetcher: async (query) =>
      requestSimpleExampleList(query) as Promise<{
        data: { lists: ExampleRow[]; total: number };
      }>,
    immediate: true,
  });

  const selector = useRowSelector<ExampleRow>({ tableData, lineKey: 'id', isMultiple: true });
  const { selectRows, statusOfSelect, toggleBatchSelect, chooseRow } = selector;

  const columns: ColumnsType<ExampleRow> = [
    createSelectColumn(selector, { batchHeader: false }),
    {
      title: '示例名称',
      dataIndex: 'exampleName',
      minWidth: 160,
      className: 'name-slot-cell',
      ellipsis: true,
      render: (_, row) => (
        <CellNameId
          id={row.id}
          name={row.exampleName}
        />
      ),
    },
    {
      title: '产品包名',
      dataIndex: 'pkg',
      minWidth: 160,
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 100,
      align: 'center',
      render: (_, row) => (
        <CellState
          modelValue={row.status}
          activeValue={1}
          inactiveValue={0}
          activeLabel={statusMap.getLabel(1)}
          inactiveLabel={statusMap.getLabel(0)}
        />
      ),
    },
    {
      title: '创建时间',
      dataIndex: 'createTime',
      minWidth: 160,
      render: (v) => <CellDateTime value={v} />,
    },
  ];

  return (
    <div className="page-simple-example-batch-select">
      <DoFilterPanel
        line={1}
        loading={tableLoading}
        onSearch={() => void search(true)}
        ctl={
          <Button
            disabled={tableLoading}
            onClick={() => void reset()}
          >
            重置
          </Button>
        }
      >
        <div className="do-filter-field">
          <span className="do-filter-field-label">示例名称</span>
          <Input
            allowClear
            placeholder="不限"
            style={{ width: 180 }}
            value={listFilters.exampleName}
            onChange={(e) => setListFilters({ exampleName: e.target.value })}
            onPressEnter={() => void search(true)}
          />
        </div>
        <div className="do-filter-field">
          <span className="do-filter-field-label do-filter-field-label-sm">状态</span>
          <Radio.Group
            optionType="button"
            buttonStyle="solid"
            size="small"
            value={listFilters.status}
            onChange={(e) => {
              setListFilters({ status: e.target.value });
              void search(true);
            }}
            options={[{ label: '不限', value: '' }, ...statusMap.options]}
          />
        </div>
      </DoFilterPanel>

      <TableWrap
        enableDoHeader
        batch={
          <div
            className={[
              'batch-select-control',
              statusOfSelect !== 'none-selected' ? 'is-active' : '',
            ]
              .filter(Boolean)
              .join(' ')}
            role="checkbox"
            aria-checked={
              statusOfSelect === 'all-selected'
                ? 'true'
                : statusOfSelect === 'half-selected'
                  ? 'mixed'
                  : 'false'
            }
            tabIndex={0}
            onClick={toggleBatchSelect}
            onKeyDown={(e) => {
              if (e.key === 'Enter' || e.key === ' ') {
                e.preventDefault();
                toggleBatchSelect();
              }
            }}
          >
            <DoSelectBatchBox status={statusOfSelect} />
            <span className="batch-select-label">全选本页</span>
            {selectRows.length ? (
              <span className="batch-select-count">已选 {selectRows.length}</span>
            ) : null}
          </div>
        }
        footer={
          <ListPaginationBar
            pageNum={listFilters.pageNum || 1}
            pageSize={listFilters.pageSize || 10}
            total={tableTotal}
            loading={tableLoading}
            onPageChange={(p) => void handlePageChange(p)}
            onSizeChange={(s) => void handleSizeChange(s)}
          />
        }
      >
        <Table
          className="do-inner-scroller page-table hide-table-border"
          rowKey="id"
          loading={tableLoading}
          dataSource={tableData}
          columns={columns}
          pagination={false}
          bordered
          size="middle"
          scroll={{ y: maxHeight }}
          onRow={(row) => ({ onClick: () => chooseRow(row) })}
        />
      </TableWrap>
    </div>
  );
}
