// apps/kv2-admin/src/modules/_example/simpleExample/_module/simpleExample/SimpleExampleList.vue
<template>
  <div
    class="page-simple-example-list"
    :class="{ 'fill-viewport': fillViewportLayout }"
  >
    <DoFilterPanel
      :line="resolvedFilterLine"
      :loading="tableLoading"
      @search="search(true)"
    >
      <el-form
        class="with-btn"
        inline
        :label-width="isFilterPanelDemo ? 'auto' : '80px'"
        @submit.prevent
      >
        <template v-if="isFilterPanelDemo">
          <el-form-item
            v-for="field in demoFields"
            :key="field.key"
            :label="`筛选项 ${field.key.slice(1)}`"
          >
            <el-input
              v-if="field.kind === 'input'"
              v-model="demoFilters[field.key]"
              clearable
              placeholder="不限"
              @keyup.enter="search(true)"
            />
            <el-select
              v-else-if="field.kind === 'select'"
              v-model="demoFilters[field.key]"
              clearable
              placeholder="不限"
            >
              <el-option
                label="不限"
                value=""
              />
              <el-option
                label="启用"
                value="1"
              />
              <el-option
                label="停用"
                value="0"
              />
            </el-select>
            <el-radio-group
              v-else
              v-model="demoFilters[field.key]"
              size="small"
              @change="search(true)"
            >
              <el-radio-button label="">不限</el-radio-button>
              <el-radio-button label="1">启用</el-radio-button>
              <el-radio-button label="0">停用</el-radio-button>
            </el-radio-group>
          </el-form-item>
        </template>
        <template v-else>
          <el-form-item label="示例名称">
            <el-input
              v-model="listFilters.exampleName"
              clearable
              placeholder="不限"
              @keyup.enter="search(true)"
            />
          </el-form-item>

          <el-form-item label="任务类型">
            <el-radio-group
              v-model="listFilters.taskAction"
              size="small"
              @change="search(true)"
            >
              <el-radio-button label="">不限</el-radio-button>
              <el-radio-button
                v-for="eachType in $MAPS.example.simpleExample.exampleTaskAction.options"
                :key="eachType.value"
                :label="eachType.value"
              >
                {{ eachType.label }}
              </el-radio-button>
            </el-radio-group>
          </el-form-item>

          <el-form-item
            label="状态"
            label-width="52px"
          >
            <el-radio-group
              v-model="listFilters.status"
              size="small"
              @change="search(true)"
            >
              <el-radio-button label="">不限</el-radio-button>
              <el-radio-button
                v-for="eachType in $MAPS.example.simpleExample.exampleStatus.options"
                :key="eachType.value"
                :label="eachType.value"
              >
                {{ eachType.label }}
              </el-radio-button>
            </el-radio-group>
          </el-form-item>
        </template>
      </el-form>
      <template
        v-if="resolvedButtonCount >= 2"
        #ctl
      >
        <el-button
          :disabled="tableLoading"
          @click="handleReset"
        >
          重置
        </el-button>
        <el-button
          v-if="resolvedButtonCount >= 3"
          plain
          :disabled="tableLoading"
          @click="onDemoExtra('export')"
        >
          导出
        </el-button>
        <el-button
          v-if="resolvedButtonCount >= 4"
          plain
          :disabled="tableLoading"
          @click="onDemoExtra('more')"
        >
          更多
        </el-button>
      </template>
    </DoFilterPanel>

    <TableWrap>
      <el-table
        v-loading="tableLoading"
        class="do-inner-scroller page-table hide-table-border"
        :data="tableData"
        :max-height="maxHeight"
        border
        stripe
      >
        <el-table-column
          label="示例名称"
          prop="exampleName"
          min-width="160"
          class-name="name-slot-cell"
          show-overflow-tooltip
        >
          <template #default="{ row }">
            <CellNameId
              :id="row.id"
              :name="row.exampleName"
            />
          </template>
        </el-table-column>
        <el-table-column
          label="产品包名"
          prop="pkg"
          min-width="160"
        />
        <el-table-column
          label="任务类型"
          prop="taskAction"
          width="100"
          align="center"
        >
          <template #default="{ row }">
            {{ $MAPS.example.simpleExample.exampleTaskAction.getLabel(row.taskAction) }}
          </template>
        </el-table-column>
        <el-table-column
          label="状态"
          prop="status"
          width="100"
          align="center"
        >
          <template #default="{ row }">
            <CellState
              :value="row.status"
              :active-value="1"
              :inactive-value="0"
              :active-label="$MAPS.example.simpleExample.exampleStatus.getLabel(1)"
              :inactive-label="$MAPS.example.simpleExample.exampleStatus.getLabel(0)"
              switchable
              :switching="isStatusSwitching(row.id)"
              active-tips="确认启用该示例？"
              inactive-tips="确认停用该示例？"
              @switch="switchExampleStatus.bind(null, row)"
            />
          </template>
        </el-table-column>
        <el-table-column
          label="创建时间"
          prop="createTime"
          min-width="160"
        >
          <template #default="{ row }">
            <CellDateTime :value="row.createTime" />
          </template>
        </el-table-column>
        <el-table-column
          width="140"
          fixed="right"
          class-name="ops-column"
        >
          <template #header>
            <el-button
              type="primary"
              size="small"
              @click="openCreate"
            >
              新建示例
            </el-button>
          </template>
          <template #default="{ row }">
            <div class="line-actions">
              <el-button
                type="primary"
                plain
                size="small"
                icon="el-icon-edit"
                title="编辑"
                aria-label="编辑"
                @click="openEdit(row)"
              />
              <el-button
                type="danger"
                plain
                size="small"
                icon="el-icon-delete"
                title="删除"
                aria-label="删除"
                @click="removeRow(row)"
              />
            </div>
          </template>
        </el-table-column>
      </el-table>

      <template #ft>
        <BasePagination
          :page-num="listFilters.pageNum"
          :page-size="listFilters.pageSize"
          :total="tableTotal"
          :page-sizes="[10, 20, 50]"
          @update:page-num="handlePageChange"
          @update:page-size="handleSizeChange"
        />
      </template>
    </TableWrap>

    <DialogEditSimpleExample
      ref="dialogEditRef"
      @success="search(false)"
    />
  </div>
</template>

<script setup lang="ts">
import { Message as ElMessage, MessageBox as ElMessageBox } from 'element-ui';
import { computed, reactive, ref, watch } from 'vue';

import DialogEditSimpleExample from './DialogEditSimpleExample.vue';

import { useAdminTableMaxHeight } from '@/composables/useAdminTableMaxHeight';
import { useTableQuery } from '@/composables/useTableQuery';
import {
  buildDoFilterPanelDemoFields,
  createDoFilterPanelDemoFilters,
} from '@/modules/_example/doFilterPanel/_utils/doFilterPanelDemo';
import {
  requestBatchSimpleExample,
  requestDeleteSimpleExample,
  requestSimpleExampleList,
} from '@/modules/_example/simpleExample/_api';

const props = withDefaults(
  defineProps<{
    /** 主搜索 + #ctl 附加按钮数；1=仅搜索 */
    filterButtonCount?: 1 | 2 | 3 | 4;
    /**
     * 筛选项个数。传入后进入 DoFilterPanel Demo 形态（生成演示字段）；
     * 不传则保持列表示例管理内置 3 项业务筛选。
     */
    filterFieldCount?: number;
    /** 折叠可见行数；Demo 未传时默认 1 */
    filterLine?: number;
    /**
     * 素材管理同形：页根 height:100% + 列 flex + 区内滚动。
     * 用于复现/验收「展开筛选压扁 table-wrap」。
     */
    fillViewportLayout?: boolean;
  }>(),
  {
    filterButtonCount: undefined,
    filterFieldCount: undefined,
    filterLine: undefined,
    fillViewportLayout: false,
  },
);

type ExampleRow = {
  id: number;
  exampleName: string;
  pkg: string;
  status: number;
  taskAction: string;
  createTime: string;
  [key: string]: unknown;
};

const maxHeight = useAdminTableMaxHeight('.page-simple-example-list', 400);
const dialogEditRef = ref<InstanceType<typeof DialogEditSimpleExample>>();
const statusSwitchingIds = ref<Record<string, boolean>>({});

const isFilterPanelDemo = computed(
  () => props.filterFieldCount != null && props.filterFieldCount > 0,
);
const resolvedButtonCount = computed(() => props.filterButtonCount ?? 2);
const resolvedFilterLine = computed(() => props.filterLine ?? 1);

const demoFields = computed(() =>
  isFilterPanelDemo.value ? buildDoFilterPanelDemoFields(props.filterFieldCount!) : [],
);
const demoFilters = reactive<Record<string, string>>({});

watch(
  () => props.filterFieldCount,
  (count) => {
    Object.keys(demoFilters).forEach((key) => {
      delete demoFilters[key];
    });
    if (count != null && count > 0) {
      Object.assign(demoFilters, createDoFilterPanelDemoFilters(count));
    }
  },
  { immediate: true },
);

const {
  listFilters,
  tableData,
  tableTotal,
  tableLoading,
  search,
  handlePageChange,
  handleSizeChange,
  reset,
} = useTableQuery<
  ExampleRow,
  { exampleName: string; taskAction: string | number; status: string | number }
>({
  defaultFilters: {
    exampleName: '',
    taskAction: '',
    status: '',
  },
  defaultPageSize: 10,
  fetcher: async (query, _signal) =>
    requestSimpleExampleList(query) as Promise<{ data: { lists: ExampleRow[]; total: number } }>,
});

function handleReset() {
  if (isFilterPanelDemo.value) {
    const blank = createDoFilterPanelDemoFilters(props.filterFieldCount!);
    Object.keys(demoFilters).forEach((key) => {
      demoFilters[key] = blank[key] ?? '';
    });
    search(true);
    return;
  }
  reset();
}

function onDemoExtra(kind: 'export' | 'more') {
  const label = kind === 'export' ? '导出' : '更多';
  ElMessage.success(`已触发「${label}」（Demo）`);
}

function openCreate() {
  dialogEditRef.value?.open();
}

function openEdit(row: ExampleRow) {
  dialogEditRef.value?.open(row);
}

async function removeRow(row: ExampleRow) {
  await ElMessageBox.confirm(`确认删除「${row.exampleName}」？`, '提示', { type: 'warning' });
  await requestDeleteSimpleExample({ id: row.id });
  ElMessage.success('删除成功');
  search(false);
}

function isStatusSwitching(id: string | number) {
  return !!statusSwitchingIds.value[String(id)];
}

async function switchExampleStatus(row: ExampleRow, nextStatus: string | number | boolean) {
  const key = String(row.id);
  statusSwitchingIds.value = { ...statusSwitchingIds.value, [key]: true };
  try {
    await requestBatchSimpleExample([row.id], Number(nextStatus));
    row.status = Number(nextStatus);
    ElMessage.success(Number(nextStatus) === 1 ? '已启用' : '已停用');
  } finally {
    const nextMap = { ...statusSwitchingIds.value };
    delete nextMap[key];
    statusSwitchingIds.value = nextMap;
  }
}
</script>

<style lang="scss" scoped>
.page-simple-example-list {
  box-sizing: border-box;

  /* 对齐素材管理：定高列 flex + 区内滚动；展开筛选项时依赖 TableWrap flex-shrink:0 防压扁 */
  &.fill-viewport {
    display: flex;
    flex-direction: column;
    height: 100%;
    min-height: 0;
    overflow-y: auto;

    :deep(.do-filter-panel) {
      flex-shrink: 0;
    }

    :deep(.table-wrap) {
      flex-shrink: 0;
    }
  }
}
</style>

// apps/kr-admin/src/modules/_example/simpleExample/_module/SimpleExampleList.tsx
import { DeleteOutlined, EditOutlined } from '@ant-design/icons';
import { Button, Input, Radio, Select, Table } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { useMemo, useState } from 'react';

import DialogEditSimpleExample from './DialogEditSimpleExample';

import CellDateTime from '@/components/CellDateTime';
import CellNameId from '@/components/CellNameId';
import CellState from '@/components/CellState';
import DoFilterPanel from '@/components/DoFilterPanel';
import ListPaginationBar from '@/components/ListPaginationBar';
import TableWrap from '@/components/TableWrap';
import { useAdminTableMaxHeight } from '@/composables/useAdminTableMaxHeight';
import { useTableQuery } from '@/composables/useTableQuery';
import maps from '@/maps';
import {
  buildDoFilterPanelDemoFields,
  createDoFilterPanelDemoFilters,
} from '@/modules/_example/doFilterPanel/_utils/doFilterPanelDemo';
import {
  requestBatchSimpleExample,
  requestDeleteSimpleExample,
  requestSimpleExampleList,
} from '@/modules/_example/simpleExample/_api';
import { message, modal } from '@/plugins/antdApp';

export type SimpleExampleRow = {
  id: string | number;
  exampleName: string;
  pkg?: string;
  taskAction?: string | number;
  status: number;
  createTime?: string;
  [key: string]: unknown;
};

export type SimpleExampleListProps = {
  filterFieldCount?: number;
  filterButtonCount?: number;
  filterLine?: number;
  fillViewportLayout?: boolean;
  pageClassName?: string;
};

export default function SimpleExampleList({
  filterFieldCount,
  filterButtonCount = 2,
  filterLine,
  fillViewportLayout = false,
  pageClassName = 'page-simple-example-list',
}: SimpleExampleListProps) {
  const statusMap = maps.example.simpleExample.exampleStatus;
  const taskMap = maps.example.simpleExample.exampleTaskAction;
  const isFilterPanelDemo = filterFieldCount != null && filterFieldCount > 0;
  const resolvedFilterLine = filterLine ?? (isFilterPanelDemo ? 1 : 1);
  const resolvedButtonCount = filterButtonCount ?? 2;

  const [editOpen, setEditOpen] = useState(false);
  const [editRow, setEditRow] = useState<SimpleExampleRow | null>(null);
  const [statusSwitchingIds, setStatusSwitchingIds] = useState<Record<string, boolean>>({});
  const [demoFilters, setDemoFilters] = useState<Record<string, string>>(() =>
    isFilterPanelDemo ? createDoFilterPanelDemoFilters(filterFieldCount!) : {},
  );

  const demoFields = useMemo(
    () => (isFilterPanelDemo ? buildDoFilterPanelDemoFields(filterFieldCount!) : []),
    [filterFieldCount, isFilterPanelDemo],
  );

  const {
    listFilters,
    setListFilters,
    tableData,
    tableTotal,
    tableLoading,
    search,
    reset,
    patchRow,
    handlePageChange,
    handleSizeChange,
  } = useTableQuery<
    SimpleExampleRow,
    { exampleName: string; status: number | ''; taskAction: string | '' }
  >({
    defaultFilters: { exampleName: '', status: '', taskAction: '' },
    defaultPageSize: 10,
    fetcher: async (query, _signal) =>
      requestSimpleExampleList(query) as Promise<{
        data: { lists: SimpleExampleRow[]; total: number };
      }>,
    immediate: true,
  });

  const maxHeight = useAdminTableMaxHeight(`.${pageClassName}`, 400);

  function handleReset() {
    if (isFilterPanelDemo) {
      setDemoFilters(createDoFilterPanelDemoFilters(filterFieldCount!));
      void search(true);
      return;
    }
    void reset();
  }

  function onDemoExtra(kind: 'export' | 'more') {
    message.success(`已触发「${kind === 'export' ? '导出' : '更多'}」（Demo）`);
  }

  async function switchExampleStatus(row: SimpleExampleRow, nextStatus: string | number | boolean) {
    const key = String(row.id);
    setStatusSwitchingIds((prev) => ({ ...prev, [key]: true }));
    try {
      await requestBatchSimpleExample([row.id], Number(nextStatus));
      patchRow((item) => item.id === row.id, { status: Number(nextStatus) });
      message.success(Number(nextStatus) === 1 ? '已启用' : '已停用');
    } finally {
      setStatusSwitchingIds((prev) => {
        const next = { ...prev };
        delete next[key];
        return next;
      });
    }
  }

  const columns: ColumnsType<SimpleExampleRow> = [
    {
      title: '示例名称',
      dataIndex: 'exampleName',
      minWidth: 160,
      className: 'name-slot-cell',
      render: (_, row) => (
        <CellNameId
          id={row.id}
          name={row.exampleName}
        />
      ),
    },
    {
      title: '产品包名',
      dataIndex: 'pkg',
      minWidth: 160,
      render: (v) => v || '—',
    },
    {
      title: '任务类型',
      dataIndex: 'taskAction',
      width: 100,
      align: 'center',
      render: (v) => taskMap.getLabel?.(v) ?? String(v ?? '—'),
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 100,
      align: 'center',
      render: (_, row) => (
        <CellState
          modelValue={row.status}
          activeValue={1}
          inactiveValue={0}
          activeLabel={statusMap.getLabel(1)}
          inactiveLabel={statusMap.getLabel(0)}
          switchable
          switching={!!statusSwitchingIds[String(row.id)]}
          activeTips="确认启用该示例？"
          inactiveTips="确认停用该示例？"
          onSwitch={(next) => void switchExampleStatus(row, next)}
        />
      ),
    },
    {
      title: '创建时间',
      dataIndex: 'createTime',
      minWidth: 160,
      render: (v) => <CellDateTime value={v} />,
    },
    {
      title: (
        <Button
          type="primary"
          size="small"
          onClick={() => {
            setEditRow(null);
            setEditOpen(true);
          }}
        >
          新建示例
        </Button>
      ),
      key: 'ops',
      width: 140,
      fixed: 'right',
      className: 'ops-column',
      render: (_, row) => (
        <div className="line-actions">
          <Button
            type="primary"
            ghost
            size="small"
            icon={<EditOutlined />}
            title="编辑"
            aria-label="编辑"
            onClick={() => {
              setEditRow(row);
              setEditOpen(true);
            }}
          />
          <Button
            danger
            ghost
            size="small"
            icon={<DeleteOutlined />}
            title="删除"
            aria-label="删除"
            onClick={() => {
              modal.confirm({
                title: '提示',
                content: `确认删除「${row.exampleName}」？`,
                onOk: async () => {
                  await requestDeleteSimpleExample({ id: row.id });
                  message.success('删除成功');
                  void search(false);
                },
              });
            }}
          />
        </div>
      ),
    },
  ];

  const ctl =
    resolvedButtonCount >= 2 ? (
      <>
        <Button
          disabled={tableLoading}
          onClick={handleReset}
        >
          重置
        </Button>
        {resolvedButtonCount >= 3 ? (
          <Button
            disabled={tableLoading}
            onClick={() => onDemoExtra('export')}
          >
            导出
          </Button>
        ) : null}
        {resolvedButtonCount >= 4 ? (
          <Button
            disabled={tableLoading}
            onClick={() => onDemoExtra('more')}
          >
            更多
          </Button>
        ) : null}
      </>
    ) : null;

  return (
    <div
      className={[pageClassName, fillViewportLayout ? 'fill-viewport' : '']
        .filter(Boolean)
        .join(' ')}
    >
      <DoFilterPanel
        line={resolvedFilterLine}
        labelWidth={isFilterPanelDemo ? 'auto' : 80}
        loading={tableLoading}
        onSearch={() => void search(true)}
        ctl={ctl}
        hideSearch={resolvedButtonCount < 1}
      >
        {isFilterPanelDemo
          ? demoFields.map((field) => (
              <div
                className="do-filter-field"
                key={field.key}
              >
                <span className="do-filter-field-label">筛选项 {field.key.slice(1)}</span>
                {field.kind === 'input' ? (
                  <Input
                    allowClear
                    placeholder="不限"
                    value={demoFilters[field.key] ?? ''}
                    onChange={(e) =>
                      setDemoFilters((prev) => ({ ...prev, [field.key]: e.target.value }))
                    }
                    onPressEnter={() => void search(true)}
                  />
                ) : null}
                {field.kind === 'select' ? (
                  <Select
                    allowClear
                    placeholder="不限"
                    value={demoFilters[field.key] ?? ''}
                    onChange={(v) => setDemoFilters((prev) => ({ ...prev, [field.key]: v ?? '' }))}
                    options={[
                      { label: '不限', value: '' },
                      { label: '启用', value: '1' },
                      { label: '停用', value: '0' },
                    ]}
                  />
                ) : null}
                {field.kind === 'radio' ? (
                  <Radio.Group
                    optionType="button"
                    buttonStyle="solid"
                    size="small"
                    value={demoFilters[field.key] ?? ''}
                    onChange={(e) => {
                      setDemoFilters((prev) => ({ ...prev, [field.key]: e.target.value }));
                      void search(true);
                    }}
                    options={[
                      { label: '不限', value: '' },
                      { label: '启用', value: '1' },
                      { label: '停用', value: '0' },
                    ]}
                  />
                ) : null}
              </div>
            ))
          : [
              <div
                className="do-filter-field"
                key="name"
              >
                <span className="do-filter-field-label">示例名称</span>
                <Input
                  allowClear
                  placeholder="不限"
                  value={listFilters.exampleName}
                  onChange={(e) => setListFilters({ exampleName: e.target.value })}
                  onPressEnter={() => void search(true)}
                />
              </div>,
              <div
                className="do-filter-field"
                key="task"
              >
                <span className="do-filter-field-label">任务类型</span>
                <Radio.Group
                  optionType="button"
                  buttonStyle="solid"
                  size="small"
                  value={listFilters.taskAction}
                  onChange={(e) => {
                    setListFilters({ taskAction: e.target.value });
                    void search(true);
                  }}
                  options={[{ label: '不限', value: '' }, ...(taskMap.options || [])]}
                />
              </div>,
              <div
                className="do-filter-field"
                key="status"
              >
                <span className="do-filter-field-label do-filter-field-label-sm">状态</span>
                <Radio.Group
                  optionType="button"
                  buttonStyle="solid"
                  size="small"
                  value={listFilters.status}
                  onChange={(e) => {
                    setListFilters({ status: e.target.value });
                    void search(true);
                  }}
                  options={[{ label: '不限', value: '' }, ...statusMap.options]}
                />
              </div>,
            ]}
      </DoFilterPanel>

      <TableWrap
        footer={
          <ListPaginationBar
            pageNum={listFilters.pageNum || 1}
            pageSize={listFilters.pageSize || 10}
            total={tableTotal}
            loading={tableLoading}
            onPageChange={(p) => void handlePageChange(p)}
            onSizeChange={(s) => void handleSizeChange(s)}
          />
        }
      >
        <Table
          className="do-inner-scroller page-table"
          rowKey="id"
          loading={tableLoading}
          dataSource={tableData}
          columns={columns}
          pagination={false}
          size="middle"
          scroll={{ y: maxHeight }}
        />
      </TableWrap>

      <DialogEditSimpleExample
        open={editOpen}
        row={editRow}
        onClose={() => setEditOpen(false)}
        onSuccess={() => void search(false)}
      />
    </div>
  );
}
